In [23]:
from pathlib import Path
import os, glob, re
import numpy as np
import pandas as pd
from biopandas.pdb import PandasPdb
import MDAnalysis as mda
from rdkit import Chem
import tempfile
import subprocess

# =========================
# Paths
# =========================
RCSB_PROTEIN_DIR = Path("CLR-PDB-matched-to-opm_ids")
UNLABELED_DIR = Path("CLR-Unlabeled-Distinct-matched-to-opm_ids")
OPM_DIR = Path("OPM_PDB")

def get_protein_name(filename):
    basename = os.path.basename(filename)
    match = re.match(r'([a-zA-Z0-9]{4})', basename)
    return match.group(1).upper() if match else None


def get_mode_index(filename):
    basename = os.path.basename(filename)
    match = re.search(r'mode_(\d+)', basename)
    return int(match.group(1)) if match else None


def natural_sort_key(s):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', str(s))]


def grid_list(atom_df):
    return list(zip(atom_df['x_coord'], atom_df['y_coord'], atom_df['z_coord']))


def filtering_proteins(atom_df, grid_list, radius=5.0):
    import numpy as np

    # Adjust these column names if needed for your dataframe
    residue_cols = ['chain_id', 'residue_name', 'residue_number', 'insertion']
    residue_cols = [col for col in residue_cols if col in atom_df.columns]

    if not residue_cols:
        raise ValueError("Could not identify residue columns in atom_df.")

    atom_coords = atom_df[['x_coord', 'y_coord', 'z_coord']].values
    initially_filtered_atoms = set()

    # Step 1: find atoms within radius of any grid point
    for x, y, z in grid_list:
        distances_sq = (
            (atom_coords[:, 0] - x) ** 2 +
            (atom_coords[:, 1] - y) ** 2 +
            (atom_coords[:, 2] - z) ** 2
        )
        mask = distances_sq <= radius ** 2
        initially_filtered_atoms.update(atom_df.index[mask])

    print(f"Total atoms within {radius} Å cutoff: {len(initially_filtered_atoms)}")

    if not initially_filtered_atoms:
        return atom_df.loc[list(initially_filtered_atoms)]

    grouped = atom_df.groupby(residue_cols)

    # Step 2: residues passing the 50% rule
    residue_keep_set = set()

    for residue_key, residue_df in grouped:
        residue_atom_indices = set(residue_df.index)
        n_total = len(residue_atom_indices)
        n_filtered = len(residue_atom_indices & initially_filtered_atoms)

        if n_total == 0:
            continue

        fraction_present = n_filtered / n_total

        if fraction_present >= 0.5:
            residue_keep_set.add(residue_key)

    # Step 3: expand to all atoms in kept residues
    filtered_atoms = set()
    for residue_key, residue_df in grouped:
        if residue_key in residue_keep_set:
            filtered_atoms.update(residue_df.index)

    # Fallback: if nothing survives 50% rule, keep residues that had any atom in cutoff
    if len(filtered_atoms) == 0:
        print("No residues passed the 50% occupancy filter. Falling back to residues with at least one atom within cutoff.")

        fallback_residue_keep_set = set()

        for residue_key, residue_df in grouped:
            residue_atom_indices = set(residue_df.index)
            if len(residue_atom_indices & initially_filtered_atoms) > 0:
                fallback_residue_keep_set.add(residue_key)

        for residue_key, residue_df in grouped:
            if residue_key in fallback_residue_keep_set:
                filtered_atoms.update(residue_df.index)

    print(f"Total atoms after residue expansion + filtering: {len(filtered_atoms)}")
    return atom_df.loc[list(filtered_atoms)]


def read_protein_atoms(pdb_path):
    ppdb = PandasPdb().read_pdb(str(pdb_path))
    atoms = ppdb.df["ATOM"].copy()
    atoms = atoms[~atoms["atom_name"].str.startswith("H")].copy()
    return atoms


def read_clr_atoms(pdb_path):
    ppdb = PandasPdb().read_pdb(str(pdb_path))
    hetatm = ppdb.df["HETATM"].copy()
    clr = hetatm[hetatm["residue_name"] == "CLR"].copy()
    return clr


def atom_match_key(df):
    """
    Match RCSB atoms to OPM atoms by residue number, chain, and atom subtype/name.
    """
    return list(zip(
        df["residue_number"].astype(int),
        df["chain_id"].astype(str),
        df["atom_name"].astype(str).str.strip()
    ))


def map_rcsb_filtered_atoms_to_opm(filtered_rcsb_atoms, opm_atoms):
    """
    Takes atoms filtered using RCSB/Vina coordinate system and returns
    matching atoms from OPM coordinate system.
    """
    filtered_keys = set(atom_match_key(filtered_rcsb_atoms))

    opm_atoms = opm_atoms.copy()
    opm_atoms["_match_key"] = atom_match_key(opm_atoms)

    mapped = opm_atoms[opm_atoms["_match_key"].isin(filtered_keys)].copy()
    mapped = mapped.drop(columns=["_match_key"])

    return mapped


def save_atoms_as_pdb(atom_df, output_path):
    filtered_pdb = PandasPdb()
    filtered_pdb.df["ATOM"] = atom_df.copy()
    filtered_pdb.to_pdb(
        path=str(output_path),
        records=None,
        gz=False,
        append_newline=True
    )


def get_all_opm_clr_gridlists(opm_file):
    ligand = read_clr_atoms(opm_file)
    all_ligands = []

    for residue_number, chain_id in set(zip(ligand["residue_number"], ligand["chain_id"])):
        clr_atoms = ligand[
            (ligand["residue_number"] == residue_number) &
            (ligand["chain_id"] == chain_id)
        ]

        if not clr_atoms.empty:
            all_ligands.append(grid_list(clr_atoms))

    return all_ligands


def check_if_unlabeled_is_positive(positive_grid_list, unlabeled_grid_list, cutoff=5.0):
    positive_grid_list = np.asarray(positive_grid_list, dtype=float)
    unlabeled_grid_list = np.asarray(unlabeled_grid_list, dtype=float)

    if positive_grid_list.size == 0 or unlabeled_grid_list.size == 0:
        return False

    positive_centroid = positive_grid_list.mean(axis=0)
    unlabeled_centroid = unlabeled_grid_list.mean(axis=0)

    distance = np.linalg.norm(positive_centroid - unlabeled_centroid)
    return distance <= cutoff

def make_atom_key(df):
    return list(zip(
        df['residue_number'].astype(int),
        df['chain_id'].astype(str),
        df['atom_name'].astype(str).str.strip()
    ))


def map_rcsb_atoms_to_opm(filtered_rcsb_atoms, opm_protein):
    filtered_keys = set(make_atom_key(filtered_rcsb_atoms))

    opm_protein = opm_protein.copy()
    opm_protein['_key'] = make_atom_key(opm_protein)

    mapped_atoms = opm_protein[opm_protein['_key'].isin(filtered_keys)].copy()
    mapped_atoms = mapped_atoms.drop(columns=['_key'])

    return mapped_atoms

In [24]:
def lookup_charge(chain, resseq, atomname, charges_full, charges_nochain, has_chain):
    # try chain-aware first
    if has_chain:
        val = charges_full.get((chain, resseq, atomname), None)
        if val is not None:
            return val

    # always try no-chain fallback too
    val = charges_nochain.get((resseq, atomname), None)
    if val is not None:
        return val

    return 0.0

def strip_dum_atoms(pdb_path, out_path):
    with open(pdb_path) as f_in, open(out_path, "w") as f_out:
        for line in f_in:
            if "DUM" not in line:
                f_out.write(line)


def run_pdb2pqr(clean_pdb, pqr_out, ph=7.4):
    cmd = [
        "pdb2pqr",
        "--ff=AMBER",
        f"--with-ph={ph}",
        "--quiet",
        str(clean_pdb),
        str(pqr_out),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.returncode == 0

def parse_pqr_charges(pqr_path):
    """
    Returns:
        charges_full[(chain, resseq, atomname)] = charge
        charges_nochain[(resseq, atomname)] = charge
        has_chain = bool
    """
    charges_full = {}
    charges_nochain = {}
    chain_values = set()

    with open(pqr_path) as f:
        for line in f:
            if not line.startswith(("ATOM", "HETATM")):
                continue
            try:
                atomname = line[12:16].strip()
                chain = line[21].strip()
                resseq = int(line[22:26].strip())
                charge = float(line[54:62].strip())
            except (ValueError, IndexError):
                continue

            chain_values.add(chain)
            charges_full[(chain, resseq, atomname)] = charge
            charges_nochain[(resseq, atomname)] = charge

    has_chain = any(c != "" for c in chain_values)
    return charges_full, charges_nochain, has_chain


def build_pqr_cache(full_pdb_dir, ph=7.4):
    full_pdb_dir = Path(full_pdb_dir)
    pdb_files = sorted(full_pdb_dir.glob("*.pdb"))

    pqr_cache = {}
    pqr_failures = []

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)

        for pdb_path in pdb_files:
            stem = pdb_path.stem
            match = re.match(r'([A-Za-z0-9]{4})', stem)
            if not match:
                pqr_failures.append(stem.upper())
                continue

            pdbid = match.group(1).upper()

            clean_pdb = tmpdir / f"{pdbid}_clean.pdb"
            pqr_out = tmpdir / f"{pdbid}.pqr"

            strip_dum_atoms(pdb_path, clean_pdb)

            ok = run_pdb2pqr(clean_pdb, pqr_out, ph=ph)
            if not ok or not pqr_out.exists():
                pqr_failures.append(pdbid)
                continue

            charges_full, charges_nochain, has_chain = parse_pqr_charges(pqr_out)
            pqr_cache[pdbid] = (charges_full, charges_nochain, has_chain)

    print(f"pdb2pqr complete: {len(pqr_cache)} ok, {len(pqr_failures)} failed")
    if pqr_failures:
        print("Failed PDB IDs:", pqr_failures[:20])

In [25]:
def clean_pdb_df_for_saving(df, record_name, start_atom_number=1, start_line_idx=0):
    """
    Cleans a Biopandas ATOM/HETATM dataframe so PandasPdb.to_pdb()
    does not fail from NaN values or wrong dtypes.
    """
    df = df.copy()
    df = df.dropna(how="all").copy()

    if df.empty:
        return df

    df = df.reset_index(drop=True)

    # Required record type
    df["record_name"] = record_name

    # Coordinates must be numeric
    coord_cols = ["x_coord", "y_coord", "z_coord"]
    for col in coord_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df = df.dropna(subset=coord_cols).copy()
    df = df.reset_index(drop=True)

    # Integer-like columns
    df["atom_number"] = np.arange(
        start_atom_number,
        start_atom_number + len(df)
    ).astype(int)

    if "residue_number" not in df.columns:
        df["residue_number"] = 1

    df["residue_number"] = pd.to_numeric(
        df["residue_number"],
        errors="coerce"
    ).fillna(1).astype(int)

    df["line_idx"] = np.arange(
        start_line_idx,
        start_line_idx + len(df)
    ).astype(int)

    # Float columns
    for col, default in {
        "x_coord": 0.0,
        "y_coord": 0.0,
        "z_coord": 0.0,
        "occupancy": 1.00,
        "b_factor": 0.00,
    }.items():
        if col not in df.columns:
            df[col] = default
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(default).astype(float)

    # String columns
    string_defaults = {
        "atom_name": "X",
        "alt_loc": "",
        "residue_name": "UNK",
        "chain_id": "",
        "insertion": "",
        "segment_id": "",
        "element_symbol": "",
        "blank_1": "",
        "blank_2": "",
        "blank_3": "",
        "blank_4": "",
    }

    for col, default in string_defaults.items():
        if col not in df.columns:
            df[col] = default
        df[col] = df[col].fillna(default).astype(str)

    # Important:
    # Do NOT make charge an empty string.
    # Biopandas may expect this column to be float/NaN.
    if "charge" not in df.columns:
        df["charge"] = np.nan
    else:
        df["charge"] = pd.to_numeric(df["charge"], errors="coerce")

    # Clean atom names / element symbols
    df["atom_name"] = df["atom_name"].astype(str).str.strip()
    df["residue_name"] = df["residue_name"].astype(str).str.strip()
    df["chain_id"] = df["chain_id"].astype(str).str.strip()
    df["element_symbol"] = df["element_symbol"].astype(str).str.strip()

    # If element_symbol is missing, infer from atom_name
    missing_element = df["element_symbol"].eq("") | df["element_symbol"].eq("nan")
    df.loc[missing_element, "element_symbol"] = (
        df.loc[missing_element, "atom_name"]
        .str.extract(r"([A-Za-z]+)", expand=False)
        .fillna("C")
        .str[:2]
        .str.capitalize()
    )

    return df

def get_positive_ligand_atoms(positive_file, protein_name):
    protein_pdb_df = PandasPdb().read_pdb(positive_file)
    protein_pdb_df.df.keys()
    protein = protein_pdb_df.df['ATOM']
    protein = protein[~protein['atom_name'].str.startswith('H')] # don't use hydrogen
    protein_coords = protein[['x_coord', 'y_coord', 'z_coord']].values
    protein_centroid = protein_coords.mean(axis=0)
    print(set(protein['chain_id']))
    print(positive_file)

    ligand_df = PandasPdb().read_pdb(positive_file)
    ligand_df.df.keys()
    ligand = ligand_df.df['HETATM']
    ligand = ligand[ligand['residue_name']=="CLR"]
    x = list(set(zip(ligand['residue_number'], ligand['chain_id'])))

    #get the most inward residue
    min_distance = float('inf')
    closest_clr = None

    all_ligands = []

    for residue_number, chain_id in x:
        clr_atoms = ligand[(ligand['residue_number'] == residue_number) & (ligand['chain_id'] == chain_id)]
        if clr_atoms.empty:
            continue

        clr_coords = clr_atoms[['x_coord', 'y_coord', 'z_coord']].values
        clr_centroid = clr_coords.mean(axis=0)
        
        distance = np.linalg.norm(protein_centroid - clr_centroid)
        
        if distance < min_distance:
            min_distance = distance
            closest_clr = (residue_number, chain_id)

        grid_list_ = grid_list(clr_atoms)

        all_ligands.append(grid_list_)

    ligand_ = ligand[(ligand['residue_number'] == closest_clr[0]) & (ligand['chain_id'] == closest_clr[1])]
    grid_list_ = grid_list(ligand_)

    filtered_atoms = filtering_proteins(protein, grid_list_)

    # Save to pdb
    filtered_atoms_clean = clean_pdb_df_for_saving(
        filtered_atoms,
        record_name="ATOM",
        start_atom_number=1,
        start_line_idx=0
    )

    ligand_clean = clean_pdb_df_for_saving(
        ligand_,
        record_name="HETATM",
        start_atom_number=len(filtered_atoms_clean) + 1,
        start_line_idx=len(filtered_atoms_clean)
    )

    filtered_pdb = PandasPdb()
    filtered_pdb.df["ATOM"] = filtered_atoms_clean
    filtered_pdb.df["HETATM"] = ligand_clean

    filtered_pdb_path = f"filtered-opm-ivan-5A/positive/{protein_name}-filtered-with-ligand.pdb"
    os.makedirs(os.path.dirname(filtered_pdb_path), exist_ok=True)

    filtered_pdb.to_pdb(
        path=filtered_pdb_path,
        records=["ATOM", "HETATM"],
        gz=False,
        append_newline=True
    )

    print(f"Saved: {filtered_pdb_path}")

    return protein, all_ligands

In [26]:
def check_if_unlabeled_is_positive(positive_grid_list, unlabeled_grid_list, cutoff=5.0):
    positive_grid_list = np.asarray(positive_grid_list, dtype=float)
    unlabeled_grid_list = np.asarray(unlabeled_grid_list, dtype=float)

    if positive_grid_list.size == 0 or unlabeled_grid_list.size == 0:
        print("Empty positive_grid_list or unlabeled_grid_list")
        return False

    chol_centroid = positive_grid_list.mean(axis=0)
    vina_centroid = unlabeled_grid_list.mean(axis=0)

    distance = np.linalg.norm(chol_centroid - vina_centroid)
    print(f"Centroid distance: {distance:.3f} Å")
    return distance <= cutoff

def kabsch_align_coords(source_coords, target_coords):
    """
    Align source_coords onto target_coords using matched atoms.
    Returns rotation matrix R and translation vector t.
    """
    source_coords = np.asarray(source_coords, dtype=float)
    target_coords = np.asarray(target_coords, dtype=float)

    source_centroid = source_coords.mean(axis=0)
    target_centroid = target_coords.mean(axis=0)

    source_centered = source_coords - source_centroid
    target_centered = target_coords - target_centroid

    H = source_centered.T @ target_centered
    U, S, Vt = np.linalg.svd(H)

    R = Vt.T @ U.T

    if np.linalg.det(R) < 0:
        Vt[-1, :] *= -1
        R = Vt.T @ U.T

    t = target_centroid - source_centroid @ R

    return R, t


def transform_ligand_to_opm_coords(ligand_df, rcsb_protein_df, opm_protein_df):
    """
    Transform Vina/RCSB ligand coordinates into OPM coordinate space.
    Uses matched protein atoms to estimate the rigid-body transform.
    """
    rcsb = rcsb_protein_df.copy()
    opm = opm_protein_df.copy()

    rcsb["_key"] = make_atom_key(rcsb)
    opm["_key"] = make_atom_key(opm)

    rcsb = rcsb.drop_duplicates("_key")
    opm = opm.drop_duplicates("_key")

    merged = rcsb.merge(
        opm,
        on="_key",
        suffixes=("_rcsb", "_opm")
    )

    if len(merged) < 3:
        raise ValueError("Need at least 3 matched atoms to align RCSB ligand to OPM coordinates.")

    source_coords = merged[["x_coord_rcsb", "y_coord_rcsb", "z_coord_rcsb"]].values
    target_coords = merged[["x_coord_opm", "y_coord_opm", "z_coord_opm"]].values

    R, t = kabsch_align_coords(source_coords, target_coords)

    ligand = ligand_df.copy()
    ligand_coords = ligand[["x_coord", "y_coord", "z_coord"]].values.astype(float)
    ligand_coords_opm = ligand_coords @ R + t

    ligand["x_coord"] = ligand_coords_opm[:, 0]
    ligand["y_coord"] = ligand_coords_opm[:, 1]
    ligand["z_coord"] = ligand_coords_opm[:, 2]

    return ligand

In [27]:
# positive_files = glob.glob("OPM_PDB/*.pdb")
# positive_files = sorted(positive_files, key=natural_sort_key)

# unlabeled_files = glob.glob("CLR-Unlabeled-Distinct-matched-to-opm_ids/*.pdb")
# unlabeled_files = sorted(unlabeled_files, key=natural_sort_key)

# RCSB_PROTEIN_DIR = "CLR-PDB-matched-to-opm_ids"
# OPM_DIR = "OPM_PDB"

# for unlabeled_file in unlabeled_files:
#     unlabeled_name = get_protein_name(unlabeled_file)
#     fragment_index = get_mode_index(unlabeled_file)

#     if unlabeled_name is None:
#         print(f"Skipping file with no PDB id match: {unlabeled_file}")
#         continue

#     rcsb_file = os.path.join(RCSB_PROTEIN_DIR, f"{unlabeled_name}_protein.pdb")
#     opm_file = os.path.join(OPM_DIR, f"{unlabeled_name.lower()}.pdb")

#     if not os.path.exists(rcsb_file):
#         print(f"Missing RCSB file: {rcsb_file}")
#         continue

#     if not os.path.exists(opm_file):
#         print(f"Missing OPM file: {opm_file}")
#         continue

#     # OPM positive logic, keeps closest CLR and all_lig_gridlist
#     opm_protein, all_lig_gridlist = get_positive_ligand_atoms(opm_file, unlabeled_name)

#     # RCSB whole protein for filtering against Vina docked CLR
#     rcsb_pdb = PandasPdb().read_pdb(rcsb_file)
#     rcsb_protein = rcsb_pdb.df['ATOM']
#     rcsb_protein = rcsb_protein[~rcsb_protein['atom_name'].str.startswith('H')]

#     fragment_df = PandasPdb().read_pdb(unlabeled_file)
#     fragment = fragment_df.df['HETATM']
#     #fragment = fragment[fragment['residue_name'] == 'CLR']

#     grid_list_ = grid_list(fragment)

#     # Filter RCSB atoms using Vina CLR coordinates
#     filtered_rcsb_atoms = filtering_proteins(rcsb_protein, grid_list_)

#     if filtered_rcsb_atoms.empty:
#         print(f"No filtered RCSB atoms found for {unlabeled_file}")
#         continue

#     # Convert filtered RCSB atoms to OPM coordinates
#     filtered_opm_atoms = map_rcsb_atoms_to_opm(filtered_rcsb_atoms, opm_protein)

#     if filtered_opm_atoms.empty:
#         print(f"No OPM atom matches found for {unlabeled_file}")
#         continue

#     fragment_opm = transform_ligand_to_opm_coords(
#         ligand_df=fragment,
#         rcsb_protein_df=rcsb_protein,
#         opm_protein_df=opm_protein
#     )

#     filtered_opm_atoms_clean = clean_pdb_df_for_saving(
#         filtered_opm_atoms,
#         record_name="ATOM",
#         start_atom_number=1,
#         start_line_idx=0
#     )

#     fragment_opm_clean = clean_pdb_df_for_saving(
#         fragment_opm,
#         record_name="HETATM",
#         start_atom_number=len(filtered_opm_atoms_clean) + 1,
#         start_line_idx=len(filtered_opm_atoms_clean)
#     )

#     filtered_pdb = PandasPdb()
#     filtered_pdb.df["ATOM"] = filtered_opm_atoms_clean
#     filtered_pdb.df["HETATM"] = fragment_opm_clean

#     grid_list_filtered = grid_list(filtered_pdb.df['ATOM'])

#     is_positive = False
#     for lig in all_lig_gridlist:
#         if check_if_unlabeled_is_positive(lig.copy(), grid_list_filtered.copy()):
#             is_positive = True
#             break

#     if is_positive:
#         filtered_pdb_path = f"filtered-opm-vina-5A/unlabeled/{unlabeled_name}-f{fragment_index}-positive-with-ligand.pdb"
#     else:
#         filtered_pdb_path = f"filtered-opm-vina-5A/unlabeled/{unlabeled_name}-f{fragment_index}-with-ligand.pdb"

#     os.makedirs(os.path.dirname(filtered_pdb_path), exist_ok=True)
#     filtered_pdb.to_pdb(
#         path=filtered_pdb_path,
#         records=["ATOM", "HETATM"],
#         gz=False,
#         append_newline=True
#     )

#     print(f"Saved: {filtered_pdb_path}")

In [28]:
import glob
from pathlib import Path

def pdb_id_from_file(path):
    """
    Extract PDB ID from file name.
    Works for names like:
    1abc.pdb
    1ABC.pdb
    1ABC_protein.pdb
    1abc_opm.pdb
    """
    stem = Path(path).stem
    stem = stem.replace("_protein", "")
    return stem[:4].lower()


# Ivan files are used only to get the PDB IDs
ivan_files = glob.glob("/home/alexhernandez/p2rank/ivanfiles/*.pdb")

ivan_pdb_ids = {
    pdb_id_from_file(f)
    for f in ivan_files
}

print("Number of Ivan PDB IDs:", len(ivan_pdb_ids))


# Now use OPM PDB files, but only if their PDB ID is in ivanfiles
opm_files = glob.glob("OPM_PDB/*.pdb")

positive_files = [
    f for f in opm_files
    if pdb_id_from_file(f) in ivan_pdb_ids
]

positive_files = sorted(positive_files, key=natural_sort_key)

print("Number of matching OPM PDB files:", len(positive_files))


# Optional: report Ivan IDs that do not have a matching OPM file
opm_pdb_ids = {
    pdb_id_from_file(f)
    for f in opm_files
}

missing_from_opm = sorted(ivan_pdb_ids - opm_pdb_ids)

print("Ivan PDB IDs missing from OPM_PDB:")
print(missing_from_opm)


# Run your normal positive logic, but now using matching OPM files
for positive in positive_files:
    positive_name = get_protein_name(positive)

    protein, all_lig_gridlist = get_positive_ligand_atoms(
        positive,
        positive_name
    )

Number of Ivan PDB IDs: 57
Number of matching OPM PDB files: 40
Ivan PDB IDs missing from OPM_PDB:
['8jd1', '8jd5', '8kdf', '8kdh', '8srh', '8srk', '8szg', '8szi', '8v81', '9axf', '9b36', '9b37', '9c3e', '9dmg', '9dmt', '9dxs', '9ii3']
{'G', 'B', 'A'}
OPM_PDB/4hqj.pdb
Total atoms within 5.0 Å cutoff: 55
Total atoms after residue expansion + filtering: 55
Saved: filtered-opm-ivan-5A/positive/4HQJ-filtered-with-ligand.pdb
{'G', 'B', 'A'}
OPM_PDB/4ret.pdb
Total atoms within 5.0 Å cutoff: 58
Total atoms after residue expansion + filtering: 47
Saved: filtered-opm-ivan-5A/positive/4RET-filtered-with-ligand.pdb
{'C', 'A'}
OPM_PDB/5oqt.pdb
Total atoms within 5.0 Å cutoff: 51
Total atoms after residue expansion + filtering: 66
Saved: filtered-opm-ivan-5A/positive/5OQT-filtered-with-ligand.pdb
{'C', 'B', 'D', 'A'}
OPM_PDB/5sy1.pdb
Total atoms within 5.0 Å cutoff: 34
Total atoms after residue expansion + filtering: 40
Saved: filtered-opm-ivan-5A/positive/5SY1-filtered-with-ligand.pdb
{'B', 'D', 'A'}
OPM_PDB/5wb2.pdb
Total atoms within 5.0 Å cutoff: 38
Total atoms after residue expansion + filtering: 38
Saved: filtered-opm-ivan-5A/positive/5WB2-filtered-with-ligand.pdb
{'A'}
OPM_PDB/6awn.pdb
Total atoms within 5.0 Å cutoff: 22
Total atoms after residue expansion + filtering: 22
Saved: filtered-opm-ivan-5A/positive/6AWN-filtered-with-ligand.pdb
{'A'}
OPM_PDB/6awo.pdb
Total atoms within 5.0 Å cutoff: 21
Total atoms after residue expansion + filtering: 27
Saved: filtered-opm-ivan-5A/positive/6AWO-filtered-with-ligand.pdb
{'A'}
OPM_PDB/6awq.pdb
Total atoms within 5.0 Å cutoff: 21
Total atoms after residue expansion + filtering: 27
Saved: filtered-opm-ivan-5A/positive/6AWQ-filtered-with-ligand.pdb
{'B', 'A'}
OPM_PDB/6jxk.pdb
Total atoms within 5.0 Å cutoff: 39
Total atoms after residue expansion + filtering: 29
Saved: filtered-opm-ivan-5A/positive/6JXK-filtered-with-ligand.pdb
{'B', 'A'}
OPM_PDB/6l47.pdb
Total atoms within 5.0 Å cutoff: 95
Total atoms after residue expansion + filtering: 110
Saved: filtered-opm-ivan-5A/positive/6L47-filtered-with-ligand.pdb
{'G', 'R', 'N', 'A', 'B', 'P'}
OPM_PDB/6nbh.pdb
Total atoms within 5.0 Å cutoff: 23
Total atoms after residue expansion + filtering: 14
Saved: filtered-opm-ivan-5A/positive/6NBH-filtered-with-ligand.pdb
{'C', 'B', 'A'}
OPM_PDB/6qex.pdb
Total atoms within 5.0 Å cutoff: 25
Total atoms after residue expansion + filtering: 12
Saved: filtered-opm-ivan-5A/positive/6QEX-filtered-with-ligand.pdb
{'G', 'E', 'D', 'A', 'C', 'H', 'F', 'B'}
OPM_PDB/6v35.pdb
Total atoms within 5.0 Å cutoff: 36
Total atoms after residue expansion + filtering: 38
Saved: filtered-opm-ivan-5A/positive/6V35-filtered-with-ligand.pdb
{'C', 'B', 'D', 'A'}
OPM_PDB/6vum.pdb
Total atoms within 5.0 Å cutoff: 19
Total atoms after residue expansion + filtering: 14
Saved: filtered-opm-ivan-5A/positive/6VUM-filtered-with-ligand.pdb
{'D', 'A'}
OPM_PDB/6w5v.pdb
Total atoms within 5.0 Å cutoff: 65
Total atoms after residue expansion + filtering: 54
Saved: filtered-opm-ivan-5A/positive/6W5V-filtered-with-ligand.pdb
{'C', 'B', 'A'}
OPM_PDB/7a6c.pdb
Total atoms within 5.0 Å cutoff: 22
Total atoms after residue expansion + filtering: 18
Saved: filtered-opm-ivan-5A/positive/7A6C-filtered-with-ligand.pdb
{'C', 'B', 'A'}
OPM_PDB/7a6e.pdb
Total atoms within 5.0 Å cutoff: 30
Total atoms after residue expansion + filtering: 26
Saved: filtered-opm-ivan-5A/positive/7A6E-filtered-with-ligand.pdb
{'C', 'B', 'A'}
OPM_PDB/7a6f.pdb
Total atoms within 5.0 Å cutoff: 24
Total atoms after residue expansion + filtering: 15
Saved: filtered-opm-ivan-5A/positive/7A6F-filtered-with-ligand.pdb
{'C', 'B', 'A'}
OPM_PDB/7a65.pdb
Total atoms within 5.0 Å cutoff: 30
Total atoms after residue expansion + filtering: 16
Saved: filtered-opm-ivan-5A/positive/7A65-filtered-with-ligand.pdb
{'B', 'A'}
OPM_PDB/7ca3.pdb
Total atoms within 5.0 Å cutoff: 20
Total atoms after residue expansion + filtering: 24
Saved: filtered-opm-ivan-5A/positive/7CA3-filtered-with-ligand.pdb
{'B', 'A'}
OPM_PDB/7cum.pdb
Total atoms within 5.0 Å cutoff: 30
Total atoms after residue expansion + filtering: 35
Saved: filtered-opm-ivan-5A/positive/7CUM-filtered-with-ligand.pdb
{'G', 'B', 'A'}
OPM_PDB/7d92.pdb
Total atoms within 5.0 Å cutoff: 36
Total atoms after residue expansion + filtering: 22
Saved: filtered-opm-ivan-5A/positive/7D92-filtered-with-ligand.pdb
{'G', 'B', 'A'}
OPM_PDB/7d93.pdb
Total atoms within 5.0 Å cutoff: 56
Total atoms after residue expansion + filtering: 47
Saved: filtered-opm-ivan-5A/positive/7D93-filtered-with-ligand.pdb
{'G', 'B', 'A'}
OPM_PDB/7d94.pdb
Total atoms within 5.0 Å cutoff: 55
Total atoms after residue expansion + filtering: 47
Saved: filtered-opm-ivan-5A/positive/7D94-filtered-with-ligand.pdb
{'G', 'B', 'A'}
OPM_PDB/7ddf.pdb
Total atoms within 5.0 Å cutoff: 31
Total atoms after residue expansion + filtering: 18
Saved: filtered-opm-ivan-5A/positive/7DDF-filtered-with-ligand.pdb
{'G', 'B', 'A'}
OPM_PDB/7ddi.pdb
Total atoms within 5.0 Å cutoff: 56
Total atoms after residue expansion + filtering: 47
Saved: filtered-opm-ivan-5A/positive/7DDI-filtered-with-ligand.pdb
{'G', 'B', 'A'}
OPM_PDB/7ddk.pdb
Total atoms within 5.0 Å cutoff: 30
Total atoms after residue expansion + filtering: 12
Saved: filtered-opm-ivan-5A/positive/7DDK-filtered-with-ligand.pdb
{'B', 'A'}
OPM_PDB/7ky5.pdb
Total atoms within 5.0 Å cutoff: 5
No residues passed the 50% occupancy filter. Falling back to residues with at least one atom within cutoff.
Total atoms after residue expansion + filtering: 30
Saved: filtered-opm-ivan-5A/positive/7KY5-filtered-with-ligand.pdb
{'B', 'A'}
OPM_PDB/7ky8.pdb
Total atoms within 5.0 Å cutoff: 52
Total atoms after residue expansion + filtering: 68
Saved: filtered-opm-ivan-5A/positive/7KY8-filtered-with-ligand.pdb
{'B', 'A'}
OPM_PDB/7kya.pdb
Total atoms within 5.0 Å cutoff: 18
Total atoms after residue expansion + filtering: 8
Saved: filtered-opm-ivan-5A/positive/7KYA-filtered-with-ligand.pdb
{'B', 'A'}
OPM_PDB/7n4v.pdb
Total atoms within 5.0 Å cutoff: 29
Total atoms after residue expansion + filtering: 15
Saved: filtered-opm-ivan-5A/positive/7N4V-filtered-with-ligand.pdb
{'C', 'B', 'A'}
OPM_PDB/7niw.pdb
Total atoms within 5.0 Å cutoff: 31
Total atoms after residue expansion + filtering: 27
Saved: filtered-opm-ivan-5A/positive/7NIW-filtered-with-ligand.pdb
{'B', 'A'}
OPM_PDB/7qtv.pdb
Total atoms within 5.0 Å cutoff: 46
Total atoms after residue expansion + filtering: 35
Saved: filtered-opm-ivan-5A/positive/7QTV-filtered-with-ligand.pdb
{'A'}
OPM_PDB/7rm5.pdb
Total atoms within 5.0 Å cutoff: 41
Total atoms after residue expansion + filtering: 42
Saved: filtered-opm-ivan-5A/positive/7RM5-filtered-with-ligand.pdb
{'B', 'A'}
OPM_PDB/7rr9.pdb
Total atoms within 5.0 Å cutoff: 34
Total atoms after residue expansion + filtering: 38
Saved: filtered-opm-ivan-5A/positive/7RR9-filtered-with-ligand.pdb
{'E', 'D', 'A', 'C', 'F', 'B'}
OPM_PDB/7sk3.pdb
Total atoms within 5.0 Å cutoff: 35
Total atoms after residue expansion + filtering: 35
Saved: filtered-opm-ivan-5A/positive/7SK3-filtered-with-ligand.pdb
{'G', 'B', 'A'}
OPM_PDB/7wys.pdb
Total atoms within 5.0 Å cutoff: 33
Total atoms after residue expansion + filtering: 24
Saved: filtered-opm-ivan-5A/positive/7WYS-filtered-with-ligand.pdb
{'G', 'B', 'A'}
OPM_PDB/7wyy.pdb
Total atoms within 5.0 Å cutoff: 32
Total atoms after residue expansion + filtering: 31
Saved: filtered-opm-ivan-5A/positive/7WYY-filtered-with-ligand.pdb
{'G', 'B', 'A'}
OPM_PDB/7y46.pdb
Total atoms within 5.0 Å cutoff: 33
Total atoms after residue expansion + filtering: 35
Saved: filtered-opm-ivan-5A/positive/7Y46-filtered-with-ligand.pdb
{'E', 'D', 'A', 'C', 'B'}
OPM_PDB/8dpg.pdb
Total atoms within 5.0 Å cutoff: 58
Total atoms after residue expansion + filtering: 69
Saved: filtered-opm-ivan-5A/positive/8DPG-filtered-with-ligand.pdb

In [29]:
import pickle
import os

PDB2PQR_PH = 7.4

cache_path = "pqr_cache.pkl"
FULL_PDB_DIR = "/home/alexhernandez/p2rank/ivanfiles"   # change this

if os.path.exists(cache_path):
    with open(cache_path, "rb") as f:
        data = pickle.load(f)
        pqr_cache = data["pqr_cache"]
        pqr_failures = data["pqr_failures"]

    print(f"Loaded PQR cache from {cache_path}")
    print(f"Cached PDBs: {len(pqr_cache)}")
else:
    print("Cache not found, rebuilding...")

Loaded PQR cache from pqr_cache.pkl
Cached PDBs: 763

In [30]:
print("num cached pdbs:", len(pqr_cache))
print("num failures:", len(pqr_failures))

example_key = next(iter(pqr_cache))
print("example pdb id:", example_key)

charges_full, charges_nochain, has_chain = pqr_cache[example_key]
print("has_chain:", has_chain)
print("num full charge entries:", len(charges_full))
print("num no-chain charge entries:", len(charges_nochain))

print("sample full keys:", list(charges_full.items())[:10])
print("sample no-chain keys:", list(charges_nochain.items())[:10])

num cached pdbs: 763
num failures: 7
example pdb id: 1LRI
has_chain: False
num full charge entries: 1432
num no-chain charge entries: 1432
sample full keys: [(('', 1, 'N'), 0.1812), (('', 1, 'CA'), 0.0034), (('', 1, 'C'), 0.6163), (('', 1, 'O'), -0.5722), (('', 1, 'CB'), 0.4514), (('', 1, 'OG1'), -0.6764), (('', 1, 'CG2'), -0.2554), (('', 1, 'H'), 0.1934), (('', 1, 'HA'), 0.1087), (('', 1, 'HB'), -0.0323)]
sample no-chain keys: [((1, 'N'), 0.1812), ((1, 'CA'), 0.0034), ((1, 'C'), 0.6163), ((1, 'O'), -0.5722), ((1, 'CB'), 0.4514), ((1, 'OG1'), -0.6764), ((1, 'CG2'), -0.2554), ((1, 'H'), 0.1934), ((1, 'HA'), 0.1087), ((1, 'HB'), -0.0323)]

In [31]:
import numpy as np

RDKIT_FEATURE_NAMES = [
    "atom_C",
    "atom_N",
    "atom_O",
    "atom_S",

    "degree_norm",

    "hybridization_SP",
    "hybridization_SP2",
    "hybridization_SP3",

    "partial_charge",

    "is_in_ring",
    "is_aromatic",

    "residue_acidic_ASP_GLU",
    "residue_basic_LYS_ARG",
    "residue_HIS",
    "residue_CYS",
    "residue_polar_ASN_GLN_SER_THR",
    "residue_GLY",
    "residue_PRO",
    "residue_aromatic_PHE_TYR_TRP",
    "residue_hydrophobic_ALA_ILE_LEU_MET_VAL",

    "z_depth"
]

LIGAND_RESNAMES = {"CLR", "CHL", "UNL"}


def compute_z_depth_from_coords(coords):
    """
    Normalized absolute z-depth from membrane center z=0.
    Works for protein and ligand atoms.
    """
    z = np.abs(coords[:, 2].astype(float))
    max_z = z.max()

    if max_z == 0:
        return np.zeros((len(z), 1), dtype=np.float32)

    return (z / max_z).reshape(-1, 1).astype(np.float32)


def rdkit_features_no_atom_subtypes(
    pdb_path,
    pqr_cache=None,
    charge_min=-1.003100,
    charge_max=0.885100,
    normalize_charge=True,
    ligand_feature_mode="full",
    return_atom_info=False
):
    """
    Builds RDKit-style features without atom subtype one-hot columns.

    ligand_feature_mode:
        "none"   -> ligand feature rows are all zero, but ligand atoms remain in distance matrix
        "z_only" -> ligand rows only keep z-depth
    """
    mol = Chem.MolFromPDBFile(
        str(pdb_path),
        removeHs=False,
        sanitize=False
    )

    if mol is None:
        print(f"[SKIP] RDKit could not parse: {pdb_path}")
        return None, None, None, None, None

    try:
        Chem.SanitizeMol(mol)
    except Exception:
        print(f"[WARN] RDKit sanitize warning for: {pdb_path}")

    conf = mol.GetConformer()

    heavy_atoms = [
        atom for atom in mol.GetAtoms()
        if atom.GetAtomicNum() != 1
    ]

    n_atoms = len(heavy_atoms)
    n_features = len(RDKIT_FEATURE_NAMES)

    coords = np.zeros((n_atoms, 3), dtype=np.float32)
    features = np.zeros((n_atoms, n_features), dtype=np.float32)

    protein_mask = np.zeros(n_atoms, dtype=bool)
    ligand_mask = np.zeros(n_atoms, dtype=bool)

    atom_info_rows = []

    base_name = os.path.basename(str(pdb_path))
    match = re.match(r"([A-Za-z0-9]{4})", base_name)
    pdb_id = match.group(1).upper() if match else None

    charges_full, charges_nochain, has_chain = ({}, {}, False)
    if pqr_cache is not None and pdb_id in pqr_cache:
        charges_full, charges_nochain, has_chain = pqr_cache[pdb_id]

    for i, atom in enumerate(heavy_atoms):
        pos = conf.GetAtomPosition(atom.GetIdx())
        coords[i] = [pos.x, pos.y, pos.z]

        pdb_info = atom.GetPDBResidueInfo()

        if pdb_info is not None:
            residue = pdb_info.GetResidueName().strip()
            atomname = pdb_info.GetName().strip()
            chain = (pdb_info.GetChainId() or "").strip()
            resseq = int(pdb_info.GetResidueNumber())
        else:
            residue = ""
            atomname = atom.GetSymbol()
            chain = ""
            resseq = -9999

        is_ligand = residue in LIGAND_RESNAMES
        ligand_mask[i] = is_ligand
        protein_mask[i] = not is_ligand

        idx = {name: k for k, name in enumerate(RDKIT_FEATURE_NAMES)}

        atom_symbol = atom.GetSymbol().upper()

        if atom_symbol == "C":
            features[i, idx["atom_C"]] = 1.0
        elif atom_symbol == "N":
            features[i, idx["atom_N"]] = 1.0
        elif atom_symbol == "O":
            features[i, idx["atom_O"]] = 1.0
        elif atom_symbol == "S":
            features[i, idx["atom_S"]] = 1.0
        features[i, idx["degree_norm"]] = atom.GetDegree() / 6.0

        hybridization = atom.GetHybridization()
        if hybridization == Chem.HybridizationType.SP:
            features[i, idx["hybridization_SP"]] = 1.0
        elif hybridization == Chem.HybridizationType.SP2:
            features[i, idx["hybridization_SP2"]] = 1.0
        elif hybridization == Chem.HybridizationType.SP3:
            features[i, idx["hybridization_SP3"]] = 1.0

        partial_charge = lookup_charge(
            chain,
            resseq,
            atomname,
            charges_full,
            charges_nochain,
            has_chain
        )

        if normalize_charge:
            if charge_max == charge_min:
                partial_charge = 0.0
            else:
                partial_charge = (partial_charge - charge_min) / (charge_max - charge_min)
                partial_charge = np.clip(partial_charge, 0.0, 1.0)

        features[i, idx["partial_charge"]] = float(partial_charge)

        features[i, idx["is_in_ring"]] = 1.0 if atom.IsInRing() else 0.0
        features[i, idx["is_aromatic"]] = 1.0 if atom.GetIsAromatic() else 0.0

        if residue in {"ASP", "GLU"}:
            features[i, idx["residue_acidic_ASP_GLU"]] = 1.0
        elif residue in {"LYS", "ARG"}:
            features[i, idx["residue_basic_LYS_ARG"]] = 1.0
        elif residue == "HIS":
            features[i, idx["residue_HIS"]] = 1.0
        elif residue == "CYS":
            features[i, idx["residue_CYS"]] = 1.0
        elif residue in {"ASN", "GLN", "SER", "THR"}:
            features[i, idx["residue_polar_ASN_GLN_SER_THR"]] = 1.0
        elif residue == "GLY":
            features[i, idx["residue_GLY"]] = 1.0
        elif residue == "PRO":
            features[i, idx["residue_PRO"]] = 1.0
        elif residue in {"PHE", "TYR", "TRP"}:
            features[i, idx["residue_aromatic_PHE_TYR_TRP"]] = 1.0
        elif residue in {"ALA", "ILE", "LEU", "MET", "VAL"}:
            features[i, idx["residue_hydrophobic_ALA_ILE_LEU_MET_VAL"]] = 1.0
        
        atom_info_rows.append({
            "row_index": i,
            "atom_name": atomname,
            "atom_symbol": atom_symbol,
            "residue_name": residue,
            "residue_number": resseq,
            "chain_id": chain,
            "is_protein": bool(protein_mask[i]),
            "is_ligand": bool(ligand_mask[i]),
            "x": coords[i, 0],
            "y": coords[i, 1],
            "z": coords[i, 2],
        })

    z_depth = compute_z_depth_from_coords(coords)
    z_idx = RDKIT_FEATURE_NAMES.index("z_depth")
    features[:, z_idx] = z_depth[:, 0]

    if ligand_feature_mode == "none":
        features[ligand_mask, :] = 0.0

    elif ligand_feature_mode == "z_only":
        ligand_z = features[ligand_mask, z_idx].copy()
        features[ligand_mask, :] = 0.0
        features[ligand_mask, z_idx] = ligand_z

    elif ligand_feature_mode == "full":
        # Keep all RDKit-derived ligand features.
        pass

    else:
        raise ValueError("ligand_feature_mode must be 'none' or 'z_only'")

    if return_atom_info:
        atom_info_df = pd.DataFrame(atom_info_rows)
        return coords, features, protein_mask, ligand_mask, z_depth, atom_info_df

    return coords, features, protein_mask, ligand_mask, z_depth

def compute_weighted_inverse_distance(
    coords,
    protein_mask,
    ligand_mask,
    pp_weight=2.0,
    pl_weight=1.0,
    ll_weight=0.5,
    row_normalize=True
):
    """
    Builds inverse-distance matrix with edge-type weights.

    pp_weight: protein-protein edge importance
    pl_weight: protein-ligand edge importance
    ll_weight: ligand-ligand edge importance
    """
    diff = coords[:, np.newaxis, :] - coords[np.newaxis, :, :]
    distances = np.sqrt(np.sum(diff ** 2, axis=-1))

    with np.errstate(divide="ignore"):
        inv = 1.0 / distances

    np.fill_diagonal(inv, 1.0)
    inv = np.minimum(inv, 1.0)

    weights = np.ones_like(inv, dtype=np.float32) * pl_weight

    pp_edges = np.outer(protein_mask, protein_mask)
    ll_edges = np.outer(ligand_mask, ligand_mask)

    weights[pp_edges] = pp_weight
    weights[ll_edges] = ll_weight

    weighted_inv = inv * weights

    np.fill_diagonal(weighted_inv, 1.0)

    if row_normalize:
        row_sums = weighted_inv.sum(axis=1, keepdims=True)
        row_sums[row_sums == 0] = 1.0
        weighted_inv = weighted_inv / row_sums

    return weighted_inv.astype(np.float32)

def pdb_to_dataframe(pdb_file):
    """
    Load a PDB file using MDAnalysis and convert key atom information to a pandas DataFrame.
    """
    u = mda.Universe(pdb_file)
    
    # Extract atom-related data: atom name, residue name, residue ID, and chain ID
    atom_data = {
        'Atom Name': u.atoms.names,
        'Residue Name': u.atoms.resnames,
        'Residue ID': u.atoms.resids,
        'Chain ID': u.atoms.segids,
        'X': u.atoms.positions[:, 0],
        'Y': u.atoms.positions[:, 1],
        'Z': u.atoms.positions[:, 2],
    }
    
    # Create a pandas DataFrame from the atom data
    df = pd.DataFrame(atom_data)
    
    return df

def min_max_normalization(matrix):
    """
    Perform Min-Max normalization on a given matrix.

    Parameters:
    matrix (np.ndarray): The input matrix to be normalized.

    Returns:
    np.ndarray: The normalized matrix with values scaled to the range [0, 1].
    """
    # Compute the minimum and maximum values for the matrix
    min_val = np.min(matrix)
    max_val = np.max(matrix)

    # Apply Min-Max normalization formula
    normalized_matrix = (matrix - min_val) / (max_val - min_val)

    return normalized_matrix

In [32]:
max_atoms = 200
output_dir = "cholesterol-rdkit-ivan-ligandgraph-5A/positive"
os.makedirs(output_dir, exist_ok=True)

positive_files = glob.glob("filtered-opm-ivan-5A/positive/*with-ligand.pdb")
positive_files = sorted(positive_files, key=natural_sort_key)

for file in positive_files:
    coords, encoded_matrix, protein_mask, ligand_mask, z_depth = rdkit_features_no_atom_subtypes(
        file,
        pqr_cache=pqr_cache,
        charge_min=-1.003100,
        charge_max=0.885100,
        normalize_charge=True,
        ligand_feature_mode="full"
    )

    if coords is None or encoded_matrix is None:
        print(f"[SKIP] Failed encoding for {file}")
        continue

    weighted_inverse_distance = compute_weighted_inverse_distance(
        coords,
        protein_mask=protein_mask,
        ligand_mask=ligand_mask,
        pp_weight=2.0,
        pl_weight=1.0,
        ll_weight=0.5,
        row_normalize=True
    )

    if weighted_inverse_distance.shape[0] != encoded_matrix.shape[0]:
        raise ValueError(
            f"Atom mismatch in {file}: "
            f"weighted_inverse_distance={weighted_inverse_distance.shape}, "
            f"encoded_matrix={encoded_matrix.shape}"
        )

    combined_matrix = weighted_inverse_distance @ encoded_matrix
    combined_matrix = combined_matrix * z_depth

    num_atoms = combined_matrix.shape[0]

    if num_atoms > max_atoms:
        print(f"[SKIP] {file} has {num_atoms} atoms, exceeding max_atoms={max_atoms}")
        continue

    combined_matrix_padded = np.pad(
        combined_matrix,
        ((0, max_atoms - num_atoms), (0, 0)),
        mode="constant"
    )

    protein_mask_padded = np.pad(
        protein_mask.astype(np.int8),
        (0, max_atoms - num_atoms),
        mode="constant"
    )

    ligand_mask_padded = np.pad(
        ligand_mask.astype(np.int8),
        (0, max_atoms - num_atoms),
        mode="constant"
    )

    z_depth_padded = np.pad(
        z_depth,
        ((0, max_atoms - num_atoms), (0, 0)),
        mode="constant"
    )

    base_name = os.path.splitext(os.path.basename(file))[0]

    matrix_path = os.path.join(output_dir, f"{base_name}_combined_matrix.npy")
    meta_path = os.path.join(output_dir, f"{base_name}_metadata.npz")

    np.save(matrix_path, combined_matrix_padded)

    np.savez(
        meta_path,
        protein_mask=protein_mask_padded,
        ligand_mask=ligand_mask_padded,
        z_depth=z_depth_padded,
        feature_names=np.array(RDKIT_FEATURE_NAMES),
        pp_weight=np.array([2.0]),
        pl_weight=np.array([1.0]),
        ll_weight=np.array([0.5])
    )

    print(f"Saved matrix: {matrix_path}")
    print(f"Saved metadata: {meta_path}")

Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/4HQJ-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/4HQJ-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/4RET-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/4RET-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/5OQT-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/5OQT-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/5SY1-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/5SY1-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/5WB2-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/5WB2-filtered-with-ligand_metadata.npz
[SKIP] RDKit could not parse: filtered-opm-ivan-5A/positive/6AWN-filtered-with-ligand.pdb
[SKIP] Failed encoding for filtered-opm-ivan-5A/positive/6AWN-filtered-with-ligand.pdb
[SKIP] RDKit could not parse: filtered-opm-ivan-5A/positive/6AWO-filtered-with-ligand.pdb
[SKIP] Failed encoding for filtered-opm-ivan-5A/positive/6AWO-filtered-with-ligand.pdb
[SKIP] RDKit could not parse: filtered-opm-ivan-5A/positive/6AWQ-filtered-with-ligand.pdb
[SKIP] Failed encoding for filtered-opm-ivan-5A/positive/6AWQ-filtered-with-ligand.pdb
[SKIP] RDKit could not parse: filtered-opm-ivan-5A/positive/6JXK-filtered-with-ligand.pdb
[SKIP] Failed encoding for filtered-opm-ivan-5A/positive/6JXK-filtered-with-ligand.pdb
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/6L47-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/6L47-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/6NBH-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/6NBH-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/6QEX-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/6QEX-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/6V35-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/6V35-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/6VUM-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/6VUM-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/6W5V-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/6W5V-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7A6C-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7A6C-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7A6E-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7A6E-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7A6F-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7A6F-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7A65-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7A65-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7CA3-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7CA3-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7CUM-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7CUM-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7D92-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7D92-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7D93-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7D93-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7D94-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7D94-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7DDF-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7DDF-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7DDI-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7DDI-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7DDK-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7DDK-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7KY5-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7KY5-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7KY8-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7KY8-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7KYA-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7KYA-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7N4V-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7N4V-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7NIW-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7NIW-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7QTV-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7QTV-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7RM5-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7RM5-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7RR9-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7RR9-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7SK3-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7SK3-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7WYS-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7WYS-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7WYY-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7WYY-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7Y46-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/7Y46-filtered-with-ligand_metadata.npz
Saved matrix: cholesterol-rdkit-ivan-ligandgraph-5A/positive/8DPG-filtered-with-ligand_combined_matrix.npy
Saved metadata: cholesterol-rdkit-ivan-ligandgraph-5A/positive/8DPG-filtered-with-ligand_metadata.npz

[10:04:33]

****
Post-condition Violation
Element 'Cb' not found
Violation occurred on line 93 in file /project/build/temp.linux-x86_64-cpython-312/rdkit/Code/GraphMol/PeriodicTable.h
Failed Expression: anum > -1
----------
Stacktrace:
----------
****

[10:04:33]

****
Post-condition Violation
Element 'Cb' not found
Violation occurred on line 93 in file /project/build/temp.linux-x86_64-cpython-312/rdkit/Code/GraphMol/PeriodicTable.h
Failed Expression: anum > -1
----------
Stacktrace:
----------
****

[10:04:33]

****
Post-condition Violation
Element 'Cb' not found
Violation occurred on line 93 in file /project/build/temp.linux-x86_64-cpython-312/rdkit/Code/GraphMol/PeriodicTable.h
Failed Expression: anum > -1
----------
Stacktrace:
----------
****

[10:04:33]

****
Post-condition Violation
Element 'Cb' not found
Violation occurred on line 93 in file /project/build/temp.linux-x86_64-cpython-312/rdkit/Code/GraphMol/PeriodicTable.h
Failed Expression: anum > -1
----------
Stacktrace:
----------
****

In [33]:
# max_atoms = 200
# output_dir = "cholesterol-rdkit-opm-ligandgraph-5A/unlabeled"
# os.makedirs(output_dir, exist_ok=True)

# unlabeled_files = glob.glob("filtered-opm-vina-5A/unlabeled/*with-ligand.pdb")
# unlabeled_files = sorted(unlabeled_files, key=natural_sort_key)

# for file in unlabeled_files:
#     coords, encoded_matrix, protein_mask, ligand_mask, z_depth = rdkit_features_no_atom_subtypes(
#         file,
#         pqr_cache=pqr_cache,
#         charge_min=-1.003100,
#         charge_max=0.885100,
#         normalize_charge=True,
#         ligand_feature_mode="full"
#     )

#     if coords is None or encoded_matrix is None:
#         print(f"[SKIP] Failed encoding for {file}")
#         continue

#     weighted_inverse_distance = compute_weighted_inverse_distance(
#         coords,
#         protein_mask=protein_mask,
#         ligand_mask=ligand_mask,
#         pp_weight=2.0,
#         pl_weight=1.0,
#         ll_weight=0.5,
#         row_normalize=True
#     )

#     if weighted_inverse_distance.shape[0] != encoded_matrix.shape[0]:
#         raise ValueError(
#             f"Atom mismatch in {file}: "
#             f"weighted_inverse_distance={weighted_inverse_distance.shape}, "
#             f"encoded_matrix={encoded_matrix.shape}"
#         )

#     combined_matrix = weighted_inverse_distance @ encoded_matrix
#     combined_matrix = combined_matrix * z_depth

#     num_atoms = combined_matrix.shape[0]

#     if num_atoms > max_atoms:
#         print(f"[SKIP] {file} has {num_atoms} atoms, exceeding max_atoms={max_atoms}")
#         continue

#     combined_matrix_padded = np.pad(
#         combined_matrix,
#         ((0, max_atoms - num_atoms), (0, 0)),
#         mode="constant"
#     )

#     protein_mask_padded = np.pad(
#         protein_mask.astype(np.int8),
#         (0, max_atoms - num_atoms),
#         mode="constant"
#     )

#     ligand_mask_padded = np.pad(
#         ligand_mask.astype(np.int8),
#         (0, max_atoms - num_atoms),
#         mode="constant"
#     )

#     z_depth_padded = np.pad(
#         z_depth,
#         ((0, max_atoms - num_atoms), (0, 0)),
#         mode="constant"
#     )

#     base_name = os.path.splitext(os.path.basename(file))[0]

#     matrix_path = os.path.join(output_dir, f"{base_name}_combined_matrix.npy")
#     meta_path = os.path.join(output_dir, f"{base_name}_metadata.npz")

#     np.save(matrix_path, combined_matrix_padded)

#     np.savez(
#         meta_path,
#         protein_mask=protein_mask_padded,
#         ligand_mask=ligand_mask_padded,
#         z_depth=z_depth_padded,
#         feature_names=np.array(RDKIT_FEATURE_NAMES),
#         pp_weight=np.array([2.0]),
#         pl_weight=np.array([1.0]),
#         ll_weight=np.array([0.5])
#     )

#     print(f"Saved matrix: {matrix_path}")
#     print(f"Saved metadata: {meta_path}")

In [34]:
def inspect_preprocessed_sample(
    pdb_path,
    combined_matrix_path,
    metadata_path,
    pqr_cache=None
):
    """
    Inspect one filtered PDB and its preprocessed matrix/metadata.

    Important:
    - encoded_matrix = raw atom features before graph aggregation
    - combined_matrix = weighted_inverse_distance @ encoded_matrix
    """

    pdb_path = str(pdb_path)
    combined_matrix_path = str(combined_matrix_path)
    metadata_path = str(metadata_path)

    combined_matrix = np.load(combined_matrix_path)
    metadata = np.load(metadata_path, allow_pickle=True)

    saved_protein_mask = metadata["protein_mask"].astype(bool)
    saved_ligand_mask = metadata["ligand_mask"].astype(bool)
    saved_feature_names = metadata["feature_names"]

    coords, encoded_matrix, protein_mask, ligand_mask, z_depth, atom_info_df = rdkit_features_no_atom_subtypes(
        pdb_path,
        pqr_cache=pqr_cache,
        charge_min=-1.003100,
        charge_max=0.885100,
        normalize_charge=True,
        ligand_feature_mode="full",
        return_atom_info=True
    )

    if coords is None:
        print("Could not encode PDB.")
        return None, None, None

    num_real_atoms = len(encoded_matrix)

    print("========== SHAPES ==========")
    print("Raw encoded_matrix shape:", encoded_matrix.shape)
    print("Saved combined_matrix shape:", combined_matrix.shape)
    print("Number of real atoms from PDB:", num_real_atoms)
    print("Number of saved protein atoms:", saved_protein_mask.sum())
    print("Number of saved ligand atoms:", saved_ligand_mask.sum())
    print("Number of saved padding rows:", len(saved_protein_mask) - saved_protein_mask.sum() - saved_ligand_mask.sum())

    print("\n========== FEATURE NAMES ==========")
    for i, name in enumerate(saved_feature_names):
        print(f"{i}: {name}")

    raw_feature_df = pd.DataFrame(
        encoded_matrix,
        columns=RDKIT_FEATURE_NAMES
    )

    combined_real_df = pd.DataFrame(
        combined_matrix[:num_real_atoms],
        columns=saved_feature_names
    )

    atom_raw_df = pd.concat(
        [atom_info_df.reset_index(drop=True), raw_feature_df.reset_index(drop=True)],
        axis=1
    )

    atom_combined_df = pd.concat(
        [atom_info_df.reset_index(drop=True), combined_real_df.reset_index(drop=True)],
        axis=1
    )

    protein_raw = atom_raw_df[atom_raw_df["is_protein"]].copy()
    ligand_raw = atom_raw_df[atom_raw_df["is_ligand"]].copy()

    protein_combined = atom_combined_df[atom_combined_df["is_protein"]].copy()
    ligand_combined = atom_combined_df[atom_combined_df["is_ligand"]].copy()

    with pd.option_context(
        "display.max_rows", None,
        "display.max_columns", None,
        "display.width", None,
        "display.max_colwidth", None,
        "display.float_format", "{:.6f}".format
    ):
        print("\n========== RAW PROTEIN FEATURES ==========")
        display(protein_raw)

        print("\n========== RAW LIGAND FEATURES ==========")
        display(ligand_raw)

        print("\n========== COMBINED PROTEIN FEATURES ==========")
        display(protein_combined)

        print("\n========== COMBINED LIGAND FEATURES ==========")
        display(ligand_combined)

    return atom_raw_df, atom_combined_df, metadata

pdb_path = "/home/alexhernandez/CholBindNet/OPM_GNN/Ligand_and_Protein/filtered-opm-vina-5A/unlabeled/1ZHY-f1-with-ligand.pdb"

combined_matrix_path = "/home/alexhernandez/CholBindNet/OPM_GNN/Ligand_and_Protein/cholesterol-rdkit-opm-ligandgraph-5A/unlabeled/1ZHY-f1-with-ligand_combined_matrix.npy"

metadata_path = "/home/alexhernandez/CholBindNet/OPM_GNN/Ligand_and_Protein/cholesterol-rdkit-opm-ligandgraph-5A/positive/1ZHY-filtered-with-ligand_metadata.npz"

atom_raw_df, atom_combined_df, metadata = inspect_preprocessed_sample(
    pdb_path=pdb_path,
    combined_matrix_path=combined_matrix_path,
    metadata_path=metadata_path,
    pqr_cache=pqr_cache,
)

========== SHAPES ==========
Raw encoded_matrix shape: (94, 21)
Saved combined_matrix shape: (200, 21)
Number of real atoms from PDB: 94
Number of saved protein atoms: 49
Number of saved ligand atoms: 28
Number of saved padding rows: 123

========== FEATURE NAMES ==========
0: atom_C
1: atom_N
2: atom_O
3: atom_S
4: degree_norm
5: hybridization_SP
6: hybridization_SP2
7: hybridization_SP3
8: partial_charge
9: is_in_ring
10: is_aromatic
11: residue_acidic_ASP_GLU
12: residue_basic_LYS_ARG
13: residue_HIS
14: residue_CYS
15: residue_polar_ASN_GLN_SER_THR
16: residue_GLY
17: residue_PRO
18: residue_aromatic_PHE_TYR_TRP
19: residue_hydrophobic_ALA_ILE_LEU_MET_VAL
20: z_depth

========== RAW PROTEIN FEATURES ==========

,row_index,atom_name,atom_symbol,residue_name,residue_number,chain_id,is_protein,is_ligand,x,y,z,atom_C,atom_N,atom_O,atom_S,degree_norm,hybridization_SP,hybridization_SP2,hybridization_SP3,partial_charge,is_in_ring,is_aromatic,residue_acidic_ASP_GLU,residue_basic_LYS_ARG,residue_HIS,residue_CYS,residue_polar_ASN_GLN_SER_THR,residue_GLY,residue_PRO,residue_aromatic_PHE_TYR_TRP,residue_hydrophobic_ALA_ILE_LEU_MET_VAL,z_depth
0,0,N,N,GLU,232,A,True,False,11.021000,-0.981000,-28.156000,0.000000,1.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.257812,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.599625
1,1,CA,C,GLU,232,A,True,False,10.181000,-1.055000,-26.957001,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.552272,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.574091
2,2,C,C,GLU,232,A,True,False,9.519000,0.293000,-26.688000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.815433,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.568362
3,3,O,O,GLU,232,A,True,False,10.198000,1.315000,-26.628000,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,1.000000,0.000000,0.223070,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.567084
4,4,CB,C,GLU,232,A,True,False,11.026000,-1.425000,-25.733000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.560905,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.548024
5,5,CG,C,GLU,232,A,True,False,11.713000,-2.771000,-25.815001,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.538449,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.549770
6,6,CD,C,GLU,232,A,True,False,12.585000,-3.039000,-24.601999,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,1.000000,0.000000,0.957790,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.523937
7,7,OE1,O,GLU,232,A,True,False,13.606000,-2.340000,-24.434000,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,1.000000,0.000000,0.097606,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.520359
8,8,OE2,O,GLU,232,A,True,False,12.244000,-3.945000,-23.812000,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,1.000000,0.000000,0.097606,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.507113
9,9,N,N,SER,234,A,True,False,7.196000,2.903000,-24.253000,0.000000,1.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.311090,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.516505
10,10,CA,C,SER,234,A,True,False,6.830000,3.206000,-22.868000,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.518060,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.487009
11,11,C,C,SER,234,A,True,False,6.269000,4.630000,-22.822001,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.847580,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.486029
12,12,O,O,SER,234,A,True,False,5.962000,5.214000,-23.861000,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,1.000000,0.000000,0.230484,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.508157
13,13,CB,C,SER,234,A,True,False,8.057000,3.088000,-21.952999,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.643364,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.467523
14,14,OG,O,SER,234,A,True,False,7.690000,3.131000,-20.580000,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.184567,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.438283
15,15,N,N,PHE,239,A,True,False,6.718000,2.515000,-17.246000,0.000000,1.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.311090,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.367280
16,16,CA,C,PHE,239,A,True,False,8.093000,2.540000,-16.761999,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.529976,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.356972
17,17,C,C,PHE,239,A,True,False,8.884000,3.839000,-16.931999,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,1.000000,0.000000,0.847580,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.360593
18,18,O,O,PHE,239,A,True,False,9.455000,4.345000,-15.968000,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,1.000000,0.000000,0.230484,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.340063
19,19,CB,C,PHE,239,A,True,False,8.884000,1.390000,-17.382000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.513081,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.370176
20,20,CG,C,PHE,239,A,True,False,9.983000,0.876000,-16.499001,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,1.000000,0.000000,0.537496,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.351371
21,21,CD1,C,PHE,239,A,True,False,9.684000,0.125000,-15.369000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.464728,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.327306
22,22,CD2,C,PHE,239,A,True,False,11.314000,1.164000,-16.778999,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.464728,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.357334
23,23,CE1,C,PHE,239,A,True,False,10.696000,-0.334000,-14.528000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.441002,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.309396
24,24,CE2,C,PHE,239,A,True,False,12.329000,0.710000,-15.945000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.441002,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.339573
25,25,CZ,C,PHE,239,A,True,False,12.017000,-0.040000,-14.817000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.474473,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.315551
26,26,N,N,SER,240,A,True,False,8.927000,4.374000,-18.146000,0.000000,1.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.311090,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.386447
27,27,CA,C,SER,240,A,True,False,9.685000,5.594000,-18.407000,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.518060,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.392005
28,28,C,C,SER,240,A,True,False,9.088000,6.854000,-17.790001,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.847580,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.378865
29,29,O,O,SER,240,A,True,False,9.793000,7.632000,-17.143999,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,1.000000,0.000000,0.230484,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.365108
30,30,CB,C,SER,240,A,True,False,9.840000,5.800000,-19.917000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.643364,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.424163
31,31,OG,O,SER,240,A,True,False,10.584000,6.973000,-20.194000,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.184567,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.430062
32,32,N,N,LYS,242,A,True,False,7.860000,9.130000,-19.594000,0.000000,1.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.346997,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.417284
33,33,CA,C,LYS,242,A,True,False,8.050000,10.134000,-20.636999,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.404142,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.439497
34,34,C,C,LYS,242,A,True,False,7.104000,9.866000,-21.819000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.920030,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.464669
35,35,O,O,LYS,242,A,True,False,7.161000,8.808000,-22.434999,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,1.000000,0.000000,0.219098,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.477788
36,36,CB,C,LYS,242,A,True,False,9.501000,10.098000,-21.115999,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.526268,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.449698
37,37,CG,C,LYS,242,A,True,False,10.510000,9.937000,-19.981001,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.541150,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.425526
38,38,CD,C,LYS,242,A,True,False,10.489000,11.129000,-19.027000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.505879,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.405209
39,39,CE,C,LYS,242,A,True,False,11.415000,10.925000,-17.823999,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.523673,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.379589
40,40,NZ,N,LYS,242,A,True,False,10.811000,10.050000,-16.773001,0.000000,1.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.327137,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.357207
41,41,N,N,SER,245,A,True,False,7.596000,7.635000,-25.440001,0.000000,1.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.311090,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.541784
42,42,CA,C,SER,245,A,True,False,8.999000,7.249000,-25.424000,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.518060,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.541443
43,43,C,C,SER,245,A,True,False,9.220000,5.872000,-26.028999,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.847580,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.554327
44,44,O,O,SER,245,A,True,False,8.305000,5.051000,-26.114000,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,1.000000,0.000000,0.230484,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.556138
45,45,CB,C,SER,245,A,True,False,9.549000,7.273000,-23.992001,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.643364,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.510946
46,46,OG,O,SER,245,A,True,False,9.053000,6.196000,-23.211000,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.184567,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.494314
47,47,N,N,LYS,247,A,True,False,12.707000,2.898000,-27.024000,0.000000,1.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.346997,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.575517
48,48,CA,C,LYS,247,A,True,False,14.106000,2.533000,-26.990000,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.404142,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.574793
49,49,C,C,LYS,247,A,True,False,14.209000,1.422000,-28.017000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.920030,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.596665
50,50,O,O,LYS,247,A,True,False,13.467000,0.440000,-27.955000,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,1.000000,0.000000,0.219098,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.595345
51,51,CB,C,LYS,247,A,True,False,14.511000,2.029000,-25.603001,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.526268,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.545255
52,52,CG,C,LYS,247,A,True,False,15.982000,2.251000,-25.296000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.541150,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.538717
53,53,CD,C,LYS,247,A,True,False,16.274000,2.091000,-23.813999,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.505879,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.507156
54,54,CE,C,LYS,247,A,True,False,17.686001,2.554000,-23.478001,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.523673,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000
55,55,NZ,N,LYS,247,A,True,False,17.969000,2.454000,-22.018999,0.000000,1.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.327137,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.468928
56,56,N,N,SER,268,A,True,False,17.091000,6.059000,-28.403999,0.000000,1.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.311090,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.604907
57,57,CA,C,SER,268,A,True,False,16.101000,6.390000,-27.388000,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.518060,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.583269
58,58,C,C,SER,268,A,True,False,15.584000,7.811000,-27.525000,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,1.000000,0.000000,0.847580,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.586187
59,59,O,O,SER,268,A,True,False,16.313999,8.717000,-27.931999,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,1.000000,0.000000,0.230484,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.594855
60,60,CB,C,SER,268,A,True,False,16.687000,6.191000,-25.987000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.643364,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.553433
61,61,OG,O,SER,268,A,True,False,17.787001,7.054000,-25.767000,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.184567,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.548748
62,62,N,N,GLY,269,A,True,False,14.316000,7.997000,-27.179001,0.000000,1.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.311090,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.578819
63,63,CA,C,GLY,269,A,True,False,13.709000,9.309000,-27.264000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.517901,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.580629
64,64,C,C,GLY,269,A,True,False,12.207000,9.210000,-27.445999,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,1.000000,0.000000,0.847580,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.584505
65,65,O,O,GLY,269,A,True,False,11.586000,8.239000,-27.018999,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,1.000000,0.000000,0.230484,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.575411

========== RAW LIGAND FEATURES ==========

,row_index,atom_name,atom_symbol,residue_name,residue_number,chain_id,is_protein,is_ligand,x,y,z,atom_C,atom_N,atom_O,atom_S,degree_norm,hybridization_SP,hybridization_SP2,hybridization_SP3,partial_charge,is_in_ring,is_aromatic,residue_acidic_ASP_GLU,residue_basic_LYS_ARG,residue_HIS,residue_CYS,residue_polar_ASN_GLN_SER_THR,residue_GLY,residue_PRO,residue_aromatic_PHE_TYR_TRP,residue_hydrophobic_ALA_ILE_LEU_MET_VAL,z_depth
66,66,C1,C,UNL,1,,False,True,23.747999,-2.967000,-33.507000,1.000000,0.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.531247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.713583
67,67,C2,C,UNL,1,,False,True,22.431000,-2.196000,-33.411999,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.531247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.711560
68,68,C3,C,UNL,1,,False,True,21.365000,-3.077000,-32.757999,1.000000,0.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.531247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.697632
69,69,C4,C,UNL,1,,False,True,21.931999,-1.706000,-34.785999,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.531247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.740821
70,70,C5,C,UNL,1,,False,True,20.510000,-2.171000,-35.117001,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.531247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.747870
71,71,C6,C,UNL,1,,False,True,20.445000,-3.141000,-36.305000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.531247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.773171
72,72,C7,C,UNL,1,,False,True,21.739000,-3.286000,-37.131001,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.531247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.790762
73,73,C8,C,UNL,1,,False,True,22.340000,-4.676000,-36.889999,1.000000,0.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.531247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.785629
74,74,C9,C,UNL,1,,False,True,21.514000,-3.067000,-38.622002,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.822515
75,75,C10,C,UNL,1,,False,True,20.233999,-2.253000,-38.924000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.828946
76,76,C11,C,UNL,1,,False,True,20.518999,-1.464000,-40.216000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.856461
77,77,C12,C,UNL,1,,False,True,21.863001,-2.005000,-40.693001,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.866620
78,78,C13,C,UNL,1,,False,True,22.677999,-1.180000,-41.693001,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.887916
79,79,C14,C,UNL,1,,False,True,21.871000,-0.926000,-42.973999,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.915197
80,80,C15,C,UNL,1,,False,True,22.704000,-0.459000,-44.125999,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.939731
81,81,C16,C,UNL,1,,False,True,24.046000,-0.511000,-44.168999,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.940647
82,82,C17,C,UNL,1,,False,True,24.782000,0.016000,-45.380001,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.966437
83,83,C18,C,UNL,1,,False,True,25.788000,-0.997000,-45.918999,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.977915
84,84,C19,C,UNL,1,,False,True,26.736000,-1.470000,-44.823002,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.954575
85,85,C20,C,UNL,1,,False,True,25.966000,-2.054000,-43.639000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.929359
86,86,C21,C,UNL,1,,False,True,24.896999,-1.097000,-43.033001,1.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.916454
87,87,C22,C,UNL,1,,False,True,25.606001,0.074000,-42.313000,1.000000,0.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.531247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.901120
88,88,C23,C,UNL,1,,False,True,23.999001,-1.930000,-42.032001,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.895136
89,89,C24,C,UNL,1,,False,True,24.752001,-2.422000,-40.764000,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.868132
90,90,C25,C,UNL,1,,False,True,23.853001,-3.145000,-39.748001,1.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.846495
91,91,C26,C,UNL,1,,False,True,22.622999,-2.303000,-39.384998,1.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,1.000000,0.531247,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.838764
92,92,C27,C,UNL,1,,False,True,23.062000,-1.036000,-38.610001,1.000000,0.000000,0.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.531247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.822259
93,93,O1,O,UNL,1,,False,True,26.559999,-0.398000,-46.956001,0.000000,0.000000,1.000000,0.000000,0.166667,0.000000,0.000000,1.000000,0.531247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000

========== COMBINED PROTEIN FEATURES ==========

,row_index,atom_name,atom_symbol,residue_name,residue_number,chain_id,is_protein,is_ligand,x,y,z,atom_C,atom_N,atom_O,atom_S,degree_norm,hybridization_SP,hybridization_SP2,hybridization_SP3,partial_charge,is_in_ring,is_aromatic,residue_acidic_ASP_GLU,residue_basic_LYS_ARG,residue_HIS,residue_CYS,residue_polar_ASN_GLN_SER_THR,residue_GLY,residue_PRO,residue_aromatic_PHE_TYR_TRP,residue_hydrophobic_ALA_ILE_LEU_MET_VAL,z_depth
0,0,N,N,GLU,232,A,True,False,11.021000,-0.981000,-28.156000,0.379708,0.092530,0.127388,0.000000,0.185818,0.000000,0.231930,0.367695,0.285482,0.054359,0.027595,0.190846,0.137486,0.000000,0.000000,0.147753,0.023292,0.000000,0.051179,0.000000,0.325717
1,1,CA,C,GLU,232,A,True,False,10.181000,-1.055000,-26.957001,0.361715,0.093951,0.118425,0.000000,0.175090,0.000000,0.227037,0.347054,0.275006,0.049319,0.027161,0.206503,0.115349,0.000000,0.000000,0.140895,0.020376,0.000000,0.050630,0.000000,0.309167
2,2,C,C,GLU,232,A,True,False,9.519000,0.293000,-26.688000,0.344397,0.085133,0.138832,0.000000,0.172633,0.000000,0.237606,0.330756,0.266179,0.047892,0.027136,0.181064,0.116258,0.000000,0.000000,0.159873,0.022098,0.000000,0.051603,0.000000,0.303735
3,3,O,O,GLU,232,A,True,False,10.198000,1.315000,-26.628000,0.352553,0.087822,0.126708,0.000000,0.172299,0.000000,0.242215,0.324869,0.273850,0.046989,0.026580,0.154626,0.130359,0.000000,0.000000,0.169852,0.024652,0.000000,0.050687,0.000000,0.302607
4,4,CB,C,GLU,232,A,True,False,11.026000,-1.425000,-25.733000,0.356227,0.075379,0.116417,0.000000,0.171357,0.000000,0.215720,0.332303,0.263059,0.048991,0.028526,0.194141,0.112943,0.000000,0.000000,0.132384,0.018706,0.000000,0.052327,0.000000,0.292367
5,5,CG,C,GLU,232,A,True,False,11.713000,-2.771000,-25.815001,0.357303,0.070131,0.122336,0.000000,0.172179,0.000000,0.230408,0.319362,0.265765,0.051968,0.029429,0.202857,0.109832,0.000000,0.000000,0.124356,0.018044,0.000000,0.053023,0.000000,0.293170
6,6,CD,C,GLU,232,A,True,False,12.585000,-3.039000,-24.601999,0.315280,0.060238,0.148419,0.000000,0.157155,0.000000,0.240755,0.283182,0.234858,0.050996,0.030358,0.199089,0.102059,0.000000,0.000000,0.114486,0.016405,0.000000,0.053589,0.000000,0.276524
7,7,OE1,O,GLU,232,A,True,False,13.606000,-2.340000,-24.434000,0.334667,0.063668,0.122024,0.000000,0.162998,0.000000,0.233555,0.286805,0.251545,0.053415,0.031764,0.168318,0.117117,0.000000,0.000000,0.120930,0.017795,0.000000,0.055711,0.000000,0.274865
8,8,OE2,O,GLU,232,A,True,False,12.244000,-3.945000,-23.812000,0.325825,0.060156,0.121132,0.000000,0.159446,0.000000,0.235678,0.271435,0.245350,0.056177,0.034562,0.173103,0.098931,0.000000,0.000000,0.118318,0.016493,0.000000,0.060367,0.000000,0.266001
9,9,N,N,SER,234,A,True,False,7.196000,2.903000,-24.253000,0.313215,0.081770,0.121520,0.000000,0.157561,0.000000,0.204970,0.311534,0.243771,0.043531,0.027853,0.065961,0.096809,0.000000,0.000000,0.247694,0.020770,0.000000,0.057506,0.000000,0.262261
10,10,CA,C,SER,234,A,True,False,6.830000,3.206000,-22.868000,0.292912,0.081868,0.112229,0.000000,0.146399,0.000000,0.191354,0.295656,0.231606,0.041126,0.027759,0.050329,0.087115,0.000000,0.000000,0.248787,0.017419,0.000000,0.059734,0.000000,0.242630
11,11,C,C,SER,234,A,True,False,6.269000,4.630000,-22.822001,0.283875,0.073184,0.128971,0.000000,0.145819,0.000000,0.201726,0.284304,0.225551,0.038963,0.025797,0.043273,0.093344,0.000000,0.000000,0.251487,0.018323,0.000000,0.056456,0.000000,0.241965
12,12,O,O,SER,234,A,True,False,5.962000,5.214000,-23.861000,0.304812,0.078790,0.124554,0.000000,0.152400,0.000000,0.219862,0.288295,0.244121,0.040030,0.025285,0.046599,0.101979,0.000000,0.000000,0.258314,0.021419,0.000000,0.054001,0.000000,0.255722
13,13,CB,C,SER,234,A,True,False,8.057000,3.088000,-21.952999,0.282770,0.070162,0.114591,0.000000,0.142749,0.000000,0.174863,0.292660,0.217781,0.043326,0.030760,0.048267,0.086486,0.000000,0.000000,0.227103,0.016603,0.000000,0.066744,0.000000,0.229731
14,14,OG,O,SER,234,A,True,False,7.690000,3.131000,-20.580000,0.274042,0.067091,0.097150,0.000000,0.135601,0.000000,0.169144,0.269139,0.207761,0.045922,0.034286,0.040651,0.080851,0.000000,0.000000,0.201100,0.014531,0.000000,0.080531,0.000000,0.210720
15,15,N,N,PHE,239,A,True,False,6.718000,2.515000,-17.246000,0.236051,0.061066,0.070163,0.000000,0.117633,0.000000,0.153611,0.213669,0.173673,0.053066,0.043040,0.029545,0.063381,0.000000,0.000000,0.122449,0.010668,0.000000,0.123561,0.000000,0.168284
16,16,CA,C,PHE,239,A,True,False,8.093000,2.540000,-16.761999,0.230454,0.061504,0.065015,0.000000,0.114357,0.000000,0.161388,0.195584,0.169789,0.059005,0.050188,0.025925,0.056710,0.000000,0.000000,0.109243,0.009426,0.000000,0.140072,0.000000,0.159864
17,17,C,C,PHE,239,A,True,False,8.884000,3.839000,-16.931999,0.220309,0.062180,0.078104,0.000000,0.114652,0.000000,0.171380,0.189213,0.167244,0.050140,0.041681,0.024121,0.060307,0.000000,0.000000,0.128998,0.009669,0.000000,0.122532,0.000000,0.161137
18,18,O,O,PHE,239,A,True,False,9.455000,4.345000,-15.968000,0.220427,0.051333,0.068303,0.000000,0.110167,0.000000,0.165791,0.174272,0.164716,0.051202,0.042541,0.023257,0.062054,0.000000,0.000000,0.116176,0.009733,0.000000,0.113534,0.000000,0.153083
19,19,CB,C,PHE,239,A,True,False,8.884000,1.390000,-17.382000,0.252790,0.052807,0.064579,0.000000,0.121541,0.000000,0.173605,0.196571,0.176051,0.081484,0.071897,0.030471,0.058684,0.000000,0.000000,0.108787,0.009997,0.000000,0.145197,0.000000,0.166891
20,20,CG,C,PHE,239,A,True,False,9.983000,0.876000,-16.499001,0.253865,0.041882,0.055624,0.000000,0.114208,0.000000,0.182586,0.168786,0.166408,0.105315,0.096244,0.027810,0.053312,0.000000,0.000000,0.089505,0.009039,0.000000,0.155544,0.000000,0.155823
21,21,CD1,C,PHE,239,A,True,False,9.684000,0.125000,-15.369000,0.238431,0.038136,0.050739,0.000000,0.107571,0.000000,0.178349,0.148957,0.154912,0.109477,0.100383,0.026423,0.050019,0.000000,0.000000,0.080169,0.008535,0.000000,0.145996,0.000000,0.145039
22,22,CD2,C,PHE,239,A,True,False,11.314000,1.164000,-16.778999,0.256356,0.042467,0.058512,0.000000,0.116714,0.000000,0.190557,0.166777,0.169072,0.110771,0.101001,0.030006,0.058770,0.000000,0.000000,0.093987,0.009906,0.000000,0.147189,0.000000,0.160433
23,23,CE1,C,PHE,239,A,True,False,10.696000,-0.334000,-14.528000,0.227683,0.034551,0.047163,0.000000,0.100096,0.000000,0.174223,0.135173,0.145775,0.111653,0.102455,0.025553,0.048539,0.000000,0.000000,0.073553,0.008300,0.000000,0.137081,0.000000,0.137374
24,24,CE2,C,PHE,239,A,True,False,12.329000,0.710000,-15.945000,0.246663,0.038891,0.054020,0.000000,0.109342,0.000000,0.186504,0.153069,0.159930,0.114850,0.104813,0.029125,0.057297,0.000000,0.000000,0.084924,0.009656,0.000000,0.140594,0.000000,0.152783
25,25,CZ,C,PHE,239,A,True,False,12.017000,-0.040000,-14.817000,0.232054,0.035038,0.048458,0.000000,0.101612,0.000000,0.177555,0.137995,0.147989,0.113835,0.104233,0.026607,0.051394,0.000000,0.000000,0.075363,0.008738,0.000000,0.136299,0.000000,0.140944
26,26,N,N,SER,240,A,True,False,8.927000,4.374000,-18.146000,0.247866,0.058675,0.079905,0.000000,0.124721,0.000000,0.170137,0.216309,0.186729,0.045236,0.036130,0.026836,0.070162,0.000000,0.000000,0.156830,0.011241,0.000000,0.105257,0.000000,0.176000
27,27,CA,C,SER,240,A,True,False,9.685000,5.594000,-18.407000,0.242066,0.064560,0.085379,0.000000,0.122202,0.000000,0.171654,0.220351,0.187336,0.039972,0.030728,0.025912,0.080707,0.000000,0.000000,0.180263,0.012330,0.000000,0.076436,0.000000,0.180156
28,28,C,C,SER,240,A,True,False,9.088000,6.854000,-17.790001,0.227538,0.058863,0.092464,0.000000,0.116229,0.000000,0.162303,0.216563,0.176483,0.035913,0.026789,0.023586,0.090317,0.000000,0.000000,0.170848,0.012116,0.000000,0.065935,0.000000,0.173685
29,29,O,O,SER,240,A,True,False,9.793000,7.632000,-17.143999,0.227962,0.057998,0.079147,0.000000,0.111782,0.000000,0.156004,0.209104,0.175820,0.035689,0.026309,0.022932,0.098268,0.000000,0.000000,0.154141,0.012328,0.000000,0.060940,0.000000,0.168031
30,30,CB,C,SER,240,A,True,False,9.840000,5.800000,-19.917000,0.258315,0.062791,0.103057,0.000000,0.130500,0.000000,0.160870,0.263293,0.197668,0.039065,0.028642,0.030492,0.094949,0.000000,0.000000,0.199883,0.015534,0.000000,0.064833,0.000000,0.200245
31,31,OG,O,SER,240,A,True,False,10.584000,6.973000,-20.194000,0.269941,0.062249,0.097872,0.000000,0.131578,0.000000,0.156461,0.273602,0.203645,0.037510,0.026380,0.030228,0.113792,0.000000,0.000000,0.191283,0.018196,0.000000,0.056860,0.000000,0.205271
32,32,N,N,LYS,242,A,True,False,7.860000,9.130000,-19.594000,0.262810,0.066803,0.087671,0.000000,0.128697,0.000000,0.153788,0.263496,0.197499,0.033037,0.022231,0.025956,0.156944,0.000000,0.000000,0.149851,0.016194,0.000000,0.049457,0.000000,0.198309
33,33,CA,C,LYS,242,A,True,False,8.050000,10.134000,-20.636999,0.276577,0.074237,0.088682,0.000000,0.133271,0.000000,0.161162,0.278335,0.211561,0.032082,0.020627,0.026421,0.186469,0.000000,0.000000,0.143681,0.018604,0.000000,0.044349,0.000000,0.210935
34,34,C,C,LYS,242,A,True,False,7.104000,9.866000,-21.819000,0.280790,0.069674,0.114205,0.000000,0.140586,0.000000,0.186767,0.277902,0.216723,0.034255,0.021478,0.030001,0.184312,0.000000,0.000000,0.160868,0.021260,0.000000,0.045993,0.000000,0.226803
35,35,O,O,LYS,242,A,True,False,7.161000,8.808000,-22.434999,0.295427,0.072025,0.110335,0.000000,0.144561,0.000000,0.197840,0.279948,0.232581,0.035289,0.022210,0.032727,0.166210,0.000000,0.000000,0.185696,0.022635,0.000000,0.047702,0.000000,0.235166
36,36,CB,C,LYS,242,A,True,False,9.501000,10.098000,-21.115999,0.292544,0.066220,0.090933,0.000000,0.139230,0.000000,0.153575,0.296122,0.213874,0.033117,0.021057,0.027767,0.182329,0.000000,0.000000,0.152347,0.021831,0.000000,0.044332,0.000000,0.216926
37,37,CG,C,LYS,242,A,True,False,10.510000,9.937000,-19.981001,0.278345,0.063236,0.083945,0.000000,0.130497,0.000000,0.139150,0.286376,0.201503,0.032953,0.021554,0.025998,0.171858,0.000000,0.000000,0.143256,0.019225,0.000000,0.045203,0.000000,0.202708
38,38,CD,C,LYS,242,A,True,False,10.489000,11.129000,-19.027000,0.267700,0.062921,0.074588,0.000000,0.124266,0.000000,0.129601,0.275608,0.192478,0.032621,0.021129,0.024579,0.172704,0.000000,0.000000,0.126261,0.017669,0.000000,0.043921,0.000000,0.191756
39,39,CE,C,LYS,242,A,True,False,11.415000,10.925000,-17.823999,0.240245,0.069060,0.070284,0.000000,0.114434,0.000000,0.123654,0.255935,0.177677,0.033247,0.021993,0.023748,0.156286,0.000000,0.000000,0.118689,0.016003,0.000000,0.045170,0.000000,0.178503
40,40,NZ,N,LYS,242,A,True,False,10.811000,10.050000,-16.773001,0.225452,0.060337,0.071418,0.000000,0.108055,0.000000,0.126703,0.230504,0.167347,0.033643,0.023173,0.022767,0.133639,0.000000,0.000000,0.119929,0.013905,0.000000,0.048631,0.000000,0.166865
41,41,N,N,SER,245,A,True,False,7.596000,7.635000,-25.440001,0.325052,0.085851,0.130880,0.000000,0.164201,0.000000,0.214562,0.327222,0.255849,0.039820,0.023113,0.045032,0.122117,0.000000,0.000000,0.263155,0.034723,0.000000,0.047555,0.000000,0.278587
42,42,CA,C,SER,245,A,True,False,8.999000,7.249000,-25.424000,0.322725,0.090391,0.128328,0.000000,0.161466,0.000000,0.215357,0.326086,0.258357,0.037650,0.021871,0.044408,0.114522,0.000000,0.000000,0.270452,0.039842,0.000000,0.044471,0.000000,0.280146
43,43,C,C,SER,245,A,True,False,9.220000,5.872000,-26.028999,0.323777,0.084029,0.146521,0.000000,0.165886,0.000000,0.232139,0.322188,0.258355,0.039932,0.022935,0.054933,0.113307,0.000000,0.000000,0.271631,0.038363,0.000000,0.046045,0.000000,0.289450
44,44,O,O,SER,245,A,True,False,8.305000,5.051000,-26.114000,0.333757,0.087002,0.135379,0.000000,0.166645,0.000000,0.240641,0.315497,0.267462,0.041872,0.024254,0.062181,0.111807,0.000000,0.000000,0.270106,0.032012,0.000000,0.048922,0.000000,0.289645
45,45,CB,C,SER,245,A,True,False,9.549000,7.273000,-23.992001,0.305125,0.075208,0.130613,0.000000,0.154012,0.000000,0.189878,0.321068,0.238593,0.036542,0.022412,0.040050,0.119313,0.000000,0.000000,0.247137,0.033389,0.000000,0.046132,0.000000,0.259689
46,46,OG,O,SER,245,A,True,False,9.053000,6.196000,-23.211000,0.300621,0.072244,0.121448,0.000000,0.148974,0.000000,0.186363,0.307951,0.233958,0.037198,0.023992,0.041114,0.111876,0.000000,0.000000,0.242252,0.025306,0.000000,0.050417,0.000000,0.248105
47,47,N,N,LYS,247,A,True,False,12.707000,2.898000,-27.024000,0.361698,0.091904,0.121915,0.000000,0.177890,0.000000,0.219346,0.356171,0.272487,0.046690,0.024798,0.089846,0.194052,0.000000,0.000000,0.171884,0.033064,0.000000,0.046613,0.000000,0.310234
48,48,CA,C,LYS,247,A,True,False,14.106000,2.533000,-26.990000,0.366145,0.096617,0.112031,0.000000,0.175956,0.000000,0.212128,0.362666,0.277165,0.046192,0.023842,0.079155,0.223082,0.000000,0.000000,0.156970,0.030026,0.000000,0.044078,0.000000,0.311973
49,49,C,C,LYS,247,A,True,False,14.209000,1.422000,-28.017000,0.370764,0.088977,0.136923,0.000000,0.182659,0.000000,0.234621,0.362043,0.279163,0.051257,0.024682,0.094150,0.227157,0.000000,0.000000,0.151864,0.028243,0.000000,0.045365,0.000000,0.327148
50,50,O,O,LYS,247,A,True,False,13.467000,0.440000,-27.955000,0.380081,0.089812,0.125452,0.000000,0.182457,0.000000,0.244771,0.350574,0.290614,0.052460,0.025756,0.119722,0.205577,0.000000,0.000000,0.146918,0.025819,0.000000,0.047286,0.000000,0.325804
51,51,CB,C,LYS,247,A,True,False,14.511000,2.029000,-25.603001,0.361623,0.079418,0.104214,0.000000,0.170494,0.000000,0.189040,0.356215,0.260014,0.046153,0.025659,0.077975,0.209414,0.000000,0.000000,0.147109,0.025796,0.000000,0.046795,0.000000,0.292024
52,52,CG,C,LYS,247,A,True,False,15.982000,2.251000,-25.296000,0.366040,0.075577,0.097100,0.000000,0.168089,0.000000,0.174457,0.364261,0.257973,0.047716,0.025974,0.066821,0.210952,0.000000,0.000000,0.147534,0.025797,0.000000,0.046782,0.000000,0.287527
53,53,CD,C,LYS,247,A,True,False,16.274000,2.091000,-23.813999,0.342136,0.074740,0.090280,0.000000,0.156885,0.000000,0.162611,0.344545,0.241620,0.048291,0.028354,0.061698,0.197740,0.000000,0.000000,0.137376,0.022814,0.000000,0.050272,0.000000,0.266532
54,54,CE,C,LYS,247,A,True,False,17.686001,2.554000,-23.478001,0.325164,0.087572,0.087264,0.000000,0.152361,0.000000,0.155810,0.344190,0.235214,0.049701,0.028392,0.054660,0.194301,0.000000,0.000000,0.138024,0.023086,0.000000,0.050032,0.000000,0.262172
55,55,NZ,N,LYS,247,A,True,False,17.969000,2.454000,-22.018999,0.307841,0.077088,0.084000,0.000000,0.143685,0.000000,0.153943,0.314985,0.221021,0.052321,0.031776,0.051932,0.170582,0.000000,0.000000,0.131795,0.021341,0.000000,0.055092,0.000000,0.243443
56,56,N,N,SER,268,A,True,False,17.091000,6.059000,-28.403999,0.380662,0.101294,0.122951,0.000000,0.190463,0.000000,0.212510,0.392397,0.287445,0.054349,0.023870,0.054222,0.138060,0.000000,0.000000,0.263089,0.049482,0.000000,0.044228,0.000000,0.333481
57,57,CA,C,SER,268,A,True,False,16.101000,6.390000,-27.388000,0.357635,0.107149,0.118485,0.000000,0.181548,0.000000,0.216486,0.366784,0.279190,0.045688,0.021787,0.048331,0.128322,0.000000,0.000000,0.266643,0.055849,0.000000,0.040658,0.000000,0.319631
58,58,C,C,SER,268,A,True,False,15.584000,7.811000,-27.525000,0.342325,0.107981,0.135881,0.000000,0.181941,0.000000,0.247279,0.338908,0.272101,0.043996,0.020997,0.044096,0.115628,0.000000,0.000000,0.258918,0.086723,0.000000,0.039601,0.000000,0.321514
59,59,O,O,SER,268,A,True,False,16.313999,8.717000,-27.931999,0.368625,0.098148,0.128082,0.000000,0.188600,0.000000,0.251155,0.343699,0.288705,0.049437,0.022703,0.045859,0.119681,0.000000,0.000000,0.264409,0.074529,0.000000,0.042737,0.000000,0.326185
60,60,CB,C,SER,268,A,True,False,16.687000,6.191000,-25.987000,0.341261,0.087218,0.124954,0.000000,0.171656,0.000000,0.187457,0.365976,0.258760,0.045417,0.023004,0.047047,0.133060,0.000000,0.000000,0.245040,0.044749,0.000000,0.042610,0.000000,0.299607
61,61,OG,O,SER,268,A,True,False,17.787001,7.054000,-25.767000,0.345101,0.084581,0.119066,0.000000,0.169479,0.000000,0.187205,0.361543,0.260191,0.048677,0.024138,0.045813,0.128416,0.000000,0.000000,0.241958,0.043374,0.000000,0.044567,0.000000,0.296725
62,62,N,N,GLY,269,A,True,False,14.316000,7.997000,-27.179001,0.365062,0.090884,0.122873,0.000000,0.182769,0.000000,0.246648,0.332171,0.282661,0.043177,0.021500,0.045149,0.118491,0.000000,0.000000,0.235963,0.099558,0.000000,0.041015,0.000000,0.314608
63,63,CA,C,GLY,269,A,True,False,13.709000,9.309000,-27.264000,0.353135,0.101981,0.125512,0.000000,0.179871,0.000000,0.264814,0.315814,0.280811,0.044605,0.022178,0.044161,0.118513,0.000000,0.000000,0.211278,0.124422,0.000000,0.042692,0.000000,0.313978
64,64,C,C,GLY,269,A,True,False,12.207000,9.210000,-27.445999,0.351567,0.088450,0.144487,0.000000,0.176727,0.000000,0.257784,0.326720,0.276344,0.044425,0.022466,0.045913,0.120828,0.000000,0.000000,0.204134,0.131313,0.000000,0.043748,0.000000,0.314021
65,65,O,O,GLY,269,A,True,False,11.586000,8.239000,-27.018999,0.359620,0.087552,0.128238,0.000000,0.176249,0.000000,0.254652,0.320759,0.282416,0.043299,0.022688,0.048199,0.123120,0.000000,0.000000,0.214158,0.109167,0.000000,0.044429,0.000000,0.307012

========== COMBINED LIGAND FEATURES ==========

,row_index,atom_name,atom_symbol,residue_name,residue_number,chain_id,is_protein,is_ligand,x,y,z,atom_C,atom_N,atom_O,atom_S,degree_norm,hybridization_SP,hybridization_SP2,hybridization_SP3,partial_charge,is_in_ring,is_aromatic,residue_acidic_ASP_GLU,residue_basic_LYS_ARG,residue_HIS,residue_CYS,residue_polar_ASN_GLN_SER_THR,residue_GLY,residue_PRO,residue_aromatic_PHE_TYR_TRP,residue_hydrophobic_ALA_ILE_LEU_MET_VAL,z_depth
66,66,C1,C,UNL,1,,False,True,23.747999,-2.967000,-33.507000,0.561941,0.062719,0.088923,0.000000,0.219036,0.000000,0.158683,0.554900,0.355182,0.128802,0.027171,0.061254,0.107871,0.000000,0.000000,0.129770,0.023556,0.000000,0.048631,0.000000,0.452566
67,67,C2,C,UNL,1,,False,True,22.431000,-2.196000,-33.411999,0.561855,0.062133,0.087572,0.000000,0.238013,0.000000,0.156314,0.555246,0.354486,0.119534,0.025946,0.060983,0.107308,0.000000,0.000000,0.128087,0.023459,0.000000,0.046560,0.000000,0.451077
68,68,C3,C,UNL,1,,False,True,21.365000,-3.077000,-32.757999,0.540326,0.065128,0.092178,0.000000,0.213310,0.000000,0.165463,0.532169,0.345817,0.113239,0.027400,0.067213,0.113565,0.000000,0.000000,0.132686,0.023963,0.000000,0.049067,0.000000,0.434031
69,69,C4,C,UNL,1,,False,True,21.931999,-1.706000,-34.785999,0.590645,0.062230,0.087946,0.000000,0.243458,0.000000,0.156197,0.584624,0.370150,0.140362,0.025463,0.060384,0.106160,0.000000,0.000000,0.128964,0.023975,0.000000,0.045920,0.000000,0.479601
70,70,C5,C,UNL,1,,False,True,20.510000,-2.171000,-35.117001,0.593290,0.063965,0.090615,0.000000,0.245029,0.000000,0.161382,0.586488,0.373279,0.143105,0.025891,0.064188,0.108968,0.000000,0.000000,0.131655,0.024439,0.000000,0.046792,0.000000,0.483964
71,71,C6,C,UNL,1,,False,True,20.445000,-3.141000,-36.305000,0.622782,0.061862,0.088526,0.000000,0.258036,0.000000,0.157227,0.615943,0.387413,0.173245,0.025647,0.062769,0.104360,0.000000,0.000000,0.127666,0.023541,0.000000,0.046388,0.000000,0.512021
72,72,C7,C,UNL,1,,False,True,21.739000,-3.286000,-37.131001,0.650202,0.057564,0.082996,0.000000,0.278720,0.000000,0.146327,0.644435,0.398333,0.213522,0.024341,0.057006,0.096699,0.000000,0.000000,0.119711,0.022081,0.000000,0.043999,0.000000,0.538016
73,73,C8,C,UNL,1,,False,True,22.340000,-4.676000,-36.889999,0.637301,0.060593,0.087735,0.000000,0.250278,0.000000,0.155125,0.630505,0.394298,0.194884,0.026425,0.060935,0.101959,0.000000,0.000000,0.125763,0.022844,0.000000,0.047612,0.000000,0.526958
74,74,C9,C,UNL,1,,False,True,21.514000,-3.067000,-38.622002,0.683218,0.056750,0.082546,0.000000,0.299767,0.000000,0.144265,0.678250,0.415560,0.352272,0.023960,0.055508,0.094531,0.000000,0.000000,0.118688,0.022036,0.000000,0.043446,0.000000,0.573754
75,75,C10,C,UNL,1,,False,True,20.233999,-2.253000,-38.924000,0.678152,0.061617,0.089178,0.000000,0.285617,0.000000,0.156177,0.672769,0.417272,0.356990,0.025393,0.060179,0.102165,0.000000,0.000000,0.128944,0.024203,0.000000,0.046211,0.000000,0.572009
76,76,C11,C,UNL,1,,False,True,20.518999,-1.464000,-40.216000,0.704291,0.061818,0.090353,0.000000,0.297800,0.000000,0.156445,0.700017,0.431859,0.402514,0.025475,0.058868,0.101884,0.000000,0.000000,0.130378,0.024701,0.000000,0.046469,0.000000,0.601865
77,77,C12,C,UNL,1,,False,True,21.863001,-2.005000,-40.693001,0.726937,0.056243,0.083439,0.000000,0.322251,0.000000,0.142690,0.723929,0.439252,0.443192,0.023702,0.053249,0.092861,0.000000,0.000000,0.118838,0.022341,0.000000,0.043143,0.000000,0.625174
78,78,C13,C,UNL,1,,False,True,22.677999,-1.180000,-41.693001,0.746880,0.056092,0.084944,0.000000,0.330591,0.000000,0.142136,0.745780,0.450636,0.472730,0.023715,0.051947,0.092372,0.000000,0.000000,0.119210,0.022545,0.000000,0.043216,0.000000,0.652307
79,79,C14,C,UNL,1,,False,True,21.871000,-0.926000,-42.973999,0.760931,0.060958,0.093308,0.000000,0.322240,0.000000,0.154687,0.760511,0.463332,0.480738,0.025747,0.056306,0.099922,0.000000,0.000000,0.129912,0.024632,0.000000,0.047036,0.000000,0.671396
80,80,C15,C,UNL,1,,False,True,22.704000,-0.459000,-44.125999,0.781323,0.061125,0.097282,0.000000,0.331074,0.000000,0.155218,0.784513,0.476284,0.504799,0.026059,0.055682,0.100092,0.000000,0.000000,0.130776,0.024808,0.000000,0.047629,0.000000,0.700368
81,81,C16,C,UNL,1,,False,True,24.046000,-0.511000,-44.168999,0.787917,0.057370,0.095359,0.000000,0.348920,0.000000,0.145729,0.794918,0.478137,0.520398,0.024714,0.051938,0.094144,0.000000,0.000000,0.122822,0.023225,0.000000,0.045103,0.000000,0.713123
82,82,C17,C,UNL,1,,False,True,24.782000,0.016000,-45.380001,0.789882,0.061864,0.114690,0.000000,0.337743,0.000000,0.157284,0.809152,0.490135,0.513082,0.026856,0.055399,0.101412,0.000000,0.000000,0.132858,0.025124,0.000000,0.049047,0.000000,0.732044
83,83,C18,C,UNL,1,,False,True,25.788000,-0.997000,-45.918999,0.779189,0.061456,0.137270,0.000000,0.350775,0.000000,0.156687,0.821229,0.496320,0.507569,0.027114,0.055286,0.100882,0.000000,0.000000,0.131851,0.024706,0.000000,0.049444,0.000000,0.747279
84,84,C19,C,UNL,1,,False,True,26.736000,-1.470000,-44.823002,0.779245,0.060964,0.114365,0.000000,0.329821,0.000000,0.155417,0.799157,0.484066,0.502778,0.027050,0.054963,0.100366,0.000000,0.000000,0.130563,0.024376,0.000000,0.049221,0.000000,0.720866
85,85,C20,C,UNL,1,,False,True,25.966000,-2.054000,-43.639000,0.773693,0.058185,0.097482,0.000000,0.327698,0.000000,0.148280,0.781079,0.471719,0.498590,0.025692,0.053075,0.095930,0.000000,0.000000,0.124208,0.023156,0.000000,0.046704,0.000000,0.697554
86,86,C21,C,UNL,1,,False,True,24.896999,-1.097000,-43.033001,0.772892,0.054819,0.088743,0.000000,0.353147,0.000000,0.139230,0.777223,0.466202,0.496160,0.023756,0.049855,0.090297,0.000000,0.000000,0.117058,0.022025,0.000000,0.043246,0.000000,0.691417
87,87,C22,C,UNL,1,,False,True,25.606001,0.074000,-42.313000,0.745601,0.060104,0.095415,0.000000,0.299488,0.000000,0.152089,0.749031,0.456092,0.355694,0.025861,0.053777,0.099103,0.000000,0.000000,0.128642,0.024380,0.000000,0.047074,0.000000,0.661838
88,88,C23,C,UNL,1,,False,True,23.999001,-1.930000,-42.032001,0.756037,0.054610,0.084489,0.000000,0.335492,0.000000,0.138783,0.756353,0.454948,0.486076,0.023576,0.050556,0.090112,0.000000,0.000000,0.116081,0.021753,0.000000,0.042873,0.000000,0.664362
89,89,C24,C,UNL,1,,False,True,24.752001,-2.422000,-40.764000,0.726681,0.056207,0.085244,0.000000,0.305317,0.000000,0.142845,0.725286,0.439947,0.442036,0.024440,0.052292,0.093187,0.000000,0.000000,0.119130,0.022195,0.000000,0.044319,0.000000,0.629652
90,90,C25,C,UNL,1,,False,True,23.853001,-3.145000,-39.748001,0.706798,0.056193,0.083504,0.000000,0.297686,0.000000,0.142993,0.703501,0.428437,0.409376,0.024376,0.053370,0.093438,0.000000,0.000000,0.118460,0.021949,0.000000,0.044145,0.000000,0.603536
91,91,C26,C,UNL,1,,False,True,22.622999,-2.303000,-39.384998,0.704343,0.054433,0.079988,0.000000,0.318521,0.000000,0.137994,0.700770,0.425087,0.398760,0.023045,0.051758,0.090435,0.000000,0.000000,0.114627,0.021438,0.000000,0.041819,0.000000,0.598221
92,92,C27,C,UNL,1,,False,True,23.062000,-1.036000,-38.610001,0.676795,0.059229,0.086235,0.000000,0.271988,0.000000,0.149155,0.673104,0.414583,0.278566,0.024668,0.055092,0.098559,0.000000,0.000000,0.125057,0.023639,0.000000,0.044773,0.000000,0.572745
93,93,O1,O,UNL,1,,False,True,26.559999,-0.398000,-46.956001,0.661207,0.068474,0.270319,0.000000,0.318089,0.000000,0.174649,0.825351,0.505398,0.367424,0.030368,0.061003,0.112337,0.000000,0.000000,0.147270,0.027608,0.000000,0.055412,0.000000,0.752932