In [1]:
import MDAnalysis as mda
import pandas as pd
from biopandas.pdb import PandasPdb
import os
import glob
import re
import math
import numpy as np
from rdkit import Chem
from rdkit.Chem import Draw

def pdb_to_dataframe(pdb_file):
    """
    Load a PDB file using MDAnalysis and convert key atom information to a pandas DataFrame.
    """
    u = mda.Universe(pdb_file)
    
    # Extract atom-related data: atom name, residue name, residue ID, and chain ID
    atom_data = {
        'Atom Name': u.atoms.names,
        'Residue Name': u.atoms.resnames,
        'Residue ID': u.atoms.resids,
        'Chain ID': u.atoms.segids,
        'X': u.atoms.positions[:, 0],
        'Y': u.atoms.positions[:, 1],
        'Z': u.atoms.positions[:, 2],
    }
    
    # Create a pandas DataFrame from the atom data
    df = pd.DataFrame(atom_data)
    
    return df

def grid_list(atom_df):
    return list(zip(atom_df['x_coord'], atom_df['y_coord'], atom_df['z_coord']))

def filtering_proteins(atom_df, grid_list, radius=5.0):
    import numpy as np

    # Adjust these column names if needed for your dataframe
    residue_cols = ['chain_id', 'residue_name', 'residue_number', 'insertion']
    residue_cols = [col for col in residue_cols if col in atom_df.columns]

    if not residue_cols:
        raise ValueError("Could not identify residue columns in atom_df.")

    atom_coords = atom_df[['x_coord', 'y_coord', 'z_coord']].values
    initially_filtered_atoms = set()

    # Step 1: find atoms within radius of any grid point
    for x, y, z in grid_list:
        distances_sq = (
            (atom_coords[:, 0] - x) ** 2 +
            (atom_coords[:, 1] - y) ** 2 +
            (atom_coords[:, 2] - z) ** 2
        )
        mask = distances_sq <= radius ** 2
        initially_filtered_atoms.update(atom_df.index[mask])

    print(f"Total atoms within {radius} Å cutoff: {len(initially_filtered_atoms)}")

    if not initially_filtered_atoms:
        return atom_df.loc[list(initially_filtered_atoms)]

    grouped = atom_df.groupby(residue_cols)

    # Step 2: residues passing the 50% rule
    residue_keep_set = set()

    for residue_key, residue_df in grouped:
        residue_atom_indices = set(residue_df.index)
        n_total = len(residue_atom_indices)
        n_filtered = len(residue_atom_indices & initially_filtered_atoms)

        if n_total == 0:
            continue

        fraction_present = n_filtered / n_total

        if fraction_present >= 0.5:
            residue_keep_set.add(residue_key)

    # Step 3: expand to all atoms in kept residues
    filtered_atoms = set()
    for residue_key, residue_df in grouped:
        if residue_key in residue_keep_set:
            filtered_atoms.update(residue_df.index)

    # Fallback: if nothing survives 50% rule, keep residues that had any atom in cutoff
    if len(filtered_atoms) == 0:
        print("No residues passed the 50% occupancy filter. Falling back to residues with at least one atom within cutoff.")

        fallback_residue_keep_set = set()

        for residue_key, residue_df in grouped:
            residue_atom_indices = set(residue_df.index)
            if len(residue_atom_indices & initially_filtered_atoms) > 0:
                fallback_residue_keep_set.add(residue_key)

        for residue_key, residue_df in grouped:
            if residue_key in fallback_residue_keep_set:
                filtered_atoms.update(residue_df.index)

    print(f"Total atoms after residue expansion + filtering: {len(filtered_atoms)}")
    return atom_df.loc[list(filtered_atoms)]

/home/alexhernandez/miniconda3/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def get_fpocket_protein_name(filename):
    basename = os.path.basename(filename)
    match = re.match(r'([a-zA-Z0-9]{4})', basename)
    if match:
        return match.group(1).upper()
    return None

def get_fpocket_pockets(fpocket_file):
    """
    Read an fpocket output PDB and return:
        pocket_id -> DataFrame of fpocket HETATM pseudo-atoms for that pocket
    """
    ppdb = PandasPdb().read_pdb(fpocket_file)
    hetatm = ppdb.df['HETATM'].copy()

    if hetatm.empty:
        return {}

    hetatm = hetatm[~hetatm['atom_name'].astype(str).str.startswith('H')].copy()

    pockets = {}
    for pocket_id in sorted(hetatm['residue_number'].dropna().unique()):
        pocket_df = hetatm[hetatm['residue_number'] == pocket_id].copy()
        if not pocket_df.empty:
            pockets[int(pocket_id)] = pocket_df

    return pockets

def get_protein_name(filename):
    basename = os.path.basename(filename)
    match = re.match(r'([a-zA-Z0-9]{4})', basename)
    if match:
        return match.group(1).upper()
    return None

def natural_sort_key(s):
    return [int(text) if text.isdigit() else text.lower() for text in re.split(r'(\d+)', s)]

In [3]:
def get_positive_ligand_atoms(positive_file, protein_name):
    protein_pdb_df = PandasPdb().read_pdb(positive_file)
    protein_pdb_df.df.keys()
    protein = protein_pdb_df.df['ATOM']
    protein = protein[~protein['atom_name'].str.startswith('H')] # don't use hydrogen
    protein_coords = protein[['x_coord', 'y_coord', 'z_coord']].values
    protein_centroid = protein_coords.mean(axis=0)
    print(set(protein['chain_id']))
    print(positive_file)

    ligand_df = PandasPdb().read_pdb(positive_file)
    ligand_df.df.keys()
    ligand = ligand_df.df['HETATM']
    ligand = ligand[ligand['residue_name']=="CLR"]
    x = list(set(zip(ligand['residue_number'], ligand['chain_id'])))

    #get the most inward residue
    min_distance = float('inf')
    closest_clr = None

    all_ligands = []

    for residue_number, chain_id in x:
        clr_atoms = ligand[(ligand['residue_number'] == residue_number) & (ligand['chain_id'] == chain_id)]
        if clr_atoms.empty:
            continue

        clr_coords = clr_atoms[['x_coord', 'y_coord', 'z_coord']].values
        clr_centroid = clr_coords.mean(axis=0)
        
        distance = np.linalg.norm(protein_centroid - clr_centroid)
        
        if distance < min_distance:
            min_distance = distance
            closest_clr = (residue_number, chain_id)

        grid_list_ = grid_list(clr_atoms)

        all_ligands.append(grid_list_)

    ligand_ = ligand[(ligand['residue_number'] == closest_clr[0]) & (ligand['chain_id'] == closest_clr[1])]
    grid_list_ = grid_list(ligand_)

    filtered_atoms = filtering_proteins(protein, grid_list_)

    # Save to pdb
    filtered_pdb = PandasPdb()
    filtered_pdb.df['ATOM'] = filtered_atoms
    filtered_pdb_path = f"filtered-rdkit-fpocket-5A/positive/{protein_name}-filtered.pdb"
    os.makedirs(os.path.dirname(filtered_pdb_path), exist_ok=True)
    filtered_pdb.to_pdb(path=filtered_pdb_path, records=None, gz=False, append_newline=True)
    print(f"Saved: {filtered_pdb_path}")

    return protein, all_ligands

In [4]:
def check_if_unlabeled_is_positive(positive_grid_list, unlabeled_grid_list, cutoff=5.0):
    positive_grid_list = np.asarray(positive_grid_list, dtype=float)
    unlabeled_grid_list = np.asarray(unlabeled_grid_list, dtype=float)

    if positive_grid_list.size == 0 or unlabeled_grid_list.size == 0:
        print("Empty positive_grid_list or unlabeled_grid_list")
        return False

    chol_centroid = positive_grid_list.mean(axis=0)
    fpocket_centroid = unlabeled_grid_list.mean(axis=0)

    distance = np.linalg.norm(chol_centroid - fpocket_centroid)
    print(f"Centroid distance: {distance:.3f} Å")
    return distance <= cutoff

In [5]:
def get_protein_name(filename):
    basename = os.path.basename(filename)  # Get file name without path
    match = re.match(r'([a-zA-Z0-9]{4})', basename)  # Match the first 4-character PDB ID
    if match:
        return match.group(1).upper()
    else:
        return None
def get_mode_index(filename):
    basename = os.path.basename(filename)
    match = re.search(r'mode_(\d+)', basename)
    if match:
        return int(match.group(1))
    else:
        return None  # or raise ValueError("No mode index found.")

def natural_sort_key(s):
    """Function to sort strings in a natural alphanumeric order."""
    return [int(text) if text.isdigit() else text.lower() for text in re.split(r'(\d+)', s)]

In [6]:
# positive_files = glob.glob("../GNN/CLR-PDB/*.pdb")
# positive_files = sorted(positive_files, key=natural_sort_key)

# fpocket_files = glob.glob("../FPocketUnlabeledUnfiltered/*/*_protein_out.pdb")
# fpocket_files = sorted(fpocket_files, key=natural_sort_key)

# positive_index = 0
# protein, all_lig_gridlist = get_positive_ligand_atoms(
#     positive_files[positive_index],
#     get_protein_name(positive_files[positive_index])
# )

# for fpocket_file in fpocket_files:
#     positive_name = get_protein_name(positive_files[positive_index])
#     unlabeled_name = get_fpocket_protein_name(fpocket_file)

#     if unlabeled_name is None:
#         print(f"Skipping file with no PDB id match: {fpocket_file}")
#         continue

#     if positive_name != unlabeled_name:
#         positive_index += 1

#         if positive_index >= len(positive_files):
#             raise Exception(f"Ran out of positive files while matching {fpocket_file}")

#         positive_name = get_protein_name(positive_files[positive_index])

#         if positive_name != unlabeled_name:
#             raise Exception(
#                 f"Proteins Not Matching Up!!! positive={positive_name}, fpocket={unlabeled_name}"
#             )

#         protein, all_lig_gridlist = get_positive_ligand_atoms(
#             positive_files[positive_index],
#             positive_name
#         )

#     pockets = get_fpocket_pockets(fpocket_file)

#     if not pockets:
#         print(f"No pockets found in {fpocket_file}")
#         continue

#     for pocket_id, pocket_df in pockets.items():
#         grid_list_ = grid_list(pocket_df)

#         # this is the NEW filtering logic being applied to RAW fpocket pockets
#         filtered_atoms = filtering_proteins(protein, grid_list_)

#         if filtered_atoms.empty:
#             continue

#         is_positive = False
#         for lig in all_lig_gridlist:
#             if check_if_unlabeled_is_positive(lig.copy(), grid_list_.copy()):
#                 is_positive = True
#                 break

#         filtered_pdb = PandasPdb()
#         filtered_pdb.df['ATOM'] = filtered_atoms

#         if is_positive:
#             filtered_pdb_path = f"filtered-rdkit-fpocket-5A/unlabeled/{unlabeled_name}-p{pocket_id}-positive.pdb"
#         else:
#             filtered_pdb_path = f"filtered-rdkit-fpocket-5A/unlabeled/{unlabeled_name}-p{pocket_id}.pdb"

#         os.makedirs(os.path.dirname(filtered_pdb_path), exist_ok=True)
#         filtered_pdb.to_pdb(path=filtered_pdb_path, records=None, gz=False, append_newline=True)

#         print(f"Saved: {filtered_pdb_path}")

In [7]:
# %%
import os
import glob
import re
from io import StringIO

import py3Dmol
import pandas as pd
from biopandas.pdb import PandasPdb


def _df_to_pdb_block(df, record_name="ATOM"):
    """
    Convert a Biopandas-style ATOM/HETATM dataframe to a PDB block string.
    """
    if df is None or df.empty:
        return ""

    lines = []
    for _, row in df.iterrows():
        atom_number = int(row.get("atom_number", 1))
        atom_name = str(row.get("atom_name", "X"))[:4]
        alt_loc = str(row.get("alt_loc", ""))[:1]
        residue_name = str(row.get("residue_name", "UNK"))[:3]
        chain_id = str(row.get("chain_id", "A"))[:1]
        residue_number = int(row.get("residue_number", 1))
        insertion = str(row.get("insertion", ""))[:1]
        x = float(row.get("x_coord", 0.0))
        y = float(row.get("y_coord", 0.0))
        z = float(row.get("z_coord", 0.0))
        occupancy = float(row.get("occupancy", 1.00))
        b_factor = float(row.get("b_factor", 0.00))
        element_symbol = str(row.get("element_symbol", "")).strip()

        if not element_symbol:
            # simple fallback from atom name
            cleaned = re.sub(r'[^A-Za-z]', '', atom_name).strip()
            element_symbol = cleaned[:2].capitalize() if cleaned else "C"

        charge = str(row.get("charge", "")).strip()

        line = (
            f"{record_name:<6}"
            f"{atom_number:>5} "
            f"{atom_name:<4}"
            f"{alt_loc:1}"
            f"{residue_name:>3} "
            f"{chain_id:1}"
            f"{residue_number:>4}"
            f"{insertion:1}   "
            f"{x:>8.3f}"
            f"{y:>8.3f}"
            f"{z:>8.3f}"
            f"{occupancy:>6.2f}"
            f"{b_factor:>6.2f}          "
            f"{element_symbol:>2}"
            f"{charge:>2}"
        )
        lines.append(line)

    lines.append("END")
    return "\n".join(lines)


def _find_positive_file(pdb_id, positive_glob="../GNN/CLR-PDB/*.pdb"):
    pdb_id = pdb_id.upper()
    matches = sorted(glob.glob(positive_glob))
    for f in matches:
        base = os.path.basename(f)
        if re.match(rf"{pdb_id}", base, re.IGNORECASE):
            return f
    return None


def _find_fpocket_file(pdb_id, fpocket_glob="../FPocketUnlabeledUnfiltered/*/*_protein_out.pdb"):
    pdb_id = pdb_id.upper()
    matches = sorted(glob.glob(fpocket_glob))
    for f in matches:
        base = os.path.basename(f)
        if re.match(rf"{pdb_id}", base, re.IGNORECASE):
            return f
    return None


def get_all_cholesterol_atoms(positive_file):
    """
    Return:
      protein_df: ATOM dataframe without hydrogens
      chol_groups: list of HETATM dataframes, one per CLR molecule
    """
    ppdb = PandasPdb().read_pdb(positive_file)

    protein_df = ppdb.df["ATOM"].copy()
    protein_df = protein_df[~protein_df["atom_name"].astype(str).str.startswith("H")].copy()

    hetatm = ppdb.df["HETATM"].copy()
    chol_df = hetatm[hetatm["residue_name"] == "CLR"].copy()
    chol_df = chol_df[~chol_df["atom_name"].astype(str).str.startswith("H")].copy()

    chol_groups = []
    for (resnum, chain_id), group in chol_df.groupby(["residue_number", "chain_id"], dropna=False):
        if not group.empty:
            chol_groups.append(group.copy())

    return protein_df, chol_groups


def build_filtered_region_from_grid(protein_df, grid_points, radius=5.0):
    """
    Reuse your existing filtering_proteins() function.
    grid_points should be [(x,y,z), ...]
    """
    return filtering_proteins(protein_df.copy(), grid_points, radius=radius)


def show_cholesterol_fpocket_view(
    pdb_id,
    pocket_ids=None,
    show_full_protein=True,
    show_cholesterol=True,
    show_fpocket=True,
    show_filtered_chol_regions=True,
    show_filtered_fpocket_regions=True,
    filter_radius=5.0,
    width=1100,
    height=800,
    background="white",
):
    """
    Visualize:
      - full protein
      - all experimental cholesterol molecules
      - all fpocket alpha spheres (or selected pockets)
      - filtered protein regions around cholesterol
      - filtered protein regions around fpocket pockets

    pocket_ids:
      None -> all pockets
      int  -> one pocket
      list -> selected pockets
    """
    pdb_id = pdb_id.upper()

    positive_file = _find_positive_file(pdb_id)
    fpocket_file = _find_fpocket_file(pdb_id)

    if positive_file is None:
        raise FileNotFoundError(f"Could not find experimental structure for {pdb_id}")
    if fpocket_file is None:
        raise FileNotFoundError(f"Could not find fpocket output for {pdb_id}")

    protein_df, chol_groups = get_all_cholesterol_atoms(positive_file)
    fpocket_pockets = get_fpocket_pockets(fpocket_file)

    if isinstance(pocket_ids, int):
        pocket_ids = [pocket_ids]

    if pocket_ids is not None:
        fpocket_pockets = {pid: df for pid, df in fpocket_pockets.items() if pid in pocket_ids}

    view = py3Dmol.view(width=width, height=height)
    view.setBackgroundColor(background)

    # Model 0: full protein
    if show_full_protein:
        protein_block = _df_to_pdb_block(protein_df, record_name="ATOM")
        view.addModel(protein_block, "pdb")
        view.setStyle({"model": 0}, {"cartoon": {"color": "lightgray"}})

    model_index = 1

    # Cholesterol molecules
    if show_cholesterol:
        for chol_df in chol_groups:
            chol_block = _df_to_pdb_block(chol_df, record_name="HETATM")
            view.addModel(chol_block, "pdb")
            view.setStyle({"model": model_index}, {"stick": {"colorscheme": "greenCarbon", "radius": 0.18}})
            model_index += 1

    # fpocket alpha spheres
    if show_fpocket:
        for pocket_id, pocket_df in fpocket_pockets.items():
            pocket_block = _df_to_pdb_block(pocket_df, record_name="HETATM")
            view.addModel(pocket_block, "pdb")
            # sphere is the closest py3Dmol style for a VDW-like alpha-sphere display
            view.setStyle({"model": model_index}, {"sphere": {"color": "red", "opacity": 0.9, "scale": 0.9}})
            model_index += 1

    # Filtered regions around cholesterol
    if show_filtered_chol_regions:
        for chol_df in chol_groups:
            chol_grid = grid_list(chol_df)
            filtered_df = build_filtered_region_from_grid(protein_df, chol_grid, radius=filter_radius)
            if filtered_df is not None and not filtered_df.empty:
                filtered_block = _df_to_pdb_block(filtered_df, record_name="ATOM")
                view.addModel(filtered_block, "pdb")
                view.setStyle(
                    {"model": model_index},
                    {"sphere": {"color": "cyan", "opacity": 0.75, "scale": 0.55}}
                )
                model_index += 1

    # Filtered regions around fpocket pockets
    if show_filtered_fpocket_regions:
        for pocket_id, pocket_df in fpocket_pockets.items():
            pocket_grid = grid_list(pocket_df)
            filtered_df = build_filtered_region_from_grid(protein_df, pocket_grid, radius=filter_radius)
            if filtered_df is not None and not filtered_df.empty:
                filtered_block = _df_to_pdb_block(filtered_df, record_name="ATOM")
                view.addModel(filtered_block, "pdb")
                view.setStyle(
                    {"model": model_index},
                    {"sphere": {"color": "magenta", "opacity": 0.75, "scale": 0.55}}
                )
                model_index += 1

    view.zoomTo()
    return view

In [8]:
show_cholesterol_fpocket_view("1ZHY", pocket_ids=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Total atoms within 5.0 Å cutoff: 77
Total atoms after residue expansion + filtering: 49
Total atoms within 5.0 Å cutoff: 207
Total atoms after residue expansion + filtering: 196
Total atoms within 5.0 Å cutoff: 60
Total atoms after residue expansion + filtering: 59
Total atoms within 5.0 Å cutoff: 115
Total atoms after residue expansion + filtering: 83
Total atoms within 5.0 Å cutoff: 52
Total atoms after residue expansion + filtering: 55
Total atoms within 5.0 Å cutoff: 36
Total atoms after residue expansion + filtering: 29
Total atoms within 5.0 Å cutoff: 58
Total atoms after residue expansion + filtering: 62
Total atoms within 5.0 Å cutoff: 80
Total atoms after residue expansion + filtering: 86
Total atoms within 5.0 Å cutoff: 34
Total atoms after residue expansion + filtering: 39
Total atoms within 5.0 Å cutoff: 43
Total atoms after residue expansion + filtering: 51
Total atoms within 5.0 Å cutoff: 48
Total atoms after residue expansion + filtering: 56

In [9]:
import os
import re
import glob
import tempfile
import subprocess
import numpy as np
import pandas as pd
import MDAnalysis as mda
from pathlib import Path
from rdkit import Chem
from rdkit.Chem import rdchem

# -------------------------
# Atom subtype setup
# -------------------------
ATOM_SUBTYPES = [
    # Carbon (17)
    'C', 'CA', 'CB', 'CD', 'CD1', 'CD2', 'CE', 'CE1', 'CE2', 'CE3',
    'CG', 'CG1', 'CG2', 'CH2', 'CZ', 'CZ2', 'CZ3',

    # Oxygen (8)
    'O', 'OH', 'OD1', 'OD2', 'OE1', 'OE2', 'OG', 'OG1',

    # Nitrogen (9)
    'N', 'NE', 'NE1', 'NE2', 'ND1', 'ND2', 'NZ', 'NH1', 'NH2',

    # Sulfur (2)
    'SD', 'SG',

    # Unknown (1)
    'UNKNOWN'
]

ATOM_TO_INDEX = {atom: idx for idx, atom in enumerate(ATOM_SUBTYPES)}

# residue groups
ACIDIC = {'ASP', 'GLU'}
BASIC = {'LYS', 'ARG'}
HIS = {'HIS'}
CYS = {'CYS'}
POLAR_UNCHARGED = {'ASN', 'GLN', 'SER', 'THR'}
GLY = {'GLY'}
PRO = {'PRO'}
AROMATIC = {'PHE', 'TYR', 'TRP'}
HYDROPHOBIC = {'ALA', 'ILE', 'LEU', 'MET', 'VAL'}

# 37 subtype + 3 hybrid + 3 misc(partial_charge, ring, aromatic) + 9 residue = 52
N_ATOM_SUBTYPE = len(ATOM_SUBTYPES)
N_HYBRID = 3
N_MISC = 3
N_RESIDUE_GROUPS = 9
ENCODING_SIZE = N_ATOM_SUBTYPE + N_HYBRID + N_MISC + N_RESIDUE_GROUPS

PDB2PQR_PH = 7.4


def one_hot_encoding(pdb_df, dtype=np.int8):
    num_rows = len(pdb_df)
    one_hot_matrix = np.zeros((num_rows, N_ATOM_SUBTYPE), dtype=dtype)

    for i, atom_name in enumerate(pdb_df['Atom Name']):
        atom_name = str(atom_name).strip()
        idx = ATOM_TO_INDEX.get(atom_name, ATOM_TO_INDEX['UNKNOWN'])
        one_hot_matrix[i, idx] = 1

    return one_hot_matrix


def pdb_to_dataframe(pdb_file):
    u = mda.Universe(pdb_file)
    atom_data = {
        'Atom Name': u.atoms.names,
        'Residue Name': u.atoms.resnames,
        'Residue ID': u.atoms.resids,
        'Chain ID': u.atoms.segids,
        'X': u.atoms.positions[:, 0],
        'Y': u.atoms.positions[:, 1],
        'Z': u.atoms.positions[:, 2],
    }
    return pd.DataFrame(atom_data)

# -------------------------
# pdb2pqr charge helpers
# -------------------------

def strip_dum_atoms(pdb_path, out_path):
    with open(pdb_path) as f_in, open(out_path, "w") as f_out:
        for line in f_in:
            if "DUM" not in line:
                f_out.write(line)


def run_pdb2pqr(clean_pdb, pqr_out, ph=7.4):
    cmd = [
        "pdb2pqr",
        "--ff=AMBER",
        f"--with-ph={ph}",
        "--quiet",
        str(clean_pdb),
        str(pqr_out),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.returncode == 0


def parse_pqr_charges(pqr_path):
    """
    Returns:
        charges_full[(chain, resseq, atomname)] = charge
        charges_nochain[(resseq, atomname)] = charge
        has_chain = bool
    """
    charges_full = {}
    charges_nochain = {}
    chain_values = set()

    with open(pqr_path) as f:
        for line in f:
            if not line.startswith(("ATOM", "HETATM")):
                continue
            try:
                atomname = line[12:16].strip()
                chain = line[21].strip()
                resseq = int(line[22:26].strip())
                charge = float(line[54:62].strip())
            except (ValueError, IndexError):
                continue

            chain_values.add(chain)
            charges_full[(chain, resseq, atomname)] = charge
            charges_nochain[(resseq, atomname)] = charge

    has_chain = any(c != "" for c in chain_values)
    return charges_full, charges_nochain, has_chain


def lookup_charge(chain, resseq, atomname, charges_full, charges_nochain, has_chain):
    # try chain-aware first
    if has_chain:
        val = charges_full.get((chain, resseq, atomname), None)
        if val is not None:
            return val

    # always try no-chain fallback too
    val = charges_nochain.get((resseq, atomname), None)
    if val is not None:
        return val

    return 0.0


def build_pqr_cache(full_pdb_dir, ph=7.4):
    full_pdb_dir = Path(full_pdb_dir)
    pdb_files = sorted(full_pdb_dir.glob("*.pdb"))

    pqr_cache = {}
    pqr_failures = []

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)

        for pdb_path in pdb_files:
            stem = pdb_path.stem
            match = re.match(r'([A-Za-z0-9]{4})', stem)
            if not match:
                pqr_failures.append(stem.upper())
                continue

            pdbid = match.group(1).upper()

            clean_pdb = tmpdir / f"{pdbid}_clean.pdb"
            pqr_out = tmpdir / f"{pdbid}.pqr"

            strip_dum_atoms(pdb_path, clean_pdb)

            ok = run_pdb2pqr(clean_pdb, pqr_out, ph=ph)
            if not ok or not pqr_out.exists():
                pqr_failures.append(pdbid)
                continue

            charges_full, charges_nochain, has_chain = parse_pqr_charges(pqr_out)
            pqr_cache[pdbid] = (charges_full, charges_nochain, has_chain)

    print(f"pdb2pqr complete: {len(pqr_cache)} ok, {len(pqr_failures)} failed")
    if pqr_failures:
        print("Failed PDB IDs:", pqr_failures[:20])

    return pqr_cache, set(pqr_failures)
def rdkit_coords_and_encoding(pdb_path, pdb_df, pqr_cache=None, output_dtype=np.float32):
    """
    Returns:
        coords: (N, 3) float32
        encoded_atoms: (N, 52) float32

    First 37 columns = atom subtype one-hot
    Remaining columns:
        37-39 = hybridization SP/SP2/SP3
        40    = partial_charge (from pdb2pqr)
        41    = is_in_ring
        42    = is_aromatic
        43-51 = residue groups
    """
    mol = Chem.MolFromPDBFile(pdb_path, removeHs=False, sanitize=False)
    if mol is None:
        print(f"[SKIP] RDKit could not parse: {pdb_path}")
        return None, None

    try:
        Chem.SanitizeMol(mol)
    except Exception:
        print(f"[WARN] RDKit sanitize warning for: {pdb_path}")

    conf = mol.GetConformer()

    # exclude hydrogens to match your filtered PDB usage
    heavy_atom_indices = [atom.GetIdx() for atom in mol.GetAtoms() if atom.GetAtomicNum() != 1]
    num_atoms = len(heavy_atom_indices)

    if len(pdb_df) != num_atoms:
        print(
            f"[WARNING] Atom count mismatch for {pdb_path}: "
            f"pdb_df has {len(pdb_df)} rows, RDKit non-H atoms has {num_atoms}"
        )
        return None, None

    subtype_one_hot = one_hot_encoding(pdb_df, dtype=np.int8)

    coords = np.zeros((num_atoms, 3), dtype=np.float32)
    encoded_atoms = np.zeros((num_atoms, ENCODING_SIZE), dtype=np.float32)
    encoded_atoms[:, :N_ATOM_SUBTYPE] = subtype_one_hot

    # guess pdb id from filename start, like 1ZHY-... or 1ZHY__...
    base_name = os.path.basename(pdb_path)
    match = re.match(r'([A-Za-z0-9]{4})', base_name)
    pdb_id = match.group(1).upper() if match else None

    charges_full, charges_nochain, has_chain = ({}, {}, False)
    if pqr_cache is not None and pdb_id in pqr_cache:
        charges_full, charges_nochain, has_chain = pqr_cache[pdb_id]

    write_i = 0
    for atom in mol.GetAtoms():
        if atom.GetAtomicNum() == 1:
            continue

        pos = conf.GetAtomPosition(atom.GetIdx())
        coords[write_i] = [pos.x, pos.y, pos.z]

        base = N_ATOM_SUBTYPE

        # hybridization
        hybridization = atom.GetHybridization()
        if hybridization == Chem.HybridizationType.SP:
            encoded_atoms[write_i, base + 0] = 1.0
        elif hybridization == Chem.HybridizationType.SP2:
            encoded_atoms[write_i, base + 1] = 1.0
        elif hybridization == Chem.HybridizationType.SP3:
            encoded_atoms[write_i, base + 2] = 1.0

        # residue / atom info for charge lookup
        pdb_info = atom.GetPDBResidueInfo()
        if pdb_info is not None:
            residue = pdb_info.GetResidueName().strip()
            atomname = pdb_info.GetName().strip()
            chain = (pdb_info.GetChainId() or "").strip()
            resseq = int(pdb_info.GetResidueNumber())
        else:
            residue = ""
            atomname = atom.GetSymbol()
            chain = ""
            resseq = -9999

        partial_charge = lookup_charge(
            chain, resseq, atomname,
            charges_full, charges_nochain, has_chain
        )

        # misc features
        encoded_atoms[write_i, base + 3] = float(partial_charge)
        encoded_atoms[write_i, base + 4] = 1.0 if atom.IsInRing() else 0.0
        encoded_atoms[write_i, base + 5] = 1.0 if atom.GetIsAromatic() else 0.0

        # residue grouping
        if residue in ['ASP', 'GLU']:
            encoded_atoms[write_i, base + 6] = 1.0
        elif residue in ['LYS', 'ARG']:
            encoded_atoms[write_i, base + 7] = 1.0
        elif residue == 'HIS':
            encoded_atoms[write_i, base + 8] = 1.0
        elif residue == 'CYS':
            encoded_atoms[write_i, base + 9] = 1.0
        elif residue in ['ASN', 'GLN', 'SER', 'THR']:
            encoded_atoms[write_i, base + 10] = 1.0
        elif residue == 'GLY':
            encoded_atoms[write_i, base + 11] = 1.0
        elif residue == 'PRO':
            encoded_atoms[write_i, base + 12] = 1.0
        elif residue in ['PHE', 'TYR', 'TRP']:
            encoded_atoms[write_i, base + 13] = 1.0
        elif residue in ['ALA', 'ILE', 'LEU', 'MET', 'VAL']:
            encoded_atoms[write_i, base + 14] = 1.0

        write_i += 1

    return coords.astype(np.float32), encoded_atoms.astype(output_dtype)

def compute_inverse_pairwise_distances_from_coords(coords):
    diff = coords[:, np.newaxis, :] - coords[np.newaxis, :, :]
    distances = np.sqrt(np.sum(diff ** 2, axis=-1))

    with np.errstate(divide='ignore'):
        inverse_distances = 1.0 / distances

    np.fill_diagonal(inverse_distances, 1.0)
    inverse_distances = np.minimum(inverse_distances, 1.0)

    return inverse_distances

In [ ]:
import pickle
import os

cache_path = "pqr_cache.pkl"
FULL_PDB_DIR = "/home/alexhernandez/CholBindNet/GNN/CLR-PDB"   # change this

if os.path.exists(cache_path):
    with open(cache_path, "rb") as f:
        data = pickle.load(f)
        pqr_cache = data["pqr_cache"]
        pqr_failures = data["pqr_failures"]

    print(f"Loaded PQR cache from {cache_path}")
    print(f"Cached PDBs: {len(pqr_cache)}")
else:
    print("Cache not found, rebuilding...")
    pqr_cache, pqr_failures = build_pqr_cache(FULL_PDB_DIR, ph=PDB2PQR_PH)

pdb2pqr complete: 763 ok, 7 failed
Failed PDB IDs: ['6IIV', '6WGT', '6WH4', '8JCW', '8JCY', '8SR9', '8SRA']

In [ ]:
# import pickle

# cache_path = "pqr_cache.pkl"

# with open(cache_path, "wb") as f:
#     pickle.dump({
#         "pqr_cache": pqr_cache,
#         "pqr_failures": pqr_failures
#     }, f)

# print(f"Saved PQR cache to {cache_path}")

Saved PQR cache to pqr_cache.pkl

In [11]:
print("num cached pdbs:", len(pqr_cache))
print("num failures:", len(pqr_failures))

example_key = next(iter(pqr_cache))
print("example pdb id:", example_key)

charges_full, charges_nochain, has_chain = pqr_cache[example_key]
print("has_chain:", has_chain)
print("num full charge entries:", len(charges_full))
print("num no-chain charge entries:", len(charges_nochain))

print("sample full keys:", list(charges_full.items())[:10])
print("sample no-chain keys:", list(charges_nochain.items())[:10])

num cached pdbs: 763
num failures: 7
example pdb id: 1LRI
has_chain: False
num full charge entries: 1432
num no-chain charge entries: 1432
sample full keys: [(('', 1, 'N'), 0.1812), (('', 1, 'CA'), 0.0034), (('', 1, 'C'), 0.6163), (('', 1, 'O'), -0.5722), (('', 1, 'CB'), 0.4514), (('', 1, 'OG1'), -0.6764), (('', 1, 'CG2'), -0.2554), (('', 1, 'H'), 0.1934), (('', 1, 'HA'), 0.1087), (('', 1, 'HB'), -0.0323)]
sample no-chain keys: [((1, 'N'), 0.1812), ((1, 'CA'), 0.0034), ((1, 'C'), 0.6163), ((1, 'O'), -0.5722), ((1, 'CB'), 0.4514), ((1, 'OG1'), -0.6764), ((1, 'CG2'), -0.2554), ((1, 'H'), 0.1934), ((1, 'HA'), 0.1087), ((1, 'HB'), -0.0323)]

In [12]:
max_atoms = 200
# positives
output_dir = "cholesterol-rdkit-fpocket-5A/positive"
os.makedirs(output_dir, exist_ok=True)

positive_files = glob.glob("filtered-rdkit-fpocket-5A/positive/*.pdb")
positive_files = sorted(positive_files, key=natural_sort_key)

for file in positive_files:
    pdb_df = pdb_to_dataframe(file)
    coords, encoded_matrix = rdkit_coords_and_encoding(file, pdb_df, pqr_cache=pqr_cache)
    if coords is None or encoded_matrix is None:
        print(f"[SKIP] Failed encoding for {file}")
        continue
    inverse_distance = compute_inverse_pairwise_distances_from_coords(coords)

    if inverse_distance.shape[0] != encoded_matrix.shape[0]:
        raise ValueError(
            f"Atom mismatch in {file}: "
            f"inverse_distance={inverse_distance.shape}, "
            f"encoded_matrix={encoded_matrix.shape}"
        )

    combined_matrix = inverse_distance @ encoded_matrix

    num_atoms = inverse_distance.shape[0]

    if num_atoms > max_atoms:
        print(f"{file} has {num_atoms} atoms, exceeding the limit of {max_atoms}")
        raise Exception("Too many atoms!")

    combined_matrix = np.pad(
        combined_matrix,
        ((0, max_atoms - num_atoms), (0, 0)),
        mode='constant'
    )

    base_name = os.path.splitext(os.path.basename(file))[0]
    output_path = os.path.join(output_dir, f"{base_name}_combined_matrix.npy")
    np.save(output_path, combined_matrix)

    #print(f"Saved: {output_path}")

[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/positive/5NM4-filtered.pdb: pdb_df has 72 rows, RDKit non-H atoms has 67
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/positive/5NM4-filtered.pdb

In [13]:
max_atoms = 200
# unlabeleds
output_dir = "cholesterol-rdkit-fpocket-5A/unlabeled"
os.makedirs(output_dir, exist_ok=True)

unlabeled_files = glob.glob("filtered-rdkit-fpocket-5A/unlabeled/*.pdb")
unlabeled_files = sorted(unlabeled_files, key=natural_sort_key)

for file in unlabeled_files:
    pdb_df = pdb_to_dataframe(file)
    coords, encoded_matrix = rdkit_coords_and_encoding(file, pdb_df, pqr_cache=pqr_cache)
    if coords is None or encoded_matrix is None:
        print(f"[SKIP] Failed encoding for {file}")
        continue
    inverse_distance = compute_inverse_pairwise_distances_from_coords(coords)

    if inverse_distance.shape[0] != encoded_matrix.shape[0]:
        raise ValueError(
            f"Atom mismatch in {file}: "
            f"inverse_distance={inverse_distance.shape}, "
            f"encoded_matrix={encoded_matrix.shape}"
        )

    combined_matrix = inverse_distance @ encoded_matrix

    num_atoms = inverse_distance.shape[0]

    if num_atoms > max_atoms:
        print(f"{file} has {num_atoms} atoms, exceeding the limit of {max_atoms}")
        #raise Exception("Too many atoms!")
        continue

    combined_matrix = np.pad(
        combined_matrix,
        ((0, max_atoms - num_atoms), (0, 0)),
        mode='constant'
    )

    base_name = os.path.splitext(os.path.basename(file))[0]
    output_path = os.path.join(output_dir, f"{base_name}_combined_matrix.npy")
    np.save(output_path, combined_matrix)

    #print(f"Saved: {output_path}")

filtered-rdkit-fpocket-5A/unlabeled/2RH1-p35.pdb has 290 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/3A3Y-p96.pdb has 254 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/3AM6-p69.pdb has 283 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/3D4S-p35.pdb has 201 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/3NY9-p38.pdb has 230 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/3NYA-p11.pdb has 274 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/3NYA-p20.pdb has 222 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/3WGU-p85.pdb has 216 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/3WGV-p88.pdb has 241 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4BOE-p1.pdb: pdb_df has 316 rows, RDKit non-H atoms has 313
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4BOE-p1.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4BOE-p6.pdb: pdb_df has 22 rows, RDKit non-H atoms has 19
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4BOE-p6.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4BQU-p1-positive.pdb: pdb_df has 234 rows, RDKit non-H atoms has 231
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4BQU-p1-positive.pdb
filtered-rdkit-fpocket-5A/unlabeled/4BQU-p2-positive.pdb has 234 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4BQU-p5.pdb: pdb_df has 54 rows, RDKit non-H atoms has 45
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4BQU-p5.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4EIY-p6.pdb: pdb_df has 83 rows, RDKit non-H atoms has 72
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4EIY-p6.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4EIY-p7.pdb: pdb_df has 79 rows, RDKit non-H atoms has 60
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4EIY-p7.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4EIY-p17.pdb: pdb_df has 46 rows, RDKit non-H atoms has 38
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4EIY-p17.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4EIY-p18.pdb: pdb_df has 95 rows, RDKit non-H atoms has 89
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4EIY-p18.pdb
filtered-rdkit-fpocket-5A/unlabeled/4HYT-p1.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/4HYT-p182.pdb has 206 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/4NC3-p18.pdb has 263 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4OR2-p25.pdb: pdb_df has 44 rows, RDKit non-H atoms has 33
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4OR2-p25.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4PXZ-p24.pdb: pdb_df has 61 rows, RDKit non-H atoms has 54
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4PXZ-p24.pdb
filtered-rdkit-fpocket-5A/unlabeled/4RES-p16.pdb has 243 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/4RES-p139.pdb has 243 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/4RES-p200.pdb has 265 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/4RES-p218.pdb has 245 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4XNU-p4.pdb: pdb_df has 121 rows, RDKit non-H atoms has 113
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4XNU-p4.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4XNU-p31.pdb: pdb_df has 51 rows, RDKit non-H atoms has 43
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4XNU-p31.pdb
filtered-rdkit-fpocket-5A/unlabeled/4XP5-p5.pdb has 275 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4XP6-p11.pdb: pdb_df has 45 rows, RDKit non-H atoms has 40
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4XP6-p11.pdb
filtered-rdkit-fpocket-5A/unlabeled/4XP9-p35.pdb has 258 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/4XPB-p3.pdb has 205 atoms, exceeding the limit of 200

[11:11:57] Explicit valence for atom # 51 C, 5, is greater than permitted

[WARN] RDKit sanitize warning for: filtered-rdkit-fpocket-5A/unlabeled/4XPF-p50.pdb

[11:11:58] Explicit valence for atom # 40 O, 3, is greater than permitted

[WARN] RDKit sanitize warning for: filtered-rdkit-fpocket-5A/unlabeled/4XPG-p38.pdb
filtered-rdkit-fpocket-5A/unlabeled/4XPH-p3.pdb has 207 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/4XPH-p6.pdb: pdb_df has 46 rows, RDKit non-H atoms has 41
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/4XPH-p6.pdb
filtered-rdkit-fpocket-5A/unlabeled/4XPH-p47.pdb has 218 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/4XPT-p38.pdb has 577 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5C1M-p9.pdb: pdb_df has 59 rows, RDKit non-H atoms has 51
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5C1M-p9.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5C1M-p15.pdb: pdb_df has 54 rows, RDKit non-H atoms has 43
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5C1M-p15.pdb
filtered-rdkit-fpocket-5A/unlabeled/5D5A-p28.pdb has 245 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/5D6L-p32.pdb has 276 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/5I6X-p4.pdb has 317 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/5I71-p1.pdb has 379 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/5I73-p23.pdb has 391 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/5I75-p70.pdb has 275 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU4-p1.pdb: pdb_df has 176 rows, RDKit non-H atoms has 160
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU4-p1.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU4-p2.pdb: pdb_df has 67 rows, RDKit non-H atoms has 59
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU4-p2.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU4-p12.pdb: pdb_df has 67 rows, RDKit non-H atoms has 61
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU4-p12.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU4-p15.pdb: pdb_df has 71 rows, RDKit non-H atoms has 60
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU4-p15.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU4-p16.pdb: pdb_df has 33 rows, RDKit non-H atoms has 28
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU4-p16.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU4-p22.pdb: pdb_df has 113 rows, RDKit non-H atoms has 99
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU4-p22.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU7-p3.pdb: pdb_df has 74 rows, RDKit non-H atoms has 66
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU7-p3.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU7-p7.pdb: pdb_df has 144 rows, RDKit non-H atoms has 136
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU7-p7.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU7-p9.pdb: pdb_df has 77 rows, RDKit non-H atoms has 71
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU7-p9.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU7-p14.pdb: pdb_df has 60 rows, RDKit non-H atoms has 52
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU7-p14.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU7-p24.pdb: pdb_df has 103 rows, RDKit non-H atoms has 89
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU7-p24.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU8-p3-positive.pdb: pdb_df has 50 rows, RDKit non-H atoms has 44
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU8-p3-positive.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU8-p8.pdb: pdb_df has 72 rows, RDKit non-H atoms has 66
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU8-p8.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU8-p18.pdb: pdb_df has 26 rows, RDKit non-H atoms has 20
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU8-p18.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IU8-p21.pdb: pdb_df has 66 rows, RDKit non-H atoms has 60
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IU8-p21.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IUA-p1.pdb: pdb_df has 185 rows, RDKit non-H atoms has 177
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IUA-p1.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IUA-p5.pdb: pdb_df has 69 rows, RDKit non-H atoms has 63
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IUA-p5.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IUA-p24.pdb: pdb_df has 109 rows, RDKit non-H atoms has 96
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IUA-p24.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p1.pdb: pdb_df has 133 rows, RDKit non-H atoms has 125
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p1.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p3.pdb: pdb_df has 119 rows, RDKit non-H atoms has 111
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p3.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p6.pdb: pdb_df has 58 rows, RDKit non-H atoms has 52
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p6.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p8.pdb: pdb_df has 33 rows, RDKit non-H atoms has 28
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p8.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p17.pdb: pdb_df has 66 rows, RDKit non-H atoms has 58
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p17.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p20.pdb: pdb_df has 40 rows, RDKit non-H atoms has 29
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p20.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p21.pdb: pdb_df has 71 rows, RDKit non-H atoms has 60
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p21.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p25.pdb: pdb_df has 81 rows, RDKit non-H atoms has 75
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p25.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p28.pdb: pdb_df has 45 rows, RDKit non-H atoms has 38
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5IUB-p28.pdb
filtered-rdkit-fpocket-5A/unlabeled/5JQH-p36.pdb has 204 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/5JQH-p68.pdb has 230 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5JTB-p11.pdb: pdb_df has 51 rows, RDKit non-H atoms has 46
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5JTB-p11.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5JTB-p13.pdb: pdb_df has 87 rows, RDKit non-H atoms has 79
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5JTB-p13.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5JTB-p22.pdb: pdb_df has 81 rows, RDKit non-H atoms has 70
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5JTB-p22.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2A-p3.pdb: pdb_df has 96 rows, RDKit non-H atoms has 88
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2A-p3.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2A-p6.pdb: pdb_df has 74 rows, RDKit non-H atoms has 66
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2A-p6.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2A-p21.pdb: pdb_df has 48 rows, RDKit non-H atoms has 40
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2A-p21.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2B-p3.pdb: pdb_df has 59 rows, RDKit non-H atoms has 51
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2B-p3.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2B-p12.pdb: pdb_df has 86 rows, RDKit non-H atoms has 78
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2B-p12.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2B-p20.pdb: pdb_df has 51 rows, RDKit non-H atoms has 40
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2B-p20.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2B-p28.pdb: pdb_df has 170 rows, RDKit non-H atoms has 143
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2B-p28.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p4.pdb: pdb_df has 74 rows, RDKit non-H atoms has 66
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p4.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p5.pdb: pdb_df has 83 rows, RDKit non-H atoms has 72
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p5.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p6.pdb: pdb_df has 71 rows, RDKit non-H atoms has 63
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p6.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p13.pdb: pdb_df has 28 rows, RDKit non-H atoms has 21
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p13.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p16.pdb: pdb_df has 48 rows, RDKit non-H atoms has 40
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p16.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p20.pdb: pdb_df has 57 rows, RDKit non-H atoms has 38
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p20.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p22.pdb: pdb_df has 45 rows, RDKit non-H atoms has 38
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2C-p22.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2D-p4.pdb: pdb_df has 59 rows, RDKit non-H atoms has 51
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2D-p4.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2D-p6.pdb: pdb_df has 56 rows, RDKit non-H atoms has 48
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2D-p6.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2D-p7.pdb: pdb_df has 102 rows, RDKit non-H atoms has 91
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2D-p7.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2D-p12.pdb: pdb_df has 28 rows, RDKit non-H atoms has 21
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2D-p12.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5K2D-p15.pdb: pdb_df has 51 rows, RDKit non-H atoms has 40
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5K2D-p15.pdb
filtered-rdkit-fpocket-5A/unlabeled/5L7D-p3.pdb has 268 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/5L7D-p113.pdb has 231 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5LWE-p12.pdb: pdb_df has 40 rows, RDKit non-H atoms has 35
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5LWE-p12.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5LWE-p41.pdb: pdb_df has 43 rows, RDKit non-H atoms has 38
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5LWE-p41.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5MZJ-p10.pdb: pdb_df has 55 rows, RDKit non-H atoms has 41
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5MZJ-p10.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5MZJ-p13.pdb: pdb_df has 110 rows, RDKit non-H atoms has 104
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5MZJ-p13.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5MZJ-p14.pdb: pdb_df has 78 rows, RDKit non-H atoms has 59
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5MZJ-p14.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5MZJ-p15.pdb: pdb_df has 71 rows, RDKit non-H atoms has 60
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5MZJ-p15.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5MZP-p14.pdb: pdb_df has 55 rows, RDKit non-H atoms has 41
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5MZP-p14.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5MZP-p27.pdb: pdb_df has 45 rows, RDKit non-H atoms has 38
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5MZP-p27.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5NLX-p8.pdb: pdb_df has 47 rows, RDKit non-H atoms has 43
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5NLX-p8.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5NLX-p21.pdb: pdb_df has 56 rows, RDKit non-H atoms has 52
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5NLX-p21.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5NM2-p1.pdb: pdb_df has 188 rows, RDKit non-H atoms has 180
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5NM2-p1.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5NM2-p6.pdb: pdb_df has 74 rows, RDKit non-H atoms has 66
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5NM2-p6.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5NM2-p8.pdb: pdb_df has 47 rows, RDKit non-H atoms has 36
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5NM2-p8.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5NM2-p11.pdb: pdb_df has 66 rows, RDKit non-H atoms has 55
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5NM2-p11.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5NM2-p16.pdb: pdb_df has 72 rows, RDKit non-H atoms has 66
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5NM2-p16.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5NM2-p22.pdb: pdb_df has 132 rows, RDKit non-H atoms has 111
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5NM2-p22.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5NM4-p13.pdb: pdb_df has 107 rows, RDKit non-H atoms has 103
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5NM4-p13.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OLG-p10.pdb: pdb_df has 55 rows, RDKit non-H atoms has 41
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OLG-p10.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OLG-p11.pdb: pdb_df has 110 rows, RDKit non-H atoms has 104
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OLG-p11.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OLG-p15.pdb: pdb_df has 71 rows, RDKit non-H atoms has 60
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OLG-p15.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OLH-p7.pdb: pdb_df has 54 rows, RDKit non-H atoms has 43
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OLH-p7.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OLV-p10.pdb: pdb_df has 67 rows, RDKit non-H atoms has 61
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OLV-p10.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OLV-p14.pdb: pdb_df has 48 rows, RDKit non-H atoms has 34
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OLV-p14.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OLZ-p3.pdb: pdb_df has 89 rows, RDKit non-H atoms has 81
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OLZ-p3.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OLZ-p7.pdb: pdb_df has 55 rows, RDKit non-H atoms has 41
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OLZ-p7.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OLZ-p9.pdb: pdb_df has 77 rows, RDKit non-H atoms has 66
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OLZ-p9.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OLZ-p10.pdb: pdb_df has 43 rows, RDKit non-H atoms has 37
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OLZ-p10.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OLZ-p20.pdb: pdb_df has 79 rows, RDKit non-H atoms has 72
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OLZ-p20.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OM1-p21.pdb: pdb_df has 48 rows, RDKit non-H atoms has 34
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OM1-p21.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OM1-p26.pdb: pdb_df has 51 rows, RDKit non-H atoms has 45
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OM1-p26.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OM4-p15.pdb: pdb_df has 48 rows, RDKit non-H atoms has 34
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OM4-p15.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5OM4-p26.pdb: pdb_df has 46 rows, RDKit non-H atoms has 32
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5OM4-p26.pdb
filtered-rdkit-fpocket-5A/unlabeled/5TVN-p1.pdb has 237 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/5UPH-p1-positive.pdb has 360 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/5UPH-p2-positive.pdb has 355 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5VRA-p5.pdb: pdb_df has 167 rows, RDKit non-H atoms has 160
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5VRA-p5.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5VRA-p8.pdb: pdb_df has 91 rows, RDKit non-H atoms has 66
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5VRA-p8.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5VRA-p11.pdb: pdb_df has 43 rows, RDKit non-H atoms has 40
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5VRA-p11.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5VRA-p13.pdb: pdb_df has 32 rows, RDKit non-H atoms has 24
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5VRA-p13.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5VRA-p17.pdb: pdb_df has 66 rows, RDKit non-H atoms has 55
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5VRA-p17.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/5VRA-p21.pdb: pdb_df has 95 rows, RDKit non-H atoms has 89
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/5VRA-p21.pdb

[11:12:52] Explicit valence for atom # 18 O, 3, is greater than permitted

filtered-rdkit-fpocket-5A/unlabeled/6WBF-p21.pdb has 343 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBF-p140.pdb has 260 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBF-p141.pdb has 260 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBF-p143.pdb has 260 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBF-p144.pdb has 260 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBF-p145.pdb has 260 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBF-p146.pdb has 260 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBF-p147.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBF-p148.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBF-p149.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBF-p150.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBF-p151.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBF-p152.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBF-p153.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p140.pdb has 260 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p141.pdb has 260 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p142.pdb has 265 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p144.pdb has 265 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p145.pdb has 260 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p146.pdb has 260 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p147.pdb has 260 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p148.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p149.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p150.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p151.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p152.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p153.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBG-p154.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBM-p134.pdb has 219 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBM-p155.pdb has 219 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBM-p158.pdb has 230 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBM-p159.pdb has 219 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBM-p169.pdb has 219 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBM-p172.pdb has 219 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p261.pdb has 462 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p280.pdb has 471 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p289.pdb has 462 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p310.pdb has 462 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p315.pdb has 462 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p316.pdb has 471 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p334.pdb has 471 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p341.pdb has 233 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p349.pdb has 233 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p351.pdb has 284 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p357.pdb has 398 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p358.pdb has 418 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p359.pdb has 427 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WBN-p360.pdb has 422 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WGT-p3.pdb has 237 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WH4-p24.pdb has 319 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WH4-p52.pdb has 309 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WH4-p54.pdb has 254 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WH4-p63.pdb has 233 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WIV-p72.pdb has 218 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WIV-p83.pdb has 273 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WIV-p88.pdb has 237 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WLW-p125.pdb has 208 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WLW-p191.pdb has 243 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p1.pdb has 905 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p2.pdb has 430 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p625.pdb has 250 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p636.pdb has 229 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p650.pdb has 207 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p651.pdb has 203 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p652.pdb has 273 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p653.pdb has 231 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p665.pdb has 215 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p666.pdb has 225 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p668.pdb has 294 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p669.pdb has 483 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p670.pdb has 417 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/6WM2-p671.pdb has 310 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/6WQA-p26.pdb: pdb_df has 80 rows, RDKit non-H atoms has 74
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/6WQA-p26.pdb
filtered-rdkit-fpocket-5A/unlabeled/6XBK-p1.pdb has 208 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/6ZDR-p7.pdb: pdb_df has 52 rows, RDKit non-H atoms has 41
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/6ZDR-p7.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/6ZDR-p11.pdb: pdb_df has 77 rows, RDKit non-H atoms has 69
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/6ZDR-p11.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/6ZDR-p14.pdb: pdb_df has 50 rows, RDKit non-H atoms has 43
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/6ZDR-p14.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/6ZDR-p17.pdb: pdb_df has 86 rows, RDKit non-H atoms has 83
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/6ZDR-p17.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/6ZDV-p1.pdb: pdb_df has 184 rows, RDKit non-H atoms has 179
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/6ZDV-p1.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/6ZDV-p16.pdb: pdb_df has 23 rows, RDKit non-H atoms has 20
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/6ZDV-p16.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/6ZDV-p21.pdb: pdb_df has 25 rows, RDKit non-H atoms has 22
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/6ZDV-p21.pdb
filtered-rdkit-fpocket-5A/unlabeled/7A69-p55.pdb has 398 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7A69-p119.pdb has 223 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7A69-p121.pdb has 219 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7BU7-p8.pdb has 208 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7BU7-p16.pdb has 231 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7BVQ-p1.pdb has 288 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7BVQ-p24.pdb has 232 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7BVQ-p65.pdb has 252 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7CFN-p8.pdb: pdb_df has 86 rows, RDKit non-H atoms has 78
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7CFN-p8.pdb
filtered-rdkit-fpocket-5A/unlabeled/7CFN-p30.pdb has 246 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7CFN-p44.pdb: pdb_df has 60 rows, RDKit non-H atoms has 46
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7CFN-p44.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7CFN-p56.pdb: pdb_df has 50 rows, RDKit non-H atoms has 44
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7CFN-p56.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7CFN-p62.pdb: pdb_df has 279 rows, RDKit non-H atoms has 273
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7CFN-p62.pdb
filtered-rdkit-fpocket-5A/unlabeled/7CKW-p2.pdb has 261 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7CKZ-p67.pdb has 283 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7CU3-p2.pdb: pdb_df has 128 rows, RDKit non-H atoms has 115
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7CU3-p2.pdb
filtered-rdkit-fpocket-5A/unlabeled/7D8X-p107.pdb has 226 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7D76-p4.pdb: pdb_df has 50 rows, RDKit non-H atoms has 40
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7D76-p4.pdb
filtered-rdkit-fpocket-5A/unlabeled/7D76-p15.pdb has 230 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7D77-p57.pdb has 238 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7DDH-p32.pdb has 218 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7DDH-p200.pdb has 324 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7DDL-p185.pdb has 268 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7DF8-p15.pdb has 233 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7DFW-p62.pdb has 206 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7DRT-p69.pdb has 419 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7E2X-p34.pdb has 212 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7E2Y-p13.pdb has 285 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7E2Z-p48.pdb has 278 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7E2Z-p51.pdb has 229 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7E14-p1.pdb has 320 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7E14-p52.pdb has 243 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7EJX-p13.pdb has 242 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7EJX-p64.pdb has 248 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKI-p55.pdb: pdb_df has 186 rows, RDKit non-H atoms has 179
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKI-p55.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKI-p100.pdb: pdb_df has 179 rows, RDKit non-H atoms has 172
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKI-p100.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKI-p102.pdb: pdb_df has 186 rows, RDKit non-H atoms has 179
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKI-p102.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKI-p129.pdb: pdb_df has 186 rows, RDKit non-H atoms has 179
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKI-p129.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKI-p141.pdb: pdb_df has 186 rows, RDKit non-H atoms has 179
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKI-p141.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKP-p4.pdb: pdb_df has 80 rows, RDKit non-H atoms has 73
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKP-p4.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKP-p5.pdb: pdb_df has 85 rows, RDKit non-H atoms has 78
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKP-p5.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKP-p31.pdb: pdb_df has 80 rows, RDKit non-H atoms has 73
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKP-p31.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKP-p33.pdb: pdb_df has 74 rows, RDKit non-H atoms has 67
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKP-p33.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKP-p69.pdb: pdb_df has 80 rows, RDKit non-H atoms has 73
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKP-p69.pdb
filtered-rdkit-fpocket-5A/unlabeled/7EKP-p104.pdb has 262 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7EKP-p113.pdb has 262 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7EKP-p118.pdb has 297 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7EKP-p127.pdb has 262 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7EKP-p128.pdb has 262 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p38.pdb: pdb_df has 70 rows, RDKit non-H atoms has 63
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p38.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p42.pdb: pdb_df has 70 rows, RDKit non-H atoms has 63
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p42.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p43.pdb: pdb_df has 70 rows, RDKit non-H atoms has 63
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p43.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p87.pdb: pdb_df has 37 rows, RDKit non-H atoms has 30
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p87.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p89.pdb: pdb_df has 70 rows, RDKit non-H atoms has 63
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p89.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p102.pdb: pdb_df has 37 rows, RDKit non-H atoms has 30
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p102.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p104.pdb: pdb_df has 37 rows, RDKit non-H atoms has 30
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p104.pdb
filtered-rdkit-fpocket-5A/unlabeled/7EKT-p116.pdb has 301 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p117.pdb: pdb_df has 37 rows, RDKit non-H atoms has 30
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p117.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p119.pdb: pdb_df has 70 rows, RDKit non-H atoms has 63
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p119.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p127.pdb: pdb_df has 37 rows, RDKit non-H atoms has 30
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7EKT-p127.pdb
filtered-rdkit-fpocket-5A/unlabeled/7EKT-p159.pdb has 257 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7EKT-p177.pdb has 257 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7EKT-p178.pdb has 265 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7EKT-p179.pdb has 257 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7F9Y-p71.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7F61-p3.pdb has 245 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7FDV-p71.pdb has 338 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7FEE-p1.pdb has 227 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7FEE-p2.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7FIN-p34.pdb has 291 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7FJD-p1.pdb has 272 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7FJD-p92.pdb has 202 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7FJE-p1.pdb has 277 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7FJE-p92.pdb has 402 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7JV5-p95.pdb has 221 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7JVP-p78.pdb has 240 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7JVQ-p77.pdb has 256 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7JVQ-p81.pdb has 202 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7JVQ-p82.pdb has 211 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7KY7-p2.pdb has 212 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7KY7-p76.pdb has 440 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LFT-p100.pdb has 344 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LFT-p118.pdb has 344 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LFT-p119.pdb has 344 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LFT-p121.pdb has 344 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LGW-p72.pdb has 336 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LH2-p84.pdb has 240 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LIA-p5.pdb has 248 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LJC-p2.pdb has 248 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LJC-p17.pdb has 210 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LJC-p78.pdb has 264 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LJC-p82.pdb has 218 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LJD-p12.pdb has 218 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LKP-p4.pdb has 278 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7LKP-p152.pdb has 239 atoms, exceeding the limit of 200

[11:13:44] Explicit valence for atom # 100 O, 3, is greater than permitted

filtered-rdkit-fpocket-5A/unlabeled/7NEQ-p104.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7NF6-p57.pdb has 314 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7NF6-p58.pdb has 334 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7NF8-p56.pdb has 322 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7NF8-p57.pdb has 334 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7OCA-p144.pdb has 277 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7OCA-p228.pdb has 320 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7OCA-p253.pdb has 320 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7OCA-p290.pdb has 311 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7OCE-p78.pdb has 277 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7OCE-p171.pdb has 311 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7OJ8-p90.pdb has 330 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7OJH-p3.pdb has 232 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7OJI-p95.pdb has 338 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7OJI-p96.pdb has 282 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXE-p11.pdb has 226 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXE-p56.pdb has 266 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXE-p114.pdb has 266 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXE-p118.pdb has 266 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXE-p210.pdb has 266 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXE-p236.pdb has 226 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXE-p283.pdb has 233 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXE-p284.pdb has 226 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXE-p285.pdb has 226 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXE-p288.pdb has 233 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXE-p289.pdb has 233 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXE-p290.pdb has 233 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXG-p9.pdb has 202 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXG-p78.pdb has 202 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXG-p152.pdb has 202 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXG-p159.pdb has 202 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXH-p269.pdb has 227 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXH-p274.pdb has 256 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXH-p276.pdb has 337 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7PXH-p277.pdb has 337 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7Q1U-p2.pdb has 381 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7R8A-p96.pdb has 208 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7R8A-p97.pdb has 209 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7R8B-p66.pdb has 304 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7R8B-p80.pdb has 201 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7R8D-p1.pdb has 316 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7R8D-p41.pdb has 246 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7RHR-p1.pdb has 510 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7SHE-p1.pdb has 270 atoms, exceeding the limit of 200

[11:13:59] Explicit valence for atom # 19 O, 3, is greater than permitted

[WARN] RDKit sanitize warning for: filtered-rdkit-fpocket-5A/unlabeled/7SHE-p42.pdb
filtered-rdkit-fpocket-5A/unlabeled/7SHE-p81.pdb has 214 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7SHE-p89.pdb has 223 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7SHF-p86.pdb: pdb_df has 47 rows, RDKit non-H atoms has 36
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7SHF-p86.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7SHF-p87.pdb: pdb_df has 83 rows, RDKit non-H atoms has 72
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7SHF-p87.pdb
filtered-rdkit-fpocket-5A/unlabeled/7SHF-p108.pdb has 253 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7SIL-p87.pdb has 209 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7SIL-p91.pdb has 206 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7SIL-p92.pdb has 313 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7SIL-p95.pdb has 326 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7SIL-p96.pdb has 326 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7SIM-p92.pdb has 283 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7SIM-p108.pdb has 262 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7SK4-p1.pdb has 204 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7SK7-p7.pdb: pdb_df has 161 rows, RDKit non-H atoms has 154
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7SK7-p7.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7SK8-p35.pdb: pdb_df has 77 rows, RDKit non-H atoms has 70
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7SK8-p35.pdb
filtered-rdkit-fpocket-5A/unlabeled/7SMS-p150.pdb has 238 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7SVD-p68.pdb has 225 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7SVD-p87.pdb has 983 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7SVD-p89.pdb has 207 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7T92-p6.pdb: pdb_df has 110 rows, RDKit non-H atoms has 106
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7T92-p6.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7T92-p18.pdb: pdb_df has 61 rows, RDKit non-H atoms has 58
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7T92-p18.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7T92-p40.pdb: pdb_df has 32 rows, RDKit non-H atoms has 29
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7T92-p40.pdb
filtered-rdkit-fpocket-5A/unlabeled/7TAI-p37.pdb has 240 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TAI-p39.pdb has 240 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TAI-p59.pdb has 270 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TAI-p77.pdb has 270 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TAI-p79.pdb has 240 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TAI-p81.pdb has 270 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TAI-p82.pdb has 266 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TAI-p83.pdb has 266 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TAI-p84.pdb has 266 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TAI-p85.pdb has 231 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TAI-p86.pdb has 231 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TAI-p87.pdb has 223 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TBW-p160.pdb has 320 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TC0-p77.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TC0-p141.pdb has 204 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TC0-p151.pdb has 232 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TJ8-p64.pdb has 264 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TJ9-p131.pdb has 205 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TY7-p38.pdb has 204 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TY7-p50.pdb has 204 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TY8-p33.pdb has 426 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TY8-p39.pdb has 201 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TY8-p40.pdb has 201 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TYA-p61.pdb has 223 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7TYA-p62.pdb has 223 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7UHG-p1.pdb has 311 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7UHG-p2.pdb has 317 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7UHG-p202.pdb has 234 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7UHG-p203.pdb has 242 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7URA-p45.pdb has 228 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7URD-p32.pdb has 319 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7USW-p26.pdb has 372 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7USW-p115.pdb has 293 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7USW-p122.pdb has 282 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7USX-p76.pdb has 308 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7USX-p101.pdb has 310 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7UZE-p1.pdb has 236 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7UZE-p11.pdb: pdb_df has 82 rows, RDKit non-H atoms has 71
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7UZE-p11.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7UZQ-p17.pdb: pdb_df has 49 rows, RDKit non-H atoms has 37
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7UZQ-p17.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7UZQ-p26.pdb: pdb_df has 54 rows, RDKit non-H atoms has 42
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7UZQ-p26.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7UZQ-p46.pdb: pdb_df has 81 rows, RDKit non-H atoms has 69
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7UZQ-p46.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7UZQ-p65.pdb: pdb_df has 68 rows, RDKit non-H atoms has 56
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7UZQ-p65.pdb
filtered-rdkit-fpocket-5A/unlabeled/7V0K-p6.pdb has 446 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7V0K-p135.pdb: pdb_df has 72 rows, RDKit non-H atoms has 60
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7V0K-p135.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7V0K-p191.pdb: pdb_df has 81 rows, RDKit non-H atoms has 69
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7V0K-p191.pdb
filtered-rdkit-fpocket-5A/unlabeled/7V0K-p240.pdb has 245 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7V0K-p244.pdb has 268 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7V0S-p1.pdb: pdb_df has 110 rows, RDKit non-H atoms has 98
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7V0S-p1.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7V0S-p17.pdb: pdb_df has 81 rows, RDKit non-H atoms has 69
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7V0S-p17.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7V0S-p33.pdb: pdb_df has 78 rows, RDKit non-H atoms has 66
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7V0S-p33.pdb
filtered-rdkit-fpocket-5A/unlabeled/7V62-p1-positive.pdb has 216 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7V62-p2.pdb has 812 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7V62-p3-positive.pdb has 221 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7V62-p4-positive.pdb has 202 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7V62-p105.pdb has 235 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7V62-p106.pdb has 205 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7V62-p108.pdb has 322 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7VAB-p68.pdb has 285 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7VAB-p82.pdb has 234 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7VDH-p5.pdb has 302 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7VLA-p10.pdb: pdb_df has 50 rows, RDKit non-H atoms has 38
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7VLA-p10.pdb
filtered-rdkit-fpocket-5A/unlabeled/7VOD-p1.pdb has 268 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7VOE-p3.pdb has 372 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7VUY-p19.pdb has 276 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7W9W-p1.pdb: pdb_df has 138 rows, RDKit non-H atoms has 135
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7W9W-p1.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7W9W-p11.pdb: pdb_df has 38 rows, RDKit non-H atoms has 30
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7W9W-p11.pdb
filtered-rdkit-fpocket-5A/unlabeled/7WC4-p4.pdb has 313 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WC5-p8.pdb has 419 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WC6-p2.pdb has 277 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WC7-p1.pdb has 223 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WC8-p2.pdb has 338 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WC9-p1.pdb has 361 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WE4-p38.pdb has 301 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7WE4-p65.pdb: pdb_df has 45 rows, RDKit non-H atoms has 35
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7WE4-p65.pdb
filtered-rdkit-fpocket-5A/unlabeled/7WEL-p1.pdb has 288 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7WEL-p103.pdb: pdb_df has 66 rows, RDKit non-H atoms has 56
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7WEL-p103.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7WFR-p74.pdb: pdb_df has 67 rows, RDKit non-H atoms has 57
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7WFR-p74.pdb
filtered-rdkit-fpocket-5A/unlabeled/7WFR-p78.pdb has 214 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7WFW-p28.pdb: pdb_df has 64 rows, RDKit non-H atoms has 54
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7WFW-p28.pdb
filtered-rdkit-fpocket-5A/unlabeled/7WFW-p70.pdb has 230 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WFW-p90.pdb has 282 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WLD-p3.pdb has 274 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WLD-p8.pdb has 213 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WLD-p153.pdb has 275 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WLD-p184.pdb has 201 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7WLW-p2.pdb: pdb_df has 68 rows, RDKit non-H atoms has 59
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7WLW-p2.pdb
filtered-rdkit-fpocket-5A/unlabeled/7WLW-p44.pdb has 243 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7WLW-p49.pdb: pdb_df has 141 rows, RDKit non-H atoms has 135
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7WLW-p49.pdb

[11:14:34] Explicit valence for atom # 64 O, 3, is greater than permitted

[WARN] RDKit sanitize warning for: filtered-rdkit-fpocket-5A/unlabeled/7WQ4-p11.pdb
filtered-rdkit-fpocket-5A/unlabeled/7WQ4-p61.pdb has 202 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WU4-p1.pdb has 304 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WU4-p56.pdb has 221 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WU5-p52.pdb has 222 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYT-p127.pdb has 257 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYT-p172.pdb has 217 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYU-p114.pdb has 250 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYU-p118.pdb has 250 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYU-p219.pdb has 225 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYU-p220.pdb has 225 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYU-p221.pdb has 205 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYU-p222.pdb has 205 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYX-p190.pdb has 232 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYX-p192.pdb has 232 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYX-p203.pdb has 256 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYX-p204.pdb has 256 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYZ-p169.pdb has 229 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYZ-p183.pdb has 229 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYZ-p203.pdb has 201 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYZ-p204.pdb has 201 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYZ-p208.pdb has 241 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WYZ-p210.pdb has 241 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WZ0-p5.pdb has 214 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7WZ0-p9.pdb has 214 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7X2C-p2.pdb: pdb_df has 227 rows, RDKit non-H atoms has 221
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7X2C-p2.pdb
filtered-rdkit-fpocket-5A/unlabeled/7X2C-p29.pdb has 209 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7X2C-p46.pdb: pdb_df has 71 rows, RDKit non-H atoms has 60
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7X2C-p46.pdb
filtered-rdkit-fpocket-5A/unlabeled/7X2C-p53.pdb has 244 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7X2D-p1.pdb: pdb_df has 385 rows, RDKit non-H atoms has 373
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7X2D-p1.pdb
filtered-rdkit-fpocket-5A/unlabeled/7X2D-p7.pdb has 203 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7X2D-p30.pdb has 202 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7X2D-p57.pdb: pdb_df has 92 rows, RDKit non-H atoms has 81
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7X2D-p57.pdb
filtered-rdkit-fpocket-5A/unlabeled/7X2D-p62.pdb has 209 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7X2F-p2.pdb has 305 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7X2F-p38.pdb: pdb_df has 60 rows, RDKit non-H atoms has 58
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7X2F-p38.pdb
filtered-rdkit-fpocket-5A/unlabeled/7X2F-p57.pdb has 246 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7X2F-p70.pdb has 221 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7X21-p95.pdb has 223 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7X22-p72.pdb has 218 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7X24-p76.pdb has 289 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7X24-p78.pdb has 213 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XBX-p6.pdb has 269 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XER-p27.pdb has 239 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XER-p44.pdb has 239 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XER-p150.pdb has 239 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XER-p194.pdb has 239 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XT8-p72.pdb has 201 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XT9-p70.pdb has 251 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XTC-p4.pdb has 205 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XTC-p15.pdb has 266 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7XVE-p25.pdb: pdb_df has 49 rows, RDKit non-H atoms has 38
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7XVE-p25.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/7XVE-p71.pdb: pdb_df has 41 rows, RDKit non-H atoms has 30
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/7XVE-p71.pdb
filtered-rdkit-fpocket-5A/unlabeled/7XVE-p102.pdb has 260 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XW5-p101.pdb has 207 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XW6-p108.pdb has 210 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XW6-p112.pdb has 208 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XZH-p1.pdb has 272 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XZH-p182.pdb has 219 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XZH-p340.pdb has 219 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XZH-p352.pdb has 251 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7XZH-p354.pdb has 232 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7Y27-p32.pdb has 230 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7Y45-p2.pdb has 423 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7Y45-p6.pdb has 423 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7Y45-p224.pdb has 234 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7Y45-p225.pdb has 234 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7YAE-p23.pdb has 233 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7YFC-p4.pdb has 206 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7YFC-p69.pdb has 208 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7YFD-p3.pdb has 267 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7YFD-p84.pdb has 241 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7YKD-p1.pdb has 320 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7YKD-p63.pdb has 234 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7ZI0-p1.pdb has 395 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7ZI0-p2.pdb has 387 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7ZI0-p102.pdb has 278 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/7ZI0-p106.pdb has 231 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8A2O-p26.pdb: pdb_df has 24 rows, RDKit non-H atoms has 18
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8A2O-p26.pdb
filtered-rdkit-fpocket-5A/unlabeled/8BHT-p80.pdb has 250 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8BI0-p90.pdb has 214 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8BI0-p91.pdb has 276 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8BJF-p89.pdb has 367 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8C9W-p17.pdb: pdb_df has 37 rows, RDKit non-H atoms has 29
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8C9W-p17.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CIC-p5.pdb: pdb_df has 138 rows, RDKit non-H atoms has 130
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CIC-p5.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CIC-p15.pdb: pdb_df has 71 rows, RDKit non-H atoms has 60
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CIC-p15.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CIC-p17.pdb: pdb_df has 40 rows, RDKit non-H atoms has 29
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CIC-p17.pdb
filtered-rdkit-fpocket-5A/unlabeled/8CRQ-p72.pdb has 213 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8CRR-p64.pdb has 224 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8CRR-p66.pdb has 296 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8CRT-p6.pdb has 201 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CRT-p13.pdb: pdb_df has 69 rows, RDKit non-H atoms has 57
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CRT-p13.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CRT-p126.pdb: pdb_df has 57 rows, RDKit non-H atoms has 45
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CRT-p126.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CS9-p7.pdb: pdb_df has 110 rows, RDKit non-H atoms has 98
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CS9-p7.pdb
filtered-rdkit-fpocket-5A/unlabeled/8CS9-p135.pdb has 291 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CS9-p314.pdb: pdb_df has 96 rows, RDKit non-H atoms has 84
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CS9-p314.pdb
filtered-rdkit-fpocket-5A/unlabeled/8CS9-p438.pdb has 274 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8CS9-p448.pdb has 237 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8CS9-p473.pdb has 259 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8CS9-p479.pdb has 204 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8CS9-p485.pdb has 210 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8CS9-p488.pdb has 232 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8CS9-p489.pdb has 214 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CSX-p20.pdb: pdb_df has 80 rows, RDKit non-H atoms has 68
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CSX-p20.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CT2-p8.pdb: pdb_df has 77 rows, RDKit non-H atoms has 66
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CT2-p8.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CT2-p10.pdb: pdb_df has 60 rows, RDKit non-H atoms has 49
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CT2-p10.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CT2-p14.pdb: pdb_df has 82 rows, RDKit non-H atoms has 71
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CT2-p14.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CT2-p20.pdb: pdb_df has 63 rows, RDKit non-H atoms has 52
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CT2-p20.pdb
filtered-rdkit-fpocket-5A/unlabeled/8CT3-p70.pdb has 243 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8CT3-p73.pdb has 243 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CTE-p11.pdb: pdb_df has 107 rows, RDKit non-H atoms has 96
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CTE-p11.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CTE-p16.pdb: pdb_df has 42 rows, RDKit non-H atoms has 30
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CTE-p16.pdb
filtered-rdkit-fpocket-5A/unlabeled/8CTE-p17.pdb has 238 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CTE-p38.pdb: pdb_df has 85 rows, RDKit non-H atoms has 74
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CTE-p38.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CTE-p67.pdb: pdb_df has 60 rows, RDKit non-H atoms has 49
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CTE-p67.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CTE-p234.pdb: pdb_df has 81 rows, RDKit non-H atoms has 70
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CTE-p234.pdb
filtered-rdkit-fpocket-5A/unlabeled/8CTE-p264.pdb has 298 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8CTE-p315.pdb has 277 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8CTE-p317.pdb has 243 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8CTE-p319.pdb has 243 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CU7-p7.pdb: pdb_df has 150 rows, RDKit non-H atoms has 142
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CU7-p7.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8CU7-p26.pdb: pdb_df has 71 rows, RDKit non-H atoms has 64
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8CU7-p26.pdb
filtered-rdkit-fpocket-5A/unlabeled/8DPI-p26.pdb has 240 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8E0G-p4.pdb has 203 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8E0G-p8.pdb: pdb_df has 54 rows, RDKit non-H atoms has 43
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8E0G-p8.pdb
filtered-rdkit-fpocket-5A/unlabeled/8EFL-p119.pdb has 236 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8EFO-p1.pdb has 340 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8EIO-p1.pdb has 871 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8EIO-p88.pdb has 315 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8EIQ-p87.pdb has 834 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8EIQ-p89.pdb has 356 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8EOG-p179.pdb has 211 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8EOG-p196.pdb has 394 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8EOG-p197.pdb has 221 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8EOG-p205.pdb has 339 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8EPL-p74.pdb has 484 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8EPL-p214.pdb has 287 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8EPL-p222.pdb has 279 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8EPL-p225.pdb has 210 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8F6Z-p14.pdb has 202 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8F7W-p18.pdb has 217 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8FD7-p85.pdb has 325 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8FD7-p204.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8FHD-p8.pdb has 345 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8FHD-p102.pdb has 214 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8FHS-p195.pdb has 331 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8FHS-p218.pdb has 303 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8G05-p3.pdb has 232 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8G05-p62.pdb has 211 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8GHF-p242.pdb has 205 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8GNE-p12.pdb: pdb_df has 42 rows, RDKit non-H atoms has 34
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8GNE-p12.pdb
filtered-rdkit-fpocket-5A/unlabeled/8GNK-p46.pdb has 424 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8HA0-p3.pdb has 231 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8HAF-p1.pdb has 380 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8HDO-p3.pdb has 267 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8HDP-p7.pdb has 312 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8HK2-p56.pdb has 217 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8HNK-p1.pdb has 288 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8HNK-p79.pdb has 209 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8HSI-p29.pdb has 215 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8I2G-p1.pdb has 289 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8I2G-p108.pdb has 272 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8I2G-p113.pdb has 225 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8IJV-p66.pdb has 227 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8IJX-p80.pdb has 254 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8IM7-p107.pdb has 201 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8IRU-p1.pdb has 268 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8IVL-p10.pdb: pdb_df has 39 rows, RDKit non-H atoms has 33
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8IVL-p10.pdb
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8IVL-p11.pdb: pdb_df has 40 rows, RDKit non-H atoms has 31
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8IVL-p11.pdb
filtered-rdkit-fpocket-5A/unlabeled/8IZ4-p43.pdb has 203 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8IZB-p2.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8IZB-p73.pdb has 215 atoms, exceeding the limit of 200
[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/unlabeled/8J6M-p8.pdb: pdb_df has 90 rows, RDKit non-H atoms has 81
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/unlabeled/8J6M-p8.pdb
filtered-rdkit-fpocket-5A/unlabeled/8J6M-p85.pdb has 207 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8J6M-p88.pdb has 248 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8J7F-p1-positive.pdb has 250 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8J7F-p2-positive.pdb has 213 atoms, exceeding the limit of 200

[11:18:06] Explicit valence for atom # 57 O, 3, is greater than permitted
[11:18:06] Explicit valence for atom # 11 O, 3, is greater than permitted

[WARN] RDKit sanitize warning for: filtered-rdkit-fpocket-5A/unlabeled/8XC1-p40.pdb
filtered-rdkit-fpocket-5A/unlabeled/8XC1-p44.pdb has 214 atoms, exceeding the limit of 200
[WARN] RDKit sanitize warning for: filtered-rdkit-fpocket-5A/unlabeled/8XC1-p51.pdb

[11:18:06] Explicit valence for atom # 33 C, 5, is greater than permitted
[11:18:06] Explicit valence for atom # 2 C, 5, is greater than permitted

[WARN] RDKit sanitize warning for: filtered-rdkit-fpocket-5A/unlabeled/8XC1-p74.pdb
[WARN] RDKit sanitize warning for: filtered-rdkit-fpocket-5A/unlabeled/8XC1-p79.pdb
filtered-rdkit-fpocket-5A/unlabeled/8XQJ-p1.pdb has 223 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8XQL-p1-positive.pdb has 201 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8XQL-p2.pdb has 318 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8XQL-p50.pdb has 206 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8XQL-p59.pdb has 232 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8XQL-p70.pdb has 225 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8XQP-p1.pdb has 507 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8XQP-p24.pdb has 231 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8XQS-p9.pdb has 221 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8XQT-p1-positive.pdb has 279 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8XQT-p3-positive.pdb has 233 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8Y6I-p51.pdb has 231 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8Y6I-p64.pdb has 266 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8Y69-p143.pdb has 353 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8Y69-p154.pdb has 263 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8YJP-p3.pdb has 731 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8YJP-p49.pdb has 234 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8YK0-p41-positive.pdb has 486 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8YKY-p60.pdb has 203 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8YN9-p69.pdb has 273 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8YNA-p66.pdb has 286 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8YUT-p17.pdb has 288 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8YUT-p68.pdb has 209 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8YUU-p39.pdb has 263 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8Z8Z-p63.pdb has 407 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8Z8Z-p64.pdb has 407 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8ZJG-p82.pdb has 203 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8ZSJ-p23.pdb has 253 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/8ZYJ-p1.pdb has 255 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9B8O-p176.pdb has 581 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9B8O-p185.pdb has 202 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9B8O-p187.pdb has 311 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9B8O-p193.pdb has 286 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9BBC-p1.pdb has 584 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9BBC-p83.pdb has 379 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9BR2-p99.pdb has 214 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9BR2-p113.pdb has 540 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9BUK-p102.pdb has 513 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9BUK-p130.pdb has 206 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9BUK-p131.pdb has 230 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9BVH-p20.pdb has 253 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9BVH-p50.pdb has 253 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9BVH-p66.pdb has 226 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9BVH-p128.pdb has 253 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9BVH-p132.pdb has 253 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9C12-p2.pdb has 208 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9C12-p109.pdb has 241 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CIA-p1.pdb has 340 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CQ4-p1.pdb has 285 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CQ4-p72.pdb has 338 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CUI-p206.pdb has 327 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CUI-p214.pdb has 242 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CUI-p215.pdb has 349 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CUI-p216.pdb has 257 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CUI-p219.pdb has 283 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CUK-p52.pdb has 300 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CUK-p241.pdb has 202 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CZM-p189.pdb has 234 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CZM-p222.pdb has 234 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CZM-p346.pdb has 240 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CZM-p366.pdb has 212 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CZQ-p29.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CZQ-p54.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CZQ-p322.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CZQ-p338.pdb has 214 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CZQ-p343.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CZQ-p345.pdb has 222 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CZQ-p354.pdb has 219 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9CZQ-p362.pdb has 214 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D3E-p45.pdb has 236 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D18-p29.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D18-p54.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D18-p323.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D18-p337.pdb has 214 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D18-p342.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D18-p345.pdb has 222 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D18-p355.pdb has 219 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D18-p362.pdb has 214 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D19-p28.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D19-p54.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D19-p325.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D19-p339.pdb has 214 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D19-p344.pdb has 220 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D19-p346.pdb has 222 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D19-p356.pdb has 219 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9D19-p363.pdb has 214 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DBK-p20.pdb has 218 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DBK-p64.pdb has 229 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DNW-p96.pdb has 370 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DNW-p98.pdb has 272 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DNX-p117.pdb has 286 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DNX-p130.pdb has 294 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DNY-p61.pdb has 405 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DNY-p105.pdb has 218 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DNY-p106.pdb has 213 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DNY-p108.pdb has 252 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DNZ-p7.pdb has 392 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DNZ-p114.pdb has 241 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DNZ-p122.pdb has 249 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DO0-p64.pdb has 222 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DO0-p117.pdb has 497 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DO0-p118.pdb has 298 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVJ-p60.pdb has 227 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVJ-p61.pdb has 204 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVK-p61.pdb has 259 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVL-p55.pdb has 325 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVL-p56.pdb has 219 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVM-p12.pdb has 232 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVM-p94.pdb has 254 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVN-p96.pdb has 334 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVN-p100.pdb has 435 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVN-p101.pdb has 221 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVO-p65.pdb has 309 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVO-p92.pdb has 255 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVP-p76.pdb has 309 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVP-p87.pdb has 230 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DVP-p95.pdb has 222 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DW9-p102.pdb has 264 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DW9-p107.pdb has 344 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DW9-p108.pdb has 686 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DXQ-p121.pdb has 469 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DXQ-p122.pdb has 204 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DXQ-p124.pdb has 215 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DXQ-p125.pdb has 266 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DXQ-p126.pdb has 431 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DXQ-p127.pdb has 266 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DXQ-p128.pdb has 231 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9DXQ-p129.pdb has 217 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9EAI-p1.pdb has 238 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9EUP-p45.pdb has 213 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9F41-p4-positive.pdb has 217 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9GE2-p1.pdb has 251 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9GE2-p66.pdb has 205 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9GYO-p10.pdb has 232 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9GYO-p49.pdb has 278 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9INE-p12.pdb has 230 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9INE-p47.pdb has 218 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9INF-p50.pdb has 236 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9ITB-p67.pdb has 258 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9ITE-p75.pdb has 310 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9ITG-p10.pdb has 279 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9ITG-p63.pdb has 201 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9J3X-p83.pdb has 271 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9J3X-p84.pdb has 278 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9J7M-p3.pdb has 260 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9J7N-p34.pdb has 258 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9J40-p73.pdb has 221 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9J40-p75.pdb has 242 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9J40-p80.pdb has 284 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9J40-p81.pdb has 246 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9J97-p54.pdb has 204 atoms, exceeding the limit of 200
filtered-rdkit-fpocket-5A/unlabeled/9K7B-p31.pdb has 487 atoms, exceeding the limit of 200

In [14]:
feature_names = [
    'C', 'CA', 'CB', 'CD', 'CD1', 'CD2', 'CE', 'CE1', 'CE2', 'CE3',
    'CG', 'CG1', 'CG2', 'CH2', 'CZ', 'CZ2', 'CZ3',

    # Oxygen (8)
    'O', 'OH', 'OD1', 'OD2', 'OE1', 'OE2', 'OG', 'OG1',

    # Nitrogen (9)
    'N', 'NE', 'NE1', 'NE2', 'ND1', 'ND2', 'NZ', 'NH1', 'NH2',

    # Sulfur (2)
    'SD', 'SG',

    # Unknown (1)
    'UNKNOWN',

    "hybridization_SP",                         
    "hybridization_SP2",                        
    "hybridization_SP3",                        

    "partial_charge",                    

    "is_in_ring",                               
    "is_aromatic",                              

    "residue_acidic_ASP_GLU",                   
    "residue_basic_LYS_ARG",                    
    "residue_HIS",                              
    "residue_CYS",                              
    "residue_polar_ASN_GLN_SER_THR",            
    "residue_GLY",                              
    "residue_PRO",                              
    "residue_aromatic_PHE_TYR_TRP",             
    "residue_hydrophobic_ALA_ILE_LEU_MET_VAL"   
]

In [15]:
max_atoms = 200
# positives
output_dir = "cholesterol-rdkit-fpocket-5A/positive"
np.set_printoptions(threshold=np.inf)

positive_files = glob.glob("filtered-rdkit-fpocket-5A/positive/*.pdb")
positive_files = sorted(positive_files, key=natural_sort_key)

# Trackers
feature_usage = None                 # total atom-level usage
feature_file_presence = None         # per-file presence
num_features = None
total_atoms_all_files = 0
total_files = len(positive_files)

for file in positive_files:
    pdb_df = pdb_to_dataframe(file)
    coords, encoded_matrix = rdkit_coords_and_encoding(file, pdb_df, pqr_cache=pqr_cache)
    if coords is None or encoded_matrix is None:
        print(f"[SKIP] Failed encoding for {file}")
        continue
    inverse_distance = compute_inverse_pairwise_distances_from_coords(coords)

    if inverse_distance.shape[0] != encoded_matrix.shape[0]:
        raise ValueError(
            f"Atom mismatch in {file}: "
            f"inverse_distance={inverse_distance.shape}, "
            f"encoded_matrix={encoded_matrix.shape}"
        )

    # Initialize trackers
    if feature_usage is None:
        num_features = encoded_matrix.shape[1]
        feature_usage = np.zeros(num_features, dtype=np.int64)
        feature_file_presence = np.zeros(num_features, dtype=np.int64)

    num_atoms = inverse_distance.shape[0]
    total_atoms_all_files += num_atoms

    # ---- Atom-level usage ----
    feature_usage += (encoded_matrix != 0).sum(axis=0).astype(np.int64)

    # ---- File-level presence ----
    feature_file_presence += (encoded_matrix != 0).any(axis=0).astype(np.int64)

    combined_matrix = inverse_distance @ encoded_matrix

    if num_atoms > max_atoms:
        print(f"{file} has {num_atoms} atoms, exceeding the limit of {max_atoms}")
        raise Exception("Too many atoms!")

    combined_matrix = np.pad(
        combined_matrix,
        ((0, max_atoms - num_atoms), (0, 0)),
        mode='constant'
    )

# ---- AFTER LOOP ----

print("\n=== FEATURE USAGE SUMMARY ===")
print(f"Total atoms: {total_atoms_all_files}")
print(f"Total files: {total_files}\n")

for i in range(num_features):
    atom_pct = (feature_usage[i] / total_atoms_all_files) * 100 if total_atoms_all_files > 0 else 0
    file_pct = (feature_file_presence[i] / total_files) * 100 if total_files > 0 else 0

    print(
        f"{i:2d} | {feature_names[i]:40s} | "
        f"atoms: {feature_usage[i]:8d} ({atom_pct:7.3f}%) | "
        f"files: {feature_file_presence[i]:4d}/{total_files} ({file_pct:6.2f}%)"
    )

# ---- UNUSED FEATURES ----

unused_features = np.where(feature_usage == 0)[0]

print("\n=== UNUSED FEATURES ===")
for i in unused_features:
    print(f"{i:2d} | {feature_names[i]}")

[WARNING] Atom count mismatch for filtered-rdkit-fpocket-5A/positive/5NM4-filtered.pdb: pdb_df has 72 rows, RDKit non-H atoms has 67
[SKIP] Failed encoding for filtered-rdkit-fpocket-5A/positive/5NM4-filtered.pdb

=== FEATURE USAGE SUMMARY ===
Total atoms: 32804
Total files: 770

 0 | C                                        | atoms:     3949 ( 12.038%) | files:  769/770 ( 99.87%)
 1 | CA                                       | atoms:     3949 ( 12.038%) | files:  769/770 ( 99.87%)
 2 | CB                                       | atoms:     3695 ( 11.264%) | files:  769/770 ( 99.87%)
 3 | CD                                       | atoms:      352 (  1.073%) | files:  302/770 ( 39.22%)
 4 | CD1                                      | atoms:     2029 (  6.185%) | files:  729/770 ( 94.68%)
 5 | CD2                                      | atoms:     1528 (  4.658%) | files:  677/770 ( 87.92%)
 6 | CE                                       | atoms:      155 (  0.473%) | files:  131/770 ( 17.01%)
 7 | CE1                                      | atoms:      773 (  2.356%) | files:  496/770 ( 64.42%)
 8 | CE2                                      | atoms:      966 (  2.945%) | files:  591/770 ( 76.75%)
 9 | CE3                                      | atoms:      238 (  0.726%) | files:  222/770 ( 28.83%)
10 | CG                                       | atoms:     2064 (  6.292%) | files:  723/770 ( 93.90%)
11 | CG1                                      | atoms:      805 (  2.454%) | files:  521/770 ( 67.66%)
12 | CG2                                      | atoms:      947 (  2.887%) | files:  564/770 ( 73.25%)
13 | CH2                                      | atoms:      238 (  0.726%) | files:  222/770 ( 28.83%)
14 | CZ                                       | atoms:      800 (  2.439%) | files:  494/770 ( 64.16%)
15 | CZ2                                      | atoms:      238 (  0.726%) | files:  222/770 ( 28.83%)
16 | CZ3                                      | atoms:      238 (  0.726%) | files:  222/770 ( 28.83%)
17 | O                                        | atoms:     3949 ( 12.038%) | files:  769/770 ( 99.87%)
18 | OH                                       | atoms:      266 (  0.811%) | files:  225/770 ( 29.22%)
19 | OD1                                      | atoms:       75 (  0.229%) | files:   67/770 (  8.70%)
20 | OD2                                      | atoms:       24 (  0.073%) | files:   24/770 (  3.12%)
21 | OE1                                      | atoms:      125 (  0.381%) | files:  120/770 ( 15.58%)
22 | OE2                                      | atoms:       82 (  0.250%) | files:   81/770 ( 10.52%)
23 | OG                                       | atoms:      227 (  0.692%) | files:  196/770 ( 25.45%)
24 | OG1                                      | atoms:      142 (  0.433%) | files:  127/770 ( 16.49%)
25 | N                                        | atoms:     3949 ( 12.038%) | files:  769/770 ( 99.87%)
26 | NE                                       | atoms:       72 (  0.219%) | files:   71/770 (  9.22%)
27 | NE1                                      | atoms:      238 (  0.726%) | files:  222/770 ( 28.83%)
28 | NE2                                      | atoms:       88 (  0.268%) | files:   82/770 ( 10.65%)
29 | ND1                                      | atoms:       45 (  0.137%) | files:   44/770 (  5.71%)
30 | ND2                                      | atoms:       51 (  0.155%) | files:   46/770 (  5.97%)
31 | NZ                                       | atoms:       46 (  0.140%) | files:   45/770 (  5.84%)
32 | NH1                                      | atoms:       72 (  0.219%) | files:   71/770 (  9.22%)
33 | NH2                                      | atoms:       72 (  0.219%) | files:   71/770 (  9.22%)
34 | SD                                       | atoms:      109 (  0.332%) | files:   97/770 ( 12.60%)
35 | SG                                       | atoms:      208 (  0.634%) | files:  145/770 ( 18.83%)
36 | UNKNOWN                                  | atoms:        0 (  0.000%) | files:    0/770 (  0.00%)
37 | hybridization_SP                         | atoms:        0 (  0.000%) | files:    0/770 (  0.00%)
38 | hybridization_SP2                        | atoms:    16703 ( 50.918%) | files:  769/770 ( 99.87%)
39 | hybridization_SP3                        | atoms:    16101 ( 49.082%) | files:  769/770 ( 99.87%)
40 | partial_charge                           | atoms:    32487 ( 99.034%) | files:  762/770 ( 98.96%)
41 | is_in_ring                               | atoms:     7280 ( 22.192%) | files:  626/770 ( 81.30%)
42 | is_aromatic                              | atoms:     6735 ( 20.531%) | files:  603/770 ( 78.31%)
43 | residue_acidic_ASP_GLU                   | atoms:      935 (  2.850%) | files:   99/770 ( 12.86%)
44 | residue_basic_LYS_ARG                    | atoms:     1221 (  3.722%) | files:  113/770 ( 14.68%)
45 | residue_HIS                              | atoms:      450 (  1.372%) | files:   44/770 (  5.71%)
46 | residue_CYS                              | atoms:     1248 (  3.804%) | files:  145/770 ( 18.83%)
47 | residue_polar_ASN_GLN_SER_THR            | atoms:     3151 (  9.606%) | files:  334/770 ( 43.38%)
48 | residue_GLY                              | atoms:     1016 (  3.097%) | files:  204/770 ( 26.49%)
49 | residue_PRO                              | atoms:      763 (  2.326%) | files:  102/770 ( 13.25%)
50 | residue_aromatic_PHE_TYR_TRP             | atoms:    11626 ( 35.441%) | files:  594/770 ( 77.14%)
51 | residue_hydrophobic_ALA_ILE_LEU_MET_VAL  | atoms:    12394 ( 37.782%) | files:  672/770 ( 87.27%)

=== UNUSED FEATURES ===
36 | UNKNOWN
37 | hybridization_SP

In [ ]:
max_atoms = 200
# unlabeleds
output_dir = "cholesterol-rdkit-fpocket-5A/unlabeled"
np.set_printoptions(threshold=np.inf)

unlabeled_files = glob.glob("filtered-rdkit-fpocket-5A/unlabeled/*.pdb")
unlabeled_files = sorted(unlabeled_files, key=natural_sort_key)

# Trackers
feature_usage = None                 # total atom-level usage
feature_file_presence = None         # per-file presence
num_features = None
total_atoms_all_files = 0
total_files = len(unlabeled_files)

for file in unlabeled_files:
    pdb_df = pdb_to_dataframe(file)
    coords, encoded_matrix = rdkit_coords_and_encoding(file, pdb_df, pqr_cache=pqr_cache)
    if coords is None or encoded_matrix is None:
        print(f"[SKIP] Failed encoding for {file}")
        continue
    inverse_distance = compute_inverse_pairwise_distances_from_coords(coords)

    if inverse_distance.shape[0] != encoded_matrix.shape[0]:
        raise ValueError(
            f"Atom mismatch in {file}: "
            f"inverse_distance={inverse_distance.shape}, "
            f"encoded_matrix={encoded_matrix.shape}"
        )

    # Initialize trackers
    if feature_usage is None:
        num_features = encoded_matrix.shape[1]
        feature_usage = np.zeros(num_features, dtype=np.int64)
        feature_file_presence = np.zeros(num_features, dtype=np.int64)

    num_atoms = inverse_distance.shape[0]
    total_atoms_all_files += num_atoms

    # ---- Atom-level usage ----
    feature_usage += (encoded_matrix != 0).sum(axis=0).astype(np.int64)

    # ---- File-level presence ----
    feature_file_presence += (encoded_matrix != 0).any(axis=0).astype(np.int64)

    combined_matrix = inverse_distance @ encoded_matrix

    if num_atoms > max_atoms:
        print(f"{file} has {num_atoms} atoms, exceeding the limit of {max_atoms}")
        #raise Exception("Too many atoms!")
        continue

    combined_matrix = np.pad(
        combined_matrix,
        ((0, max_atoms - num_atoms), (0, 0)),
        mode='constant'
    )

# ---- AFTER LOOP ----

print("\n=== FEATURE USAGE SUMMARY ===")
print(f"Total atoms: {total_atoms_all_files}")
print(f"Total files: {total_files}\n")

for i in range(num_features):
    atom_pct = (feature_usage[i] / total_atoms_all_files) * 100 if total_atoms_all_files > 0 else 0
    file_pct = (feature_file_presence[i] / total_files) * 100 if total_files > 0 else 0

    print(
        f"{i:2d} | {feature_names[i]:40s} | "
        f"atoms: {feature_usage[i]:8d} ({atom_pct:7.3f}%) | "
        f"files: {feature_file_presence[i]:4d}/{total_files} ({file_pct:6.2f}%)"
    )

# ---- UNUSED FEATURES ----

unused_features = np.where(feature_usage == 0)[0]

print("\n=== UNUSED FEATURES ===")
for i in unused_features:
    print(f"{i:2d} | {feature_names[i]}")

In [20]:
import os
import glob
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 300)
pd.set_option("display.max_colwidth", 200)

def build_atom_level_feature_table(file_path, pqr_cache=None):
    """
    Returns a dataframe with:
      - original atom information from the PDB
      - active RDKit/RDKit-derived encoded features for each atom
    """
    pdb_df = pdb_to_dataframe(file_path).copy()
    coords, encoded_matrix = rdkit_coords_and_encoding(file_path, pdb_df, pqr_cache=pqr_cache)

    if coords is None or encoded_matrix is None:
        print(f"[SKIP] Could not encode: {file_path}")
        return None, None, None

    if len(pdb_df) != encoded_matrix.shape[0]:
        print(f"[SKIP] Atom count mismatch for {file_path}: pdb_df={len(pdb_df)}, encoded={encoded_matrix.shape[0]}")
        return None, None, None

    atom_table = pdb_df.copy()

    # Add coordinate columns actually used by RDKit encoding
    atom_table["RDKit_X"] = coords[:, 0]
    atom_table["RDKit_Y"] = coords[:, 1]
    atom_table["RDKit_Z"] = coords[:, 2]

    # Add full feature vector columns
    for i, feat_name in enumerate(feature_names):
        atom_table[feat_name] = encoded_matrix[:, i]

    # Add easy-to-read active feature names per atom
    def active_features(row_vec):
        names = []
        for j, val in enumerate(row_vec):
            if feature_names[j] == "partial_charge":
                names.append(f"partial_charge={val:.4f}")
            elif val != 0:
                names.append(feature_names[j])
        return names

    atom_table["active_feature_names"] = [active_features(row) for row in encoded_matrix]

    return atom_table, coords, encoded_matrix


def summarize_feature_usage_over_files(file_list, pqr_cache=None):
    """
    Evaluates feature usage across a list of PDB files.
    Returns:
      - summary_df
      - per_file_results
    """
    feature_usage = np.zeros(len(feature_names), dtype=np.int64)
    feature_file_presence = np.zeros(len(feature_names), dtype=np.int64)

    total_atoms = 0
    processed_files = 0
    skipped_files = []

    per_file_results = []

    for file_path in file_list:
        pdb_df = pdb_to_dataframe(file_path)
        coords, encoded_matrix = rdkit_coords_and_encoding(file_path, pdb_df, pqr_cache=pqr_cache)

        if coords is None or encoded_matrix is None:
            skipped_files.append(file_path)
            continue

        if encoded_matrix.shape[1] != len(feature_names):
            skipped_files.append(file_path)
            continue

        processed_files += 1
        total_atoms += encoded_matrix.shape[0]

        feature_usage += (encoded_matrix != 0).sum(axis=0).astype(np.int64)
        feature_file_presence += (encoded_matrix != 0).any(axis=0).astype(np.int64)

        per_file_results.append({
            "file": file_path,
            "num_atoms": encoded_matrix.shape[0],
            "num_features_used": int((encoded_matrix != 0).any(axis=0).sum())
        })

    summary_rows = []
    for i, feat_name in enumerate(feature_names):
        atom_pct = (feature_usage[i] / total_atoms * 100) if total_atoms > 0 else 0.0
        file_pct = (feature_file_presence[i] / processed_files * 100) if processed_files > 0 else 0.0
        summary_rows.append({
            "feature_index": i,
            "feature_name": feat_name,
            "atom_count_nonzero": int(feature_usage[i]),
            "atom_percent_nonzero": atom_pct,
            "files_present": int(feature_file_presence[i]),
            "file_percent_present": file_pct
        })

    summary_df = pd.DataFrame(summary_rows).sort_values(
        by=["atom_count_nonzero", "files_present"],
        ascending=False
    ).reset_index(drop=True)

    print("=== RDKit FEATURE EVALUATION SUMMARY ===")
    print(f"Processed files: {processed_files}")
    print(f"Skipped files:   {len(skipped_files)}")
    print(f"Total atoms:     {total_atoms}")

    if skipped_files:
        print("\nSkipped examples:")
        for f in skipped_files[:10]:
            print(" -", f)

    return summary_df, pd.DataFrame(per_file_results), skipped_files


# -----------------------------
# Choose which files to evaluate
# -----------------------------
positive_files = sorted(glob.glob("filtered-rdkit-fpocket-5A/positive/*.pdb"), key=natural_sort_key)
unlabeled_files = sorted(glob.glob("filtered-rdkit-fpocket-5A/unlabeled/*.pdb"), key=natural_sort_key)

print(f"Positive files found:  {len(positive_files)}")
print(f"Unlabeled files found: {len(unlabeled_files)}")

# Evaluate all files
all_files = positive_files[:1]
feature_summary_df, per_file_df, skipped_files = summarize_feature_usage_over_files(all_files, pqr_cache=pqr_cache)

print("\n=== Top feature usage summary ===")
display(feature_summary_df.head(25))

print("\n=== Per-file summary ===")
display(per_file_df.head(20))

unused_df = feature_summary_df[feature_summary_df["atom_count_nonzero"] == 0].copy()
print("\n=== Unused features ===")
display(unused_df if not unused_df.empty else pd.DataFrame({"message": ["No completely unused features found."]}))

# -----------------------------
# Show one example file in detail
# -----------------------------
example_file = positive_files[0] if len(positive_files) > 0 else (unlabeled_files[0] if len(unlabeled_files) > 0 else None)

if example_file is not None:
    print(f"\n=== Detailed atom-level view for: {example_file} ===")
    atom_feature_table, coords, encoded_matrix = build_atom_level_feature_table(example_file, pqr_cache=pqr_cache)

    if atom_feature_table is not None:
        # Show original PDB atoms + important encoded columns
        preview_cols = [
            "Atom Name", "Residue Name", "Residue ID", "Chain ID",
            "X", "Y", "Z",
            "active_feature_names"
        ]

        preview_cols = [c for c in preview_cols if c in atom_feature_table.columns]
        display(atom_feature_table[preview_cols].head(50))

        print("\n=== Full atom-level table with all encoded features available in `atom_feature_table` ===")
        print(f"Shape: {atom_feature_table.shape}")

        # Optional save
        out_csv = os.path.splitext(os.path.basename(example_file))[0] + "_atom_level_rdkit_features.csv"
        atom_feature_table.to_csv(out_csv, index=False)
        print(f"Saved atom-level feature table to: {out_csv}")
else:
    print("No filtered PDB files were found.")

Positive files found:  770
Unlabeled files found: 72770
=== RDKit FEATURE EVALUATION SUMMARY ===
Processed files: 1
Skipped files:   0
Total atoms:     40

=== Top feature usage summary ===

    feature_index                             feature_name  atom_count_nonzero  atom_percent_nonzero  files_present  file_percent_present
0              40                           partial_charge                  40                 100.0              1                 100.0
1              51  residue_hydrophobic_ALA_ILE_LEU_MET_VAL                  28                  70.0              1                 100.0
2              39                        hybridization_SP3                  21                  52.5              1                 100.0
3              38                        hybridization_SP2                  19                  47.5              1                 100.0
4              50             residue_aromatic_PHE_TYR_TRP                  12                  30.0              1                 100.0
5              41                               is_in_ring                   6                  15.0              1                 100.0
6              42                              is_aromatic                   6                  15.0              1                 100.0
7               0                                        C                   5                  12.5              1                 100.0
8               1                                       CA                   5                  12.5              1                 100.0
9               2                                       CB                   5                  12.5              1                 100.0
10             17                                        O                   5                  12.5              1                 100.0
11             25                                        N                   5                  12.5              1                 100.0
12             10                                       CG                   3                   7.5              1                 100.0
13              4                                      CD1                   2                   5.0              1                 100.0
14              5                                      CD2                   2                   5.0              1                 100.0
15              6                                       CE                   1                   2.5              1                 100.0
16              7                                      CE1                   1                   2.5              1                 100.0
17              8                                      CE2                   1                   2.5              1                 100.0
18             11                                      CG1                   1                   2.5              1                 100.0
19             12                                      CG2                   1                   2.5              1                 100.0
20             14                                       CZ                   1                   2.5              1                 100.0
21             18                                       OH                   1                   2.5              1                 100.0
22             34                                       SD                   1                   2.5              1                 100.0
23              3                                       CD                   0                   0.0              0                   0.0
24              9                                      CE3                   0                   0.0              0                   0.0

=== Per-file summary ===

                                                   file  num_atoms  num_features_used
0  filtered-rdkit-fpocket-5A/positive/1LRI-filtered.pdb         40                 23

=== Unused features ===

    feature_index                   feature_name  atom_count_nonzero  atom_percent_nonzero  files_present  file_percent_present
23              3                             CD                   0                   0.0              0                   0.0
24              9                            CE3                   0                   0.0              0                   0.0
25             13                            CH2                   0                   0.0              0                   0.0
26             15                            CZ2                   0                   0.0              0                   0.0
27             16                            CZ3                   0                   0.0              0                   0.0
28             19                            OD1                   0                   0.0              0                   0.0
29             20                            OD2                   0                   0.0              0                   0.0
30             21                            OE1                   0                   0.0              0                   0.0
31             22                            OE2                   0                   0.0              0                   0.0
32             23                             OG                   0                   0.0              0                   0.0
33             24                            OG1                   0                   0.0              0                   0.0
34             26                             NE                   0                   0.0              0                   0.0
35             27                            NE1                   0                   0.0              0                   0.0
36             28                            NE2                   0                   0.0              0                   0.0
37             29                            ND1                   0                   0.0              0                   0.0
38             30                            ND2                   0                   0.0              0                   0.0
39             31                             NZ                   0                   0.0              0                   0.0
40             32                            NH1                   0                   0.0              0                   0.0
41             33                            NH2                   0                   0.0              0                   0.0
42             35                             SG                   0                   0.0              0                   0.0
43             36                        UNKNOWN                   0                   0.0              0                   0.0
44             37               hybridization_SP                   0                   0.0              0                   0.0
45             43         residue_acidic_ASP_GLU                   0                   0.0              0                   0.0
46             44          residue_basic_LYS_ARG                   0                   0.0              0                   0.0
47             45                    residue_HIS                   0                   0.0              0                   0.0
48             46                    residue_CYS                   0                   0.0              0                   0.0
49             47  residue_polar_ASN_GLN_SER_THR                   0                   0.0              0                   0.0
50             48                    residue_GLY                   0                   0.0              0                   0.0
51             49                    residue_PRO                   0                   0.0              0                   0.0

=== Detailed atom-level view for: filtered-rdkit-fpocket-5A/positive/1LRI-filtered.pdb ===

   Atom Name Residue Name  Residue ID Chain ID       X          Y          Z                                                                                     active_feature_names
0          N          LEU          15        A   9.387   9.230000  15.660000                  [N, hybridization_SP3, partial_charge=-0.4157, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
1         CA          LEU          15        A   8.792  10.132000  14.690000                 [CA, hybridization_SP3, partial_charge=-0.0518, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
2          C          LEU          15        A   7.748  11.037000  15.308000                   [C, hybridization_SP2, partial_charge=0.5973, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
3          O          LEU          15        A   7.390  12.069000  14.749000                  [O, hybridization_SP2, partial_charge=-0.5679, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
4         CB          LEU          15        A   8.199   9.319000  13.531000                 [CB, hybridization_SP3, partial_charge=-0.1102, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
5         CG          LEU          15        A   9.192   8.698000  12.566000                  [CG, hybridization_SP3, partial_charge=0.3531, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
6        CD1          LEU          15        A   8.533   7.640000  11.681000                [CD1, hybridization_SP3, partial_charge=-0.4121, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
7        CD2          LEU          15        A   9.819   9.763000  11.664000                [CD2, hybridization_SP3, partial_charge=-0.4121, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
8          N          VAL          16        A   7.260  10.744000  16.514000                  [N, hybridization_SP2, partial_charge=-0.4157, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
9         CA          VAL          16        A   6.234  11.603000  17.127001                 [CA, hybridization_SP3, partial_charge=-0.0875, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
10         C          VAL          16        A   6.729  13.031000  17.309999                   [C, hybridization_SP2, partial_charge=0.5973, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
11         O          VAL          16        A   5.935  13.969000  17.313999                  [O, hybridization_SP2, partial_charge=-0.5679, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
12        CB          VAL          16        A   5.753  10.968000  18.447001                  [CB, hybridization_SP3, partial_charge=0.2985, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
13       CG1          VAL          16        A   6.893  10.876000  19.447001                [CG1, hybridization_SP3, partial_charge=-0.3192, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
14       CG2          VAL          16        A   4.605  11.755000  19.047001                [CG2, hybridization_SP3, partial_charge=-0.3192, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
15         N          MET          35        A  -1.450  14.849000   6.298000                  [N, hybridization_SP3, partial_charge=-0.4157, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
16        CA          MET          35        A  -0.517  13.749000   6.440000                 [CA, hybridization_SP3, partial_charge=-0.0237, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
17         C          MET          35        A  -0.988  12.671000   7.381000                   [C, hybridization_SP2, partial_charge=0.5973, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
18         O          MET          35        A  -0.725  11.510000   7.068000                  [O, hybridization_SP2, partial_charge=-0.5679, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
19        CB          MET          35        A   0.858  14.245000   6.895000                  [CB, hybridization_SP3, partial_charge=0.0342, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
20        CG          MET          35        A   1.518  14.884000   5.648000                  [CG, hybridization_SP3, partial_charge=0.0018, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
21        SD          MET          35        A   2.963  15.776000   6.047000                 [SD, hybridization_SP3, partial_charge=-0.2737, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
22        CE          MET          35        A   2.322  17.243999   6.857000                 [CE, hybridization_SP3, partial_charge=-0.0536, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
23         N          TYR          87        A  11.157   7.223000   1.163000                             [N, hybridization_SP3, partial_charge=-0.4157, residue_aromatic_PHE_TYR_TRP]
24        CA          TYR          87        A  10.434   8.341000   0.548000                            [CA, hybridization_SP3, partial_charge=-0.0014, residue_aromatic_PHE_TYR_TRP]
25         C          TYR          87        A  10.991   9.675000   1.051000                              [C, hybridization_SP2, partial_charge=0.5973, residue_aromatic_PHE_TYR_TRP]
26         O          TYR          87        A  11.062  10.609000   0.247000                             [O, hybridization_SP2, partial_charge=-0.5679, residue_aromatic_PHE_TYR_TRP]
27        CB          TYR          87        A   8.949   8.247000   0.794000                            [CB, hybridization_SP3, partial_charge=-0.0152, residue_aromatic_PHE_TYR_TRP]
28        CG          TYR          87        A   8.260   7.240000  -0.108000   [CG, hybridization_SP2, partial_charge=-0.0011, is_in_ring, is_aromatic, residue_aromatic_PHE_TYR_TRP]
29       CD1          TYR          87        A   7.635   7.671000  -1.264000  [CD1, hybridization_SP2, partial_charge=-0.1906, is_in_ring, is_aromatic, residue_aromatic_PHE_TYR_TRP]
30       CD2          TYR          87        A   8.222   5.892000   0.140000  [CD2, hybridization_SP2, partial_charge=-0.1906, is_in_ring, is_aromatic, residue_aromatic_PHE_TYR_TRP]
31       CE1          TYR          87        A   7.004   6.781000  -2.105000  [CE1, hybridization_SP2, partial_charge=-0.2341, is_in_ring, is_aromatic, residue_aromatic_PHE_TYR_TRP]
32       CE2          TYR          87        A   7.597   4.970000  -0.679000  [CE2, hybridization_SP2, partial_charge=-0.2341, is_in_ring, is_aromatic, residue_aromatic_PHE_TYR_TRP]
33        CZ          TYR          87        A   6.974   5.423000  -1.822000    [CZ, hybridization_SP2, partial_charge=0.3226, is_in_ring, is_aromatic, residue_aromatic_PHE_TYR_TRP]
34        OH          TYR          87        A   6.341   4.559000  -2.686000                            [OH, hybridization_SP2, partial_charge=-0.5579, residue_aromatic_PHE_TYR_TRP]
35         N          ALA          88        A  11.364   9.765000   2.315000                  [N, hybridization_SP2, partial_charge=-0.4157, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
36        CA          ALA          88        A  11.890  11.069000   2.810000                  [CA, hybridization_SP3, partial_charge=0.0337, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
37         C          ALA          88        A  13.216  11.366000   2.123000                   [C, hybridization_SP2, partial_charge=0.5973, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
38         O          ALA          88        A  13.461  12.474000   1.672000                  [O, hybridization_SP2, partial_charge=-0.5679, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]
39        CB          ALA          88        A  12.035  11.104000   4.330000                 [CB, hybridization_SP3, partial_charge=-0.1825, residue_hydrophobic_ALA_ILE_LEU_MET_VAL]

=== Full atom-level table with all encoded features available in `atom_feature_table` ===
Shape: (40, 63)
Saved atom-level feature table to: 1LRI-filtered_atom_level_rdkit_features.csv